### ISSUE TITLE
Redis integration

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#1]
Inspired by [postgres](https://github.com/cachix/devenv/blob/main/src/modules/postgres.nix) integration, there should be one for redis.

**Comment by shyim** [comment]
I wanted to work on this. But I am stupid or so. I have no idea how to test it.

```
Building shell ...
error: getting status of '/nix/store/mn1giy89ni5gh5bgfc63ssy1kfwihryy-modules/redis.nix': No such file or directory
```

![image](https://user-images.githubusercontent.com/6224096/201476466-8aaf2186-c39c-4b88-a16e-838bfee292af.png)

My redis.nix is imported in the `top-level.nix` 

The git state is also added so Flake should find it.. hmmm


![image](https://user-images.githubusercontent.com/6224096/201476513-83b64b37-02cc-4753-a1ae-c7f46fd38159.png)

**Comment by shyim** [comment]
I can also create a draft pr if you want

**Comment by shyim** [comment]
I HAVE TO RUN `nix build` on any file change aaaaaaa. Got it fixed 😂
