### ISSUE TITLE
direnv reloading doesn't work

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#10]
Currently we check if we're in devenv before we activate shell, to prevent a cycle. 

This also prevents reloading, so better figure out a better way.

**Comment by ankhers** [comment]
I was trying to debug an issue with Emacs being unable to find a package. One of the things I did to debug was remove the check to see if we are already in direnv. It did not cycle. I believe direnv is smart enough to not cycle itself. For reference, I used the following script to test.

```bash
watch_file devenv.nix
watch_file devenv.yaml
watch_file devenv.lock
# if [[ ! "$DIRENV_ACTIVE" =~ (^|:)"$PWD"(:|$) ]]; then
  devenv shell
# fi
```

It is the standard one with just the `if` commented out.

Keep in mind I am no expert in direnv, so probably test yourself to ensure I don't have something strange going on my system.

**Comment by domenkozar** [comment]
Interesting, it does start to cycle for me. Linux?

**Comment by ankhers** [comment]
Yes. I am using NixOS. Not sure if it makes a difference, but I am also using zsh.
