### ISSUE TITLE
Ctrl-C in one terminal stops processes of other

### ISSUE THREAD

**Issue by tennox** [cachix/devenv#1001]
**Describe the bug**
I run one terminal pane with
`devenv up frontend` and one with `devenv up strapi`

When I pressed Ctrl-C in `strapi`, it also stopped `frontend`:
```
14:10:13 system | SIGTERM received
14:10:13 system | sending SIGTERM to page.1 (pid 115402)
14:10:14 system | page.1 stopped (rc=-15)
```
Edit: This seems to happen only sometimes :thinking: :sweat_smile: 

**Sidenote:** I have to run the process command in root dir because process is started in $PWD - but that's a bit unfortunate, as it's not a script I run, but a process that has a specific location in the monorepo

**Version:** 0.6.3

**Comment by tennox** [comment]
Terminal where I press Ctrl-C:
```
^CStopping processes...
16:18:39 system   | SIGINT received
16:18:39 system   | sending SIGTERM to strapi.1 (pid 255051)
16:18:39 system   | strapi.1 stopped (rc=-15)
```

Other terminal:
```
16:18:39 system | SIGTERM received
16:18:39 system | sending SIGTERM to page.1 (pid 264749)
16:18:39 system | page.1 stopped (rc=-15)
```

**Comment by domenkozar** [comment]
Try #1005

**Comment by tennox** [comment]
> Try #1005

Awesome 🤩 🦀
