### ISSUE TITLE
MySQL configuration on startup fails when trying to set up users

### ISSUE THREAD

**Issue by M-arcus** [cachix/devenv#1007]
**Describe the bug**
MySQL configuration on startup fails when trying to set up users after updating to newest devenv.lock

**To reproduce**
```
{ pkgs, lib, ... }:
{
  services.mysql.enable = true;
  services.mysql.package = lib.mkDefault pkgs.mysql80;
  services.mysql.initialDatabases = [{ name = "db"; }];
  services.mysql.ensureUsers = [{
    name = "db";
    password = "db";
    ensurePermissions = { "*.*" = "ALL PRIVILEGES"; };
  }];
  processes.entryscript.exec = ''
    ${pkgs.coreutils}/bin/sleep infinity
  '';
}
```
works.

But adding this breaks the devenv up command:
```
  services.mysql.settings = {
    mysql = {
      user = "db";
      password = "db";
      host = "127.0.0.1";
    };
  };
```

Error log:
```
10:59:42 mysql-configure.1 | mysqld is alive
10:59:42 mysql-configure.1 | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Version**
 
```
$ devenv version
devenv: 0.6.3
```

**Comment by M-arcus** [comment]
@schneider-felix mentioned, that this could be the cause
https://github.com/cachix/devenv/commit/71809bca1921dcc2c72e3749891ec91ed0fb78c4

**Comment by M-arcus** [comment]
@domenkozar @shyim 
Looks like it's broken again, executing `mysql` does not use the configured values anymore.

**Comment by domenkozar** [comment]
We really need a test for this

**Comment by shyim** [comment]
https://github.com/cachix/devenv/blob/main/tests/mysql/.test.sh
