### ISSUE TITLE
Allow devenv 1.0 cli to work with devenv 0.6 input

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#1017]
Right now when you open a project with old config and run `devenv shell` you get:

```
       error:
       error: The option `devenv.tmpdir' does not exist. Definition values:
       - In `<unknown-file>': "/run/user/1000/"

✖ Command produced the following output:


✔ Building shell in 0.8s.
Error:   × Command `/nix/store/kihsss6ydss74z3scq1ybdnbcrihmlx3-nix-devenv-2.21.0pre20240315_c5bbf14/bin/nix --show-trace --extra-experimental-features nix-command --extra-experimental-features flakes --option warn-dirty false --option eval-cache false --keep-going --max-jobs 16 print-dev-env
  │ --profile /home/shyim/Developer/sw6/.devenv/gc/shell` failed with with exit code 1

```

I think the general cli stuff should be compatible, only the real difference is the generated `.devenv.flake.nix`.  It would be nice if we could add a compatibility layer. The easiest hack would be to run `devenv update devenv` to update the input does not match.

**Comment by domenkozar** [comment]
Let me try to find a way :)

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/pull/1023

**Comment by domenkozar** [comment]
Fixed https://github.com/cachix/devenv/pull/1023, will release 1.0.1 shortly.

**Comment by shyim** [comment]
tested works flawlessly. thank you!
