### ISSUE TITLE
devenv update does not help

### ISSUE THREAD

**Issue by normanjaeckel** [cachix/devenv#1042]
**Describe the bug**

I get the message ```✨ devenv 1.0.1 is newer than devenv input in devenv.lock. Run `devenv update` to sync.``` but `devenv update` does not help to fix it. Even `rm devenv.lock` does not help. The file is created without any changes.

**To reproduce**

Just use the defaults from `devenv init`

https://gist.github.com/normanjaeckel/2d16e8626f5e08cd95e3fa45cb3c357e

```bash
$ devenv update
• Updating devenv.lock ...
✔ Updating devenv.lock in 2.1s.
```

```bash
$ devenv test
• Overriding .devenv to .devenv.OK4xhFG1usQm
• Building tests ...
• Using Cachix: devenv
✔ Building tests in 1.7s.
• Running tests ...
• Building shell ...
✔ Building shell in 2.1s.
✨ devenv 1.0.1 is newer than devenv input in devenv.lock. Run `devenv update` to sync.
hello from devenv
git version 2.43.2
• Setting up shell environment ...
✨ devenv 1.0.1 is newer than devenv input in devenv.lock. Run `devenv update` to sync.
hello from devenv
git version 2.43.2
• Testing ...
✔ Running tests in 2.9s.
• Tests passed :)
```

Make sure to include full logs and what you expected to happen.

**Version**
 
devenv 1.0.1 (x86_64-linux)

**Comment by domenkozar** [comment]
Should be fixed now, can you try again?

**Comment by normanjaeckel** [comment]
Fixed. Thank you very much.

**Comment by davidpfarrell** [comment]
@domenkozar wrote:

> Should be fixed now, can you try again?

Could you link the PR / commit that supposedly fixed this?

I'm getting this exact error using `1.0.5` and its driving me crazy - Thanks!

**Comment by davidpfarrell** [comment]
@domenkozar I believe the issue I'm seeing is that `src/modules/latest-version` still points to v1.0.4
* https://github.com/cachix/devenv/blob/main/src/modules/latest-version

**Comment by flaw** [comment]
@domenkozar I think this is happening again with `1.2.0`, `latest-version` still says to `1.1.0`

```❯ 
nix --version
nix (Nix) 2.24.8
❯ devenv version
devenv 1.2.0 (aarch64-darwin)
❯ devenv update
• Updating devenv.lock ...
✔ Updating devenv.lock in 2.5s.
❯ direnv reload
• Using Cachix: nixpkgs-python, devenv
warning: Performing inefficient double copy of path '«github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/' to the store. This can typically be avoided by rewriting an attribute like `src = ./.` to `src = builtins.path { path = ./.; name = "source"; }`.
hashing '«github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/'direnv: ([/opt/homebrew/bin/direnv export fish]) is taking a while to execute. Use CTRL-C to give up.
💡 The dotenv file '.env' was not found.
Running tasks     devenv:enterShell
Succeeded         devenv:python:virtualenv 29ms
Succeeded         devenv:enterShell        7ms
2 Succeeded                                104.46ms

✨ devenv 1.2.0 is newer than devenv input in devenv.lock. Run `devenv update` to sync.
🦾 Welcome to the development environment!
```

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/issues/294183
