### ISSUE TITLE
Package not available from Nixpkgs.

### ISSUE THREAD

**Issue by georgealexanderday** [cachix/devenv#1044]
It is noted on the installation instructions that devenv can be installed as a regular package as so:

```
environment.systemPackages = [ 
  pkgs.devenv
];
```

However I don't think it's available yet? 

Let me know if I'm mistaken or what I need to do?

**Comment by brizzbuzz** [comment]
was just about to file a ticket about this, having the same issue, wondering if perhaps it's available only on master/latest channel? my current flake setup supports 23.11 and unstable, I'd rather not set up master channel as well :/

**Comment by brizzbuzz** [comment]
yea just confirmed that if you add master nixpkgs as an input, you can add devenv through that package set

**Comment by brizzbuzz** [comment]
https://github.com/brizzbuzz/bigbang/commit/3ec3867f18f627ddc48624658d06c585cbd43e89

ignore all the other changes in `dev.nix` that was just me doing some other cleanup :)

**Comment by georgealexanderday** [comment]
yep you are right, thanks for that! I'm happy to wait for it in unstable I was just wondering.

**Comment by georgealexanderday** [comment]
It's now available on unstable so will close this issue.
