### ISSUE TITLE
devenv init should work if there is an existing git ignore

### ISSUE THREAD

**Issue by brizzbuzz** [cachix/devenv#1046]
hey :wave: 

been tinkering around w/ devenv a bit, and i think it would be nice if I could initialize devenv in an existing repo using devenv init, while a gitignore already exists.  at the moment, if I run `devenv init` in an existing repo w/ a gitignore, I get this error 

```
 devenv init                                                                                                                            03/24/24 09:41:04 AM
Error:   × File already exists /home/ryan/Workspace/brizzbuzz/scroll/.gitignore
```

Can't it either just append the required ignores or even better search and add if missing?

**Comment by domenkozar** [comment]
Fixed for next release.
