### ISSUE TITLE
--no-locale might not be an optimal Postgres option to set

### ISSUE THREAD

**Issue by jozuas** [cachix/devenv#107]
[`default = [ "--no-locale" ];`](https://github.com/cachix/devenv/blob/280f550e328364c39e02ec4bd5d626ec68ff46c8/src/modules/postgres.nix#L50)

`--no-locale` sets locale to C and DB encoding to `SQL_ASCII`.

[From Postgres docs](https://www.postgresql.org/docs/current/multibyte.html):
> The SQL_ASCII setting behaves considerably differently from the other settings. When the server character set is SQL_ASCII, the server interprets byte values 0–127 according to the ASCII standard, while byte values 128–255 are taken as uninterpreted characters. No encoding conversion will be done when the setting is SQL_ASCII. Thus, this setting is not so much a declaration that a specific encoding is in use, as a declaration of ignorance about the encoding. In most cases, if you are working with any non-ASCII data, it is unwise to use the SQL_ASCII setting because PostgreSQL will be unable to help you by converting or validating non-ASCII characters.

**Comment by domenkozar** [comment]
How about UTF8?

**Comment by jozuas** [comment]
Here's a [fun read ](https://gist.github.com/rraval/ef4e4bdc63e68fe3e83c9f98f56af7a4) on locales in PostgreSQL. Given the information in this article and the comments, it seems to me that `[ "--locale=C" "--encoding=UTF8" ]` would be the safest option with a bit of added documentation to `initdbArgs` to prevent people shooting themselves in the foot.

**Comment by domenkozar** [comment]
@jozuas would you make a PR :pray:

**Comment by jozuas** [comment]
No probs, I'll schedule for tomorrow.

**Comment by domenkozar** [comment]
@jozuas do you plan to make a PR?
