### ISSUE TITLE
languages.pnpm installs packages with npm

### ISSUE THREAD

**Issue by jcf** [cachix/devenv#1072]
**Describe the bug**

Enabling `languages.javascript.pnpm.install` executes a script that references `npm`.

https://github.com/cachix/devenv/blob/ad5a82f493f016bf4e82fae481b374d943be9560/src/modules/languages/javascript.nix#L42-L59

**To reproduce**

Enable the aforementioned option and fire up `devenv`.

**Version**
 
The version of devenv shouldn't come into it — this comes from the Nix module in the `main` branch.

**Comment by jcf** [comment]
If it's safe to substitute out `npm` with `pnpm`, I can open a PR later today.

**Comment by domenkozar** [comment]
cc @totoroot

**Comment by totoroot** [comment]
@jcf, thanks for reporting!
Sorry, that was indeed a mistake I made. Either a rebase went wrong or I simply forgot to change it after copy-pasting the script section.
I can open a PR to address this this afternoon :)

**Comment by jcf** [comment]
Thank you for the PR, @totoroot, and thank you for the merge, @domenkozar!
