### ISSUE TITLE
Overmind puts .overmind.sock into root dir instead of .devenv/state

### ISSUE THREAD

**Issue by M-arcus** [cachix/devenv#1073]
**Describe the bug**
Overmind puts .overmind.sock into root dir instead of .devenv/state when having `process.implementation = "overmind";` configured

**To reproduce**
```
{ pkgs, ... }:
{
  processes.entryscript.exec = ''
    ${pkgs.coreutils}/bin/sleep infinity
  '';
  process.implementation = "overmind";
}
```

![image](https://github.com/cachix/devenv/assets/25648755/555cd0c3-5b70-4c35-826c-3d9fdd31c61a)

**Version**
```
 $ devenv version
devenv 1.0.2 (x86_64-linux)
```

**Comment by domenkozar** [comment]
It should really got into `DEVENV_RUNTIME`. Could you make a PR?
