### ISSUE TITLE
Move nix caching from direnv plugin to devenv cli

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#1079]
Right now we have caching inside `direnv` to make folder switching instant. It would be nice if we could move the caching into devenv generally, so that `devenv shell` and `devenv up` also improves.

**Comment by domenkozar** [comment]
That's done: https://devenv.sh/blog/2024/10/03/devenv-13-instant-developer-environments-with-nix-caching/

**Comment by sandydoo** [comment]
Minus `nix develop`, but we'll improve on this.
