### ISSUE TITLE
Gleam does not work out of the box.

### ISSUE THREAD

**Issue by abeljim** [cachix/devenv#1086]
**Describe the bug**
Gleam test is not working out of the box,

**To reproduce**
Used devenv init to create a environment. languages.gleam.enable = true; Use 'gleam init test_ project' to create a project.  Cd in and use the 'gleam test' command for the result below. Adding the erlang package resolves this.

❯ gleam test
  Resolving versions
Downloading packages
 Downloaded 2 packages in 0.01s
  Compiling gleam_stdlib
error: Program not found

The program `escript` was not found. Is it installed?
Documentation for installing Erlang can be viewed here:
https://gleam.run/getting-started/installing/

**Version**
 devenv 1.0.1 (x86_64-linux)

Running on Nixos.

**Comment by domenkozar** [comment]
cc @vic

**Comment by domenkozar** [comment]
Could you contribute a test to `examples/gleam`?

**Comment by abeljim** [comment]
#1087 Created Pull Request

**Comment by hqm42** [comment]
To make it work right now, you need to add `erlang` and `rebar3` to your devenv.nix: https://gleam.run/getting-started/installing/

```
{ pkgs, ... }:

{
  packages = [ pkgs.rebar3 ];
  languages.erlang.enable = true;
  languages.gleam.enable = true;
}
```

**Comment by domenkozar** [comment]
Should `rebar3` be part of erlang and gleam should also enable erlang?

**Comment by hqm42** [comment]
Sounds good to me. Could be configured via something like `languages.erlang.rebar3.enable` with true as default. Erlang package could be overridden via the existing `languages.erlang.package`
