### ISSUE TITLE
How does devenv.yaml:allowUnfree and NIXPKGS_ALLOW_UNFREE work with nonfree packages?

### ISSUE THREAD

**Issue by SebastianCallh** [cachix/devenv#1117]
Hi! Thank you for devenv, it is such a cool piece of software. 

I have successfully used it with free languages, but I run into trouble when using terraform (adding it as a language in devenv.nix) due to their bsl license.

Upon entering the shell (with direnv) I am greeted with the classic "refused to evaluate due to license" Nix message. To address this I have tried to set `allowUnfree = true` in devenv.yaml, and `NIXPKGS_ALLOW_UNFREE=1` in my environment, but Nix still refuses to resolve. 

It is my understanding that devenv might not run in `--impure` mode, which would explain why NIXPKGS_ALLOW_UNFREE does nothing, but since allowUnfree also doe nothing I am at a loss on how to proceed here and would greatly appreciate if you could shine some light on this.

**Comment by domenkozar** [comment]
Duplicates https://github.com/cachix/devenv/issues/1090
