### ISSUE TITLE
syntax error, unexpected '!', expecting ';' when using example in the 'common patterns' page

### ISSUE THREAD

**Issue by SebastianCallh** [cachix/devenv#1123]
**Describe the bug**
Using the [How to exclude packages from the container example](https://devenv.sh/common-patterns/#how-to-exclude-packages-from-the-container) in a newly generated project (using `devenv init`) causes "syntax error, unexpected '!', expecting ';'" when entering `devenv shell`. I was expecting the code example to successfully run and to be dropped in a shell with git and (in this example) the Haskell language server available.

**To reproduce**
Download [this](https://gist.github.com/SebastianCallh/fa98b00ea3f7a88de0183e7d78acfd74) gist, unzip, cd into the folder and run `devenv shell`. The stack trace it also in the gist.

**Version**
 devenv 1.0.2 (aarch64-darwin)

**Comment by sandydoo** [comment]
Thanks!
