### ISSUE TITLE
fresh install: "✨ devenv 1.0.3 is out of date"

### ISSUE THREAD

**Issue by mx00s** [cachix/devenv#1127]
I tried running the [Getting Started directions](https://devenv.sh/getting-started/) and ran into a confusing message:

```shell
> sh <(curl -L https://nixos.org/nix/install) --no-daemon  # for WSL2 (Windows)
> nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
> git init demo && cd demo
> devenv init
> devenv test
...
✨ devenv 1.0.3 is out of date. Please update to 1.0.4: https://devenv.sh/getting-started/#installation
...
```

The update directions linked by the message are the exact ones I just followed to install devenv, so it's odd that it claims it's outdated.

According to https://github.com/NixOS/nixpkgs/blob/a0c9e3aee1000ac2bfb0e5b98c94c946a5d180a9/pkgs/by-name/de/devenv/package.nix#L32, the current version on `nixpkgs-unstable` is 1.0.3, the one I have.

This repository's releases show the more recent [1.0.4](https://github.com/cachix/devenv/releases/tag/v1.0.4) is the latest as of ~16 hours ago. Apparently the `nixpkgs-unstable` just hasn't been updated yet.

To mitigate future user confusion, would it be worth ...?

1. changing the install directions to depend directly on this repo's releases instead,
2. using the latest version from the chosen installation source as the source of truth, and/or
3. minimizing the duration between releases in this repo and bumping the version in `nixpkgs-unstable`

**Comment by domenkozar** [comment]
Hey @mx00s, nice to see you around here :wave: 

The easiest to do right now is to bump `.latest-version` once nixpkgs-unstable hits, we could even automate this.

Thanks for bringing this up!

**Comment by aimestereo** [comment]
@domenkozar same now: 1.0.8 in `nixpkgs-unstable` vs 1.1 in github repo

```
❯ devenv shell
• Building shell ...
• Using Cachix: devenv
✔ Building shell in 113.2s.
• Entering shell
✨ devenv 1.0.8 is out of date. Please update to 1.1: https://devenv.sh/getting-started/#installation
```

I am new in Nix, so I'm afraid to make any manual changes/updates - I will receive new version from `nixpkgs-unstable` when it's there/ready.
For me it would be great if I could disable this check/warning, but it seems impossible, right?

**Comment by domenkozar** [comment]
@aimestereo we've released 1.1 when it hit nixpkgs-unstable

**Comment by aimestereo** [comment]
@domenkozar wow, maybe I'm checking it wrong, I use 

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=devenv

<img width="897" alt="Screenshot 2024-09-12 at 21 14 44" src="https://github.com/user-attachments/assets/6649eb42-1de0-4930-8075-fd78c1a21d26">


<img width="924" alt="Screenshot 2024-09-12 at 21 14 38" src="https://github.com/user-attachments/assets/4b426b58-0fa8-450e-bf7d-bb52d778e21f">

**Comment by domenkozar** [comment]
@aimestereo that's nixos-unstable, not nixpkgs-unstable.

**Comment by aimestereo** [comment]
@domenkozar 🤦 thanks! solved my issue!
