### ISSUE TITLE
Contributing to devenv

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#113]
- [ ] [basic setup](https://dev.to/bcardiff/contributing-to-devenv-50ag)
- [ ] contributing a new language

**Comment by rkrzr** [comment]
It would be great if we can add some docs on how to contribute to devenv. I would like to contribute a PR but I'm struggling to set up the devenv for devenv ;)

Some of the problems I ran into:

1. I cloned devenv and got an error from direnv when `cd`ing into the directory `./.envrc:5: ./result/bin/devenv: No such file or directory`. I guess this directory is created after the first build, but I don't know the build command.
2. `devenv shell` works, but tells me to create a Python virtualenv and to install the requirements in `requirements.txt`. I was surprised by this dependency on virtualenv. Wouldn't it be possible to get these deps from Nix instead?
3. Running `devenv up` fails, even after entering a `devenv shell` and installing the Python dependencies with `OSError: no library called "cairo-2" was found`. I have the `libcairo2` Ubuntu package installed, but again I would have expected to get the deps from Nix instead.
