### ISSUE TITLE
devenv up -d (detach) argument does not work

### ISSUE THREAD

**Issue by noverby** [cachix/devenv#1159]
According to https://devenv.sh/services, `devenv up` support detaching with the `-d` argument,
but the argument does nothing, and it is not documented either with `--help`, that it is an available option.

**Comment by domenkozar** [comment]
Are you using flakes?

```
❯ devenv up --help
Start processes in the foreground. https://devenv.sh/processes/

Usage: devenv up [OPTIONS] [PROCESS]

Arguments:
  [PROCESS]  Start a specific process.

Options:
  -d, --detach  Start processes in the background.
  -h, --help    Print help
```

**Comment by noverby** [comment]
Oh, just noticed that we are using the workaround provided by https://github.com/cachix/devenv/issues/756, but with that workaround, it does not support `--detach`:

```nix      
packages.devenv-up = {stdenv}: self.devShells.${stdenv.system}.default.config.procfileScript;
```

**Comment by domenkozar** [comment]
Yeah if you'd like to use `-d` you have to use `devenv` cli.

**Comment by noverby** [comment]
For ref: process-compose issue to add support for `--detach` argument: https://github.com/F1bonacc1/process-compose/issues/169

**Comment by bachirelkhoury** [comment]
Is there any way to launch process-compose and mange services after launching with -d?
