### ISSUE TITLE
How did adding the devenv package make my system start to trust devenv.cachix.org

### ISSUE THREAD

**Issue by idrisr** [cachix/devenv#1168]
Hello, I'm trying devenv for the first time to integrate some git-hooks into to my flake-based project. On my nixos machine, I added devenv to `environment.systemPackages` and then ran `devenv init`, per the instructions on the setup page.

My question is about the final line from the stdout from `devenv init`, which I've pasted blow. How did my system start to trust `devenv.cachix.org` as a substituter / binary cache?  My prior understanding was that I would need to explicitly add additional trusted nix binary caches in my config under `nix.settings.trusted-substituters` and `nix.trusted-public-keys` to start using a new cache. I didn't add any trusted-substituters or binary-caches to my config, so I'm quite surprised to see that devenv is using `devenv.cachix.org`.

```
➜ devenv init
• Creating devenv.nix
• Creating devenv.yaml
• Creating .envrc
• Creating .gitignore
direnv: loading ~/fun/visual-preview/.envrc
direnv: loading https://raw.githubusercontent.com/cachix/devenv/95f329d49a8a5289d31e0982652f7058a189bfca/direnvrc (sha256-d+8cBpDfDBj41inrADaJt+bDWhOktwslgoP5YiGJ1v0=)
direnv: using devenv
direnv: .envrc changed, reloading
direnv: ([/nix/store/h960xs3n0qh0809620kp9955sh56rgp1-direnv-2.34.0/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
• Using Cachix: devenv
• Trusting devenv.cachix.org on first use with the public key devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
direnv: updated devenv shell cache
```

**Comment by sandydoo** [comment]
If you're a trusted user, then devenv will add the `--extra-substituters` and `--extra-trusted-public-keys` CLI arguments to its internal nix commands.

If you're not a trusted users, then you'll be provided with instructions on how to add the substituter manually.
