### ISSUE TITLE
`devenv gc` broken on MacOS ?

### ISSUE THREAD

**Issue by gotcha** [cachix/devenv#118]
When running `devenv gc`, I get the following error and output:
```
Counting old devenvs ...

error: flake 'path:/Users/gotcha/tmp/bad-devenv-gc' does not provide attribute 'packages.x86_64-darwin.default' or 'defaultPackage.x86_64-darwin'
/Users/gotcha/.nix-profile/bin/devenv: line 160: / 1024 / 1024 : syntax error: operand expected (error token is "/ 1024 / 1024 ")```

**Comment by domenkozar** [comment]
What are the steps to reproduce this?

**Comment by gotcha** [comment]
I installed `devenv` via
```
nix profile install nixpkgs#cachix
cachix use devenv
nix profile install github:cachix/devenv/v0.3
``` 

Steps to reproduce:
- `$ devenv init`
- activation via `direnv`
- `$ devenv gc`

**Comment by domenkozar** [comment]
@sandydoo could you test this?

**Comment by domenkozar** [comment]
Do you have M1 macos?

**Comment by gotcha** [comment]
> Do you have M1 macos?

Nope

**Comment by gotcha** [comment]
> Can you paste `/etc/nix/nix.conf`?

```
build-users-group = nixbld
trusted-users = root gotcha
```

**Comment by gotcha** [comment]
I updated to 0.4 and get the very similar error:
```
✦2 ❯ devenv gc
Counting old devenvs ...

error: flake 'path:/Users/gotcha/tmp/test-devenv-0.4' does not provide attribute 'packages.x86_64-darwin.default' or 'defaultPackage.x86_64-darwin'
/Users/gotcha/.nix-profile/bin/devenv: line 156: / 1024 / 1024 : syntax error: operand expected (error token is "/ 1024 / 1024 ")
```

**Comment by shyim** [comment]
Works on my m1. It's an x86 issue or something with your used devenv.nix

**Comment by domenkozar** [comment]
Could you try using the latest main branch?

https://github.com/cachix/devenv/commit/93b562bd8706d1d5bb330c25be7ca780ddadbb8c might have fixed it.

**Comment by gotcha** [comment]
@domenkozar Happy to test it. But I have no idea how to use the main branch ?

**Comment by domenkozar** [comment]
`nix profile install github:cachix/devenv/main`

**Comment by gotcha** [comment]
Not solved. This is what I did:
```
$ nix profile install github:cachix/devenv/main
$ mkdir bla
$ cd bla
$ devenv init
$ devenv gc
```

**Comment by domenkozar** [comment]
Had a call with @gotcha and it seems to be resolved, if it comes back let me know.
