### ISSUE TITLE
Rust Compilation Failure on macOS: Linker Error with Missing Directories and Frameworks 

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [cachix/devenv#1192]
**Describe the bug**
When setting up devenv on macOS with an M1 chip and trying to compile a simple Rust project using cargo run, the compilation fails during the linking stage. The linker reports missing directories and frameworks, specifically not finding -F/nix/store/xz2xij86qkgsh02db64yazdahlf0zr59-devenv-profile/Library/Frameworks and the SystemConfiguration framework. This results in a clang-16 linker command failure.
When doing 
```bash
❯ ls $(echo $DEVENV_PROFILE)
bin  include  lib  setup  share
```
there is also no Library/Frameworks folder

**To reproduce**
1. Setup devenv on macOS (M1).
2. Attempt to compile a simple Rust project using cargo run.
3. Observe the error during the linking stage.

- [flake.nix](https://gist.github.com/GeorgesAlkhouri/8e7a65d7228b63dd6091822c648912a4)

```bash
= note: ld: warning: directory not found for option '-F/nix/store/xz2xij86qkgsh02db64yazdahlf0zr59-devenv-profile/Library/Frameworks'
ld: framework not found SystemConfiguration
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Version**

 devenv: 1.0.5

**Comment by sandydoo** [comment]
@GeorgesAlkhouri, could you please post a sample rust package that exhibits the error? 
Tried the above flake after a `cargo init` — no issues. 

macOS m1
devenv 1.0.5

**Comment by sandydoo** [comment]
Make sure to run a `nix flake update` as well.

**Comment by sandydoo** [comment]
Regarding `SystemConfiguration`, you need to add any necessary frameworks to `packages`:

```nix
{
  packages = [ pkgs.darwin.apple_sdk.frameworks.SystemConfiguration ];
}
```

**Comment by GeorgesAlkhouri** [comment]
> Regarding SystemConfiguration, you need to add any necessary frameworks to packages:
{
  packages = [ pkgs.darwin.apple_sdk.frameworks.SystemConfiguration ];
}

this did solved the problem for me, didn't know about that thanks a lot.

**Comment by sandydoo** [comment]
Yeah, we could use a section in the docs that explains this part.

**Comment by danielhep** [comment]
I just ran into this many months later, it seems that it was never added to the docs. If devenv is going to be an easier to use abstraction to nix, then it needs to not have the same poor-documentation issue that Nix has.

**Comment by sandydoo** [comment]
Thanks for the reminder, @danielhep. I added an [example](https://devenv.sh/common-patterns/#link-against-macos-system-frameworks) to the docs.
