### ISSUE TITLE
New examples

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#12]
Please, comment with what kind of an example you'd like to see.

**Comment by paultiplady** [comment]
Would be great to see an example (if it's possible) of how to wire up Python with specific packages; something equivalent to 

```
pkgs.python3.withPackages (p: with p; [
  django
])
```

From https://nixos.wiki/wiki/Python.

The most complete devenv.nix I've found is  https://github.com/cachix/devenv/blob/4787a79b00c5415139c2ae7029c8d870eea831e6/devenv.nix which doesn't have this wired up.

**Comment by sacsar** [comment]
I'm currently trying to figure out how to use `niv` and `devenv` together (since the `nix` docs point you to both). I'm honestly not sure if this is a missing example or if the answer is "don't do that".

**Comment by domenkozar** [comment]
> Would be great to see an example (if it's possible) of how to wire up Python with specific packages; something equivalent to
> 
> ```
> pkgs.python3.withPackages (p: with p; [
>   django
> ])
> ```
> 
> From https://nixos.wiki/wiki/Python.
> 
> The most complete devenv.nix I've found is https://github.com/cachix/devenv/blob/4787a79b00c5415139c2ae7029c8d870eea831e6/devenv.nix which doesn't have this wired up.

That's something I've been thinking quite a bit in the last days. There are different levels of language support and I still need to do a bit of experimentation. Regardless, this will be supported!

**Comment by domenkozar** [comment]
> I'm currently trying to figure out how to use `niv` and `devenv` together (since the `nix` docs point you to both). I'm honestly not sure if this is a missing example or if the answer is "don't do that".

You don't need niv since you can use https://devenv.sh/inputs/

**Comment by paultiplady** [comment]
> There are different levels of language support and I still need to do a bit of experimentation.

Worth noting that in practice, for applications `withPackages` isn't that useful since it doesn't have all the packages, and I'll probably end up using something like https://github.com/nix-community/poetry2nix.

**Comment by ostrolucky** [comment]
I'm a PHP developer. I noticed there is a PHP-FPM service which is nice, but I'm wondering how to use it together with web server. Usual combination is NGINX + PHP-FPM, but looks like you don't provide nginx service? What's the recommended approach to use a php-fpm then, what to connect it to? Hence would be nice to provide example for HTTP server that connects to FPM.

**Comment by sonn-gamm** [comment]
+1 for Nginx support / setup.

**Comment by domenkozar** [comment]
I think @shyim mentioned recently to add nginx service

**Comment by shyim** [comment]
Are you sure with file uploading? Never head problems with that

**Comment by shyim** [comment]
If you have a reproducer repo I would like to debug it and fix it :)

**Comment by domenkozar** [comment]
There's now nginx at https://devenv.sh/reference/options/#servicesnginxenable

**Comment by frontsideair** [comment]
It would be really nice to have a Node.js/Postgres full-stack example. I tried to build one a few weeks ago but didn't work out smoothly. I think one of the reasons might be that I was using Prisma as my ORM, which may require some tweaking with socket files.

**Comment by domenkozar** [comment]
@frontsideair is there a getting started repo that devenv should work with?

**Comment by frontsideair** [comment]
This [Remix](https://github.com/remix-run/blues-stack) template is a good candidate I think, it has a docker compose file and should work with minimal changes.

**Comment by domenkozar** [comment]
Best to open a separate issue for each.
