### ISSUE TITLE
Process Compose ready_log_line not usable

### ISSUE THREAD

**Issue by euphemism** [cachix/devenv#1206]
**Describe the bug**
Attempting to pass along `ready_log_line` to Process Compose via devenv fails with the following:

```
FTL Failed to load project error="unknown key 'ready_log_line' found in process 'start'"
```

[Process Compose docs on the feature](https://f1bonacc1.github.io/process-compose/launcher/?h=ready_log#process-log-ready-example).

**To reproduce**

`devenv.nix`:
```nix
{ ... }:

{
  processes.start = {
    exec = "echo start";

    process-compose.ready_log_line = "start";
  };
}
```

**Version**
 
`devenv 1.0.5 (aarch64-darwin)`

**Comment by euphemism** [comment]
Is this just user error?

**Comment by sandydoo** [comment]
@euphemism, [this feature was added 2 weeks ago](https://github.com/F1bonacc1/process-compose/commit/03dc542993b65fae15c1e63dd2557a7bd8feb26f). You can use a newer version from `nixpkgs-unstable` in the meantime.

**Comment by euphemism** [comment]
Ah, okay. Thank you.
