### ISSUE TITLE
NixOS download on every startup

### ISSUE THREAD

**Issue by yanneckb** [cachix/devenv#1250]
Hello,
we have some shopware projects running with devenv. Everytime I start the project and the shell is builded with `devenv up` or `devenv shell` it downloads the nixOS Package and it takes veeery long
`[2.0/40.9 MiB DL] downloading 'https://github.com/NixOS/nixpkgs/archive/4a4ecb0ab415c9fccfb005567a215e6a9564cdf5.tar.gz'`
I've followed the setup instructions from shopware (https://developer.shopware.com/docs/guides/installation/devenv.html#devenv)
Does anyone have an idea why devenv is downloading the package every time and why the download is so slow?

Greetings
Yanneck

**Comment by shyim** [comment]
Why it is slow is related to https://github.com/NixOS/nix/issues/10683, feel free to add a like there.

**Comment by yamin-oanda** [comment]
I am seeing this as well:

```
$ devenv shell
• Building shell ...
• Using Cachix: nixpkgs-python, devenv
✔ Building shell in 6.3s.
• Entering shell
[9.7/42.1 MiB DL] downloading 'https://github.com/NixOS/nixpkgs/archive/a14c5d651cee9ed70f9cd9e83f323f1e531002db.tar.gz'
```

It seems to be redownloading this archive periodically even without making any changes to the devenv config. Could it be cached in the `/tmp` directory which is erased daily on macOS (eg)?

**Comment by hasrthur** [comment]
> Why it is slow is related to [NixOS/nix#10683](https://github.com/NixOS/nix/issues/10683), feel free to add a like there.

I guess the question is more "why should we download anything if we already have lock file generated and all the required packages installed". The slowness of download is a side-effect since it shouldn't happen at all, at least from my perspective
