### ISSUE TITLE
Set settings for vscode.

### ISSUE THREAD

**Issue by SolidRhino** [cachix/devenv#1257]
The Devcontainer specifications allow to add the visual studio code settings via the **settings** option in de devcontainer.json:
```json
"customizations": {
  "vscode": {
    "settings": {},
    "extensions": [],
  }
}
```
Is it posible to add this to devenv?

**Comment by shyim** [comment]
It's a free form type, so you should be able to just set it 🤔 

```
devcontainer.settings.customizations.vscode = {
   settings = {
   };
   extensions = {
   };
};
```

**Comment by SolidRhino** [comment]
It is indead possible! Maybe it is a good idee to add this to the documentation?
