### ISSUE TITLE
Newbie question: How to install devenv for my nixos config

### ISSUE THREAD

**Issue by pogopaule** [cachix/devenv#126]
I am newbie struggling to add devenv to my [existing config](https://github.com/pogopaule/dotfiles/blob/master/flake.nix). I [tried to](https://github.com/pogopaule/dotfiles/commit/7ed7a51138ca9da092771ec74c43ae287a244b01) follow [this install option](https://devenv.sh/getting-started/#__tabbed_3_4), but did not succeed.

Any tips, hints, etc?

**Comment by domenkozar** [comment]
Try referencing it as `devenv.packages.x86_64-linux.devenv`.

**Comment by pogopaule** [comment]
That did the job, thank you for your quick response!
