### ISSUE TITLE
devenv configuration for go-pre-commit

### ISSUE THREAD

**Issue by jdpedrie** [cachix/devenv#127]
My first time using nix or devenv.

I'm trying to migrate our old git pre-commit hook, which uses https://github.com/lietu/go-pre-commit. Having trouble getting the configuration working as expected.

```
pre-commit.hooks = {
  staticcheck.enable = true;
};
```

Results in `The option `pre-commit.hooks.staticcheck.entry' is used but not defined.`

```
  staticcheck.enable = true;
  staticcheck.entry = "go-pre-commit errcheck";
```

This compiles, but it seems to me I'd end up with only one of the defined checks.

I'd like to run them all.

Thanks for the help.

**Comment by domenkozar** [comment]
I'll try to add some documentation how to define custom hooks

**Comment by giodamelio** [comment]
I don't have time to contribute proper docs right now, but I will add this for anyone that finds this issue.

I was able to add a pre commit hook for Credo (an Elixir static analyzer). Here is the complete `devenv.nix` as an example.

```
{ pkgs, ... }:

{
  packages = [ pkgs.elixir_1_14 ];

  enterShell = ''
    export MIX_HOME="$PWD/.mix/"
    just --list
  '';

  languages.nix.enable = true;
  languages.elixir.enable = true;

  pre-commit.hooks = {
    credo = {
      enable = true;
      name = "Credo";
      entry = "mix credo";
      pass_filenames = false;
    };
  };
}
```

The object follows the spec described [here in the cachix/pre-commit-hooks.nix docs](https://github.com/cachix/pre-commit-hooks.nix/tree/master#custom-hooks).

**Comment by domenkozar** [comment]
I've added docs here how to add custom hooks: https://devenv.sh/pre-commit-hooks/#adding-custom-hooks
