### ISSUE TITLE
Turn off process compose

### ISSUE THREAD

**Issue by mrshmllow** [cachix/devenv#1272]
I find it hard to use and unergonomic. How do I turn it off?

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/blob/main/examples/overmind/devenv.nix

**Comment by thenonameguy** [comment]
@mrshmllow could you please also describe what you find hard to use and unergonomic about it?
Just so we can improve it :)

**Comment by mrshmllow** [comment]
> https://github.com/cachix/devenv/blob/main/examples/overmind/devenv.nix

Thank you

**Comment by mrshmllow** [comment]
> @mrshmllow could you please also describe what you find hard to use and unergonomic about it?
> Just so we can improve it :)

I am normally running a single process, and in that case it feels redundant and I just want to view the logs uninterrupted, without losing any escape code highlighting.

I like to use my terminal's keyboard scrolling which doesn't work with the log view and I have to use my scroll wheel which jumps in bigger steps than normal, and due to the UI taking up more space, it feels like I'm always missing logs 

The (often single) task loses focus all the time, for a while I had no idea and it led me to believe the task simply was broken for like 2 days

It's very nitpicky and I'm annoying for saying this but the "quit?" prompt doesn't support hjkl

I'm sure it's way better for projects where your running a load of services! I love devenv and recommend it to everyone because overall it's a very user friendly experience ♥️♥️

**Comment by thenonameguy** [comment]
Thanks a lot for taking the time to write this down! 

For your case running it [without a TUI](https://f1bonacc1.github.io/process-compose/tui/) would make more sense. That would make it more in-line with overmind/etc. behavior of just piping the process logs to STDOUT, solving the scrolling/focus issues.

I agree it's not the best fit for single process projects without that.

I'll open a ticket for your prompt navigation suggestion upstream. I think it makes total sense :)

Much appreciated 🙏
