### ISSUE TITLE
How to accept a license?

### ISSUE THREAD

**Issue by abelREK** [cachix/devenv#1274]
How do I accept the license I am getting the following error. I trying to install nrf-command-line-tools.   
I also added "segger-jlink-qt4-794l" to permittedInsecurePackages.
```
      error: Use of the "SEGGER JLink Software and Documentation pack" requires the
       acceptance of the following licenses:

         - SEGGER Downloads Terms of Use [1]
         - SEGGER Software Licensing [2]

       You can express acceptance by setting acceptLicense to true in your
       configuration. Note that this is not a free license so it requires allowing
       unfree licenses as well.

       configuration.nix:
         nixpkgs.config.allowUnfree = true;
         nixpkgs.config.segger-jlink.acceptLicense = true;

       config.nix:
         allowUnfree = true;
         segger-jlink.acceptLicense = true;

       [1]: https://www.segger.com/downloads/jlink/JLink_Linux_V794l_x86_64.tgz
       [2]: https://www.segger.com/purchase/licensing/
```

**Comment by sandydoo** [comment]
@abelREK, I don't think we have a way of setting this via config. But it looks like you can use an override instead:

```nix
pkgs.segger-jlink.override { acceptLicense = true; }
```

**Comment by abelREK** [comment]
I got the following error placing it in the packages array in devenv.nix
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'devenv-shell'
         whose name attribute is located at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'DEVENV_PROFILE' of derivation 'devenv-shell'

       … while evaluating derivation 'devenv-profile'
         whose name attribute is located at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'passAsFile' of derivation 'devenv-profile'
         at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/pkgs/build-support/trivial-builders/default.nix:69:9:
           68|         inherit buildCommand name;
           69|         passAsFile = [ "buildCommand" ]
             |         ^
           70|           ++ (derivationArgs.passAsFile or [ ]);

       … from call site
         at «github:cachix/devenv/24b3e5dd32e85ab6bd234ff3eed1fc3670bea583»/src/modules/top-level.nix:15:13:
           14|     name = "devenv-profile";
           15|     paths = lib.flatten (builtins.map drvOrPackageToPaths config.packages);
             |             ^
           16|     ignoreCollisions = true;

       … while calling 'flatten'
         at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/lib/lists.nix:383:13:
          382|   */
          383|   flatten = x:
             |             ^
          384|     if isList x

       … while calling anonymous lambda
         at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/lib/lists.nix:385:21:
          384|     if isList x
          385|     then concatMap (y: flatten y) x
             |                     ^
          386|     else [x];

       … from call site
         at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/lib/lists.nix:385:24:
          384|     if isList x
          385|     then concatMap (y: flatten y) x
             |                        ^
          386|     else [x];

       … while calling 'flatten'
         at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/lib/lists.nix:383:13:
          382|   */
          383|   flatten = x:
             |             ^
          384|     if isList x

       … while calling 'drvOrPackageToPaths'
         at «github:cachix/devenv/24b3e5dd32e85ab6bd234ff3eed1fc3670bea583»/src/modules/top-level.nix:8:25:
            7|
            8|   drvOrPackageToPaths = drvOrPackage:
             |                         ^
            9|     if drvOrPackage ? outputs then

       … from call site
         at «github:cachix/devenv/24b3e5dd32e85ab6bd234ff3eed1fc3670bea583»/src/modules/top-level.nix:9:8:
            8|   drvOrPackageToPaths = drvOrPackage:
            9|     if drvOrPackage ? outputs then
             |        ^
           10|       builtins.map (output: drvOrPackage.${output}) drvOrPackage.outputs

       … while calling anonymous lambda
         at «github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/lib/types.nix:547:14:
          546|       merge = loc: defs:
          547|         map (x: x.value) (filter (x: x ? value) (concatLists (imap1 (n: def:
             |              ^
          548|           imap1 (m: def':

       error:
       error: A definition for option `packages."[definition 2-entry 8]"' is not of type `package'. Definition values:
       - In `/nix/store/virtual0000000000000000000000006-source/devenv.nix': <function, args: {acceptLicense?, autoPatchelfHook, config, copyDesktopItems, fetchurl, fontconfig, lib, makeDesktopItem, stdenv, udev, xorg}>

✖ Command produced the following output:

**Comment by sandydoo** [comment]
Space is a delimiter in lists, so you need parentheses around this: `(pkgs.segger-jlink.override { acceptLicense = true; })`

**Comment by abelREK** [comment]
Thanks for all the help so far. This works for installing segger-jlink by itself, but it will still error out for nrf-command-line-tools. I tried to override for that package but it did not work.

**Comment by sandydoo** [comment]
Looking at the [source](https://github.com/NixOS/nixpkgs/blob/b60ebf54c15553b393d144357375ea956f89e9a9/pkgs/by-name/nr/nrf-command-line-tools/package.nix#L7C1-L7C15), the override should be:
```nix
pkgs.nrf-command-line-tools.override {
  segger-jlink = pkgs.segger-jlink.override { acceptLicense = true; };
});
```

**Comment by abelREK** [comment]
Got it working thanks so much 😄 
`
    (pkgs.nrf-command-line-tools.override {
        segger-jlink = pkgs.segger-jlink.override { acceptLicense = true; };
    })
`
