### ISSUE TITLE
devenv init: should generate the config all commented in

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#128]
I did run `devenv init` and direnv instantly picked up the generated `devenx.nix` and added some files like pre commit in my repository.

![image](https://user-images.githubusercontent.com/6224096/204133837-3cea8e04-9e65-49a1-96ad-2c2a735523e9.png)

So It would be nice to have default devenv where anything is commented in, so the repository is not changed

**Comment by domenkozar** [comment]
That makes sense, would you create a PR for it?
