### ISSUE TITLE
devenv init: auto adjust gitignore

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#129]
The `.devenv.flake.nix` and the `.devenv` folder should not be commited. When the user is running init we could directly adjust the gitignore and add those. I guess it's better DX

**Comment by domenkozar** [comment]
We do adjust `.gitignore`: https://github.com/cachix/devenv/blob/main/src/devenv.nix#L125

**Comment by shyim** [comment]
The problem for me was that the `.gitignore` didn't ended up with an empty line. So that it appended on the same line instead creating a new line. Maybe add a new line before? Like:

```bash

echo "" > .gitignore
echo "# Devenv" > .gitignore
echo stuff > .gitignore
