### ISSUE TITLE
"option android does not exist" when importing

### ISSUE THREAD

**Issue by clotodex** [cachix/devenv#1295]
**Describe the bug**
I have a devenv with the android option enabled - this works when executed directly.
But when I import this devenv and try to enter the shell it says "android option does not exist"

```
The option `android' does not exist. Definition values:
       - In `/nix/store/virtual0000000000000000000000006-source/frontend/devenv.nix':
```

**To reproduce**
import a devenv with android option enabled

**Version**
devenv 1.0.7 (x86_64-linux) - no flakes

**Comment by clotodex** [comment]
Soooo I did a system update (on nixos) and suddenly it works again.
I guess this was a nix bug? In any case devenv's version was not touched so this was a flake thing.
Feel free to close this - otherwise happy to investigate with the lock files and such.

**Comment by sandydoo** [comment]
> this works when executed directly.
> But when I import this devenv and try to enter the shell it says "android option does not exist"

Hard to say anything definitive without seeing your setup, but it sounds like you needed to run `devenv update`. Not sure how updating NixOS wouldn't fixed this.

**Comment by clotodex** [comment]
I devenv updated it a few times, also ran GC etc and nothing worked
When I updated my system, nix itself also updated so that might have had some interal bug or something
As I said, very weird. Cant reproduce it anymore. So I will close with this comment.
