### ISSUE TITLE
Enabling python produces error due to python 2.7 EOL insecurity

### ISSUE THREAD

**Issue by stroudcuster** [cachix/devenv#1297]
**Describe the bug**
Attempting to run devenv shell against a devenv.nix file containing languages.python.enable = true results in failed build with an error message reporting that python2.7 (required by cpython package) is insecure due to python 2.7 EOL.  Attempts to implement the solutions suggested in the error message did not correct the situation.
**To reproduce**
See attached files.  Run devenv shell against the attahced devenv..nix file
[devenv.nix.txt](https://github.com/user-attachments/files/15942106/devenv.nix.txt)
[python2.7-error..txt](https://github.com/user-attachments/files/15942107/python2.7-error.txt)

Make sure to include full logs and what you expected to happen.

**Version**
 devenv 1.0.5  nixos 24.05 running in visualbox 7
Paste the output of `$ devenv version` here or tell us if you're using flakes.

**Comment by sandydoo** [comment]
You should remove `pkgs.python` from `packages = [ pkgs.git pkgs.python ];`. The language integration will add the correct python interpreter.

The reason for the warning from Nix is that `pkgs.python` maps to `v2.*` versions of python.
