### ISSUE TITLE
Devenv installing older package version  of Gitea

### ISSUE THREAD

**Issue by bachirelkhoury** [cachix/devenv#1304]
**Describe the bug**
`devenv search gitea` is showing gitea version 1.22.0
However when starting the shell with `pkgs.gitea` version 1.21.10 is getting installed instead.

**To reproduce**

Init the dev environment:

```sh
$ mkdir test-devenv && cd $_
$ devenv init
```

```sh
$ devenv search gitea

# Output
| pkgs.gitea | 1.22.0  | Git with a cup of tea  |
```

Add `pkgs.gitea` to devenv.nix

```nix
{ pkgs, lib, config, inputs, ... }:

{
  # https://devenv.sh/basics/
  env.GREET = "devenv";

  # https://devenv.sh/packages/
  packages = [ pkgs.git pkgs.gitea ];

  # https://devenv.sh/scripts/
  scripts.hello.exec = "echo hello from $GREET";

  enterShell = ''
    hello
    git --version
  '';

  # https://devenv.sh/tests/
  enterTest = ''
    echo "Running tests"
    git --version | grep "2.42.0"
  '';
}
```

```sh
$ devenv shell
$ gitea --version
# Output
Gitea version 1.21.10 built with go1.22.1
```

**Version**
I tried on both macOS and Ubuntu same issue:

devenv 1.0.7 (aarch64-darwin)
devenv 1.0.7 (x86_64-linux)

**Comment by k3yss** [comment]
This is because of the `devenv-nixpkgs` that we provide, which seems to be slowing becoming outdated. You can try switching to unstable channel to get the latest version.

**Comment by bachirelkhoury** [comment]
Great thanks that worked... at the end we ended up switching to Forgejo.

**Comment by MalteMagnussen** [comment]
> This is because of the `devenv-nixpkgs` that we provide, which seems to be slowing becoming outdated. You can try switching to unstable channel to get the latest version.

@k3yss - What does that mean, and how do I switch?

**Comment by k3yss** [comment]
@MalteMagnussen I made a pr to include it in the documentation https://github.com/cachix/devenv/pull/1411

**Comment by MalteMagnussen** [comment]
@k3yss thanks man

switching fixed a lot of issues with outdated versions for us
