### ISSUE TITLE
Crash because of missing file

### ISSUE THREAD

**Issue by l0b0** [cachix/devenv#1311]
**Describe the bug**

After setting up a simple devenv and setting `CACHIX_AUTH_TOKEN`, `devenv test` fails with very little explanation.

**To reproduce**

[Gist](https://gist.github.com/l0b0/21f5f56c074b7a3d2732779dbfc7c1a7)

**Version**
 
devenv 1.0.7 (x86_64-linux)

Using flakes.

**Comment by sandydoo** [comment]
Thanks! Working on a fix.
