### ISSUE TITLE
Support for nix-direnv (or copy its mechanism)

### ISSUE THREAD

**Issue by andrewhamon** [cachix/devenv#133]
Hey there, loving the project so far!

Right now my only pain point (as compared to my previous setup using vanilla nix shell + [nix-direnv](https://github.com/nix-community/nix-direnv)) is the speed of opening new shells. Even though all the build artifacts are cached, it still takes several seconds to evaluate all the nix expressions and whatnot for a simple devenv that pulls in node and yarn.

I'm pretty sure nix-direnv solves this by caching the values of all environment variables, bypassing any nix evaluation at all. It is much faster to enter a cached shell with nix-direnv - nearly instant.

**Comment by domenkozar** [comment]
Agreed, I'd really like that to be a feature of Nix one day.

Refs #35

**Comment by domenkozar** [comment]
See https://github.com/cachix/devenv/pull/387
