### ISSUE TITLE
Easy support for adding Nix User Repository (NUR)

### ISSUE THREAD

**Issue by vsoch** [cachix/devenv#134]
Hi! I'd like to install packages from a NUR: https://nur.nix-community.org/repos/rseops/ and I didn't see any obvious docs for it.
How do I tell devenv about this set of NUR repos? There are quite a few good packages there!

Update: this thread might have helpful hints for how we'd add it directly to nix: https://discourse.nixos.org/t/introducing-nur-the-nix-user-repostory-share-all-your-nix-expressions/431/5 or https://nur.nix-community.org/documentation/

Many thanks!

**Comment by domenkozar** [comment]
Here's an example how to do it: https://github.com/cachix/devenv/pull/149

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/tree/main/examples/nur

**Comment by vsoch** [comment]
Perfecto! Thank you! :pray:
