### ISSUE TITLE
Make it easy to change JDK version for languages.clojure

### ISSUE THREAD

**Issue by socksy** [cachix/devenv#1341]
For languages.java and languages.scala it seems to be quite simple to change the JDK version. 

However, there's no way to do that for Clojure, and using `languages.java.jdk.package` does not appear to affect the jdk version used in Clojure:

```
$ java -version
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment (build 22+36-nixos)
OpenJDK 64-Bit Server VM (build 22+36-nixos, mixed mode, sharing)
$ clojure --version
Clojure CLI version 1.11.3.1463
$ clj
Clojure 1.11.1
user=> (System/getProperty "java.version")
"21"
```

**Comment by domenkozar** [comment]
cc @k3yss
