### ISSUE TITLE
redis is not stopped when devenv test fail

### ISSUE THREAD

**Issue by blackheaven** [cachix/devenv#1342]
**Describe the bug**
`redis` service is not stopped when `devenv test` fail, it stays daemonized.

**To reproduce**
[The gist](https://gist.github.com/blackheaven/a6ee2c51393585dee87e2b00ebfd2fd4)

```
$ ps aux | grep redis
```

**Version**
 
devenv 1.0.7 (x86_64-linux)

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/pull/1397
