### ISSUE TITLE
Difference between eval of a flake from github and from a local clone of the same repo

### ISSUE THREAD

**Issue by R-VdP** [cachix/devenv#138]
The following devenv config fails to evaluate:
https://gist.github.com/R-VdP/c9e7f40bcd007ec268cbd3e94ffb9711

As the call to `traceValSeq` shows, all the providers evaluate to `null`.

However, when I make a local clone of the repo and refer to it (`path:./nixpkgs-terraform-providers-bin`), then everything works without issues.

**Comment by domenkozar** [comment]
@R-VdP Hey! I'm not able to access that gist, is it private?

**Comment by R-VdP** [comment]
Hi @domenkozar, sorry an extra character got added to the URL somehow, I edited the URL above and it should work now!

**Comment by domenkozar** [comment]
Even with the latest changes it fails to contain any plugins, I'll report a bug tomorrow.

**Comment by domenkozar** [comment]
Report: https://github.com/NixOS/nix/pull/6530#issuecomment-1332450372

**Comment by domenkozar** [comment]
@edolstra fixed the bug, can you try https://github.com/cachix/devenv/pull/176

**Comment by R-VdP** [comment]
@domenkozar, yes all looks good now, thanks!
