### ISSUE TITLE
process-compose `sudo: exec: command not found`

### ISSUE THREAD

**Issue by RafaelKr** [cachix/devenv#1391]
**Describe the bug**

Using process-compose with its new `is_elevated` option leads to the bug described in https://github.com/F1bonacc1/process-compose/issues/223

This happens because `exec` is not available when used in combination with `sudo`: https://github.com/cachix/devenv/blob/b285601679c7686f623791ad93a8e0debc322633/src/modules/process-managers/process-compose.nix#L60

cc @stephank: You added this change in https://github.com/cachix/devenv/commit/78766e0df9ba0ff1923511b288d0489ba2d3a077, do you maybe have any more insights to share or an idea how to solve this?

**To reproduce**
Please see https://github.com/F1bonacc1/process-compose/issues/223

**Version**
devenv 1.0.8 (x86_64-linux)

**Comment by RafaelKr** [comment]
As this works: https://github.com/RafaelKr/process-compose-is-elevated-repro/commit/fa283f213976242d00cdb1260e2c581cea72f565
Maybe we can just remove the `exec`? Is there a specific reason to keep this there?

**Comment by sandydoo** [comment]
The `exec` skips creating an extra process. Seems like we either need to remove the `exec` or the script wrapper. Or maybe check for `is_elevated` and use that to decide if we can use `exec`. cc @domenkozar
