### ISSUE TITLE
Python requirements dont update when read from file

### ISSUE THREAD

**Issue by clotodex** [cachix/devenv#1401]
**Describe the bug**
The requirements.txt file, when used as the way to tell devenv about python requirements, has no effect on the "reloading of the environment". I would expect if I change a line in the file, that devenv rebuilds the environment.

**To reproduce**
```
  languages.python = {
    enable = true;
    uv.enable = true;
    venv = {
      enable = true;
      requirements = ./requirements.txt;
    };
  };
```
load the environment, then change the requirements.txt file, when devenv reloads it does not call uv again

**Version**
1.0.8

**Comment by thenonameguy** [comment]
> I would expect if I change a line in the file, that devenv rebuilds the environment.

When `devenv shell` manually is invoked, it should re-build the proper environment.

> when devenv reloads

Devenv doesn't "reload", direnv runs its `.envrc` file on each shell prompt.

With regular devenv usage, the above `devenv shell` call is managed by the `direnv` integration.
You can instrument `direnv` to pick up file changes to your file, see the example below:


https://github.com/cachix/devenv/blob/5340ef87de79a5e23414e6707cc90009e97745d5/templates/flake-parts/.envrc#L5

Just replace `flake.nix` with `requirements.txt` (or any files that you want the shell re-evaluation to trigger).

**Comment by clotodex** [comment]
You are right! Thank you, I was not aware of this.
Convenience wise this might be really cool to warn about by devenv if the config depends on a file not watched via direnv (simple reading of direnv.yaml should be enough)
I still have the feeling that keeping the requirements consistent is a bit finicky but there are other issues on this already
Closing for now.
