### ISSUE TITLE
proper way to build my app?

### ISSUE THREAD

**Issue by sebastianwebber** [cachix/devenv#1434]
Hello everyone, thanks for this great tool!

I'm starting to use Devenv. I'd like to replace my flake file with the `devenv.nix` config file, but the first thing that I miss is a place in the config to add my app outputs, like a container image or binary file.

What are your recommendations about this? Should I keep both the `devenv.nix` and the `flake.nix` files?

What is the suggested workflow for building my apps with Devenv?

Since I'm new to Nix, Flakes, and Devenv, I still don't know the best way to proceed.

**Comment by sebastianwebber** [comment]
It looks like what i'm looking for are the outputs that were added in 1.1:
https://devenv.sh/outputs/

**Comment by domenkozar** [comment]
Just released: https://devenv.sh/blog/2024/09/11/devenv-11-nested-nix-outputs-using-the-module-system/
