### ISSUE TITLE
nixos-rebuild error: function 'anonymous lambda' called with unexpected argument 'nix'

### ISSUE THREAD

**Issue by ddogfoodd** [cachix/devenv#1444]
**Describe the bug**
When trying to rebuild nixos with the latest nixos-unstable changes there is an error, which I assume might occur due to devenv 1.1 making it into nixos-unstable.

Here is the error message:
```
┏━ 1 Errors:
┃ error:
┃        … while calling the 'head' builtin
┃          at /nix/store/2pw5bsq1r80lcvvh2wp89m142nln1zpl-source/lib/attrsets.nix:1575:11:
┃          1574|         || pred here (elemAt values 1) (head values) then
┃          1575|           head values
┃              |           ^
┃          1576|         else
┃
┃        … while evaluating the attribute 'value'
┃          at /nix/store/2pw5bsq1r80lcvvh2wp89m142nln1zpl-source/lib/modules.nix:821:9:
┃           820|     in warnDeprecation opt //
┃           821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
┃              |         ^
┃           822|         inherit (res.defsFinal') highestPrio;
┃
┃        (stack trace truncated; use '--show-trace' to show the full trace)
┃
┃        error: function 'anonymous lambda' called with unexpected argument 'nix'
┃        at /nix/store/2pw5bsq1r80lcvvh2wp89m142nln1zpl-source/pkgs/by-name/de/devenv/package.nix:1:1:
┃             1| { lib
┃              | ^
┃             2| , stdenv
┃        Did you mean lib?
┣━━━
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 15:15:50 after 13s
```

**Version**
 
Current version I have installed is 1.0.8
This error occurs when trying to update to 1.1

**Comment by heinwol** [comment]
@ddogfoodd I confirm, has the exact same issue. Maybe will use upstream for now.

**Comment by devusb** [comment]
@ddogfoodd are you using Lix? If so, believe there's a conflict between [this bit](https://git.lix.systems/lix-project/nixos-module/src/commit/353b25f0b6da5ede15206d416345a2ec4195b5c8/overlay.nix#L16) in their overlay and [this nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/341157) that causes this issue -- the PR removed `nix` as an input to the devenv derivation, but the overlay still passes it.

**Comment by domenkozar** [comment]
Thanks @devusb

**Comment by devusb** [comment]
https://git.lix.systems/lix-project/nixos-module/pulls/34 fix is in `main`, sounds like a release with it is still pending.

**Comment by BreakingTV** [comment]
Ohhh okay my bad, thx ^^
