### ISSUE TITLE
Getting build loops repeating shell and processes build

### ISSUE THREAD

**Issue by sebasmagri** [cachix/devenv#1450]
**Describe the bug**
When activating the shell for the set up documented below the build takes a long time and repeatedly logs the `Building processes` and `Building shell` steps.

**To reproduce**

Setup and logs: https://gist.github.com/sebasmagri/a18ba94bd994d22db42bf28dc834d876

**Version**
 
`devenv 1.1.0 (x86_64-linux)` installed with home-manager

**Comment by domenkozar** [comment]
That doesn't look good, let me look into it.

**Comment by domenkozar** [comment]
@sebasmagri it's because you're launching `devenv up` inside `enterShell` by using backticks for quotes, which creates a loop:

enterShell -> `devenv up` -> enterShell -> `devenv up` -> ...

**Comment by sebasmagri** [comment]
@domenkozar darn, good catch... should have been obvious. thanks a lot for looking into this!
