### ISSUE TITLE
vscode integration terminal fail with: libc errors under a folder using devenv

### ISSUE THREAD

**Issue by orbuluh** [cachix/devenv#1464]
Hope this is the right place to ask. My vscode does install the extension: `pinage404.nix-extension-pack`, and when I open vscode integrated terminal from a devenv repo, I see the error messages (and terminal exit with code 127):

```
/bin/bash: symbol lookup error: /nix/store/7v7c61ikm7cbd3kbimk9qr8h7pdmyccn-manylinux2014/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE
```

  
I suspect it's because different versions of bash, the one used under the devenv and the one used in my windows WSL2 are different and link to different glibc

Inside the project:

```command -v bash
/nix/store/a1s263pmsci9zykm5xcdf7x9rv26w6d5-bash-5.2p26/bin/bash

/nix/store/a1s263pmsci9zykm5xcdf7x9rv26w6d5-bash-5.2p26/bin/bash --version | grep "GNU b"
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)
```

```
ldd /nix/store/a1s263pmsci9zykm5xcdf7x9rv26w6d5-bash-5.2p26/bin/bash
linux-vdso.so.1 (0x00007ffc15863000)
libdl.so.2 => /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libdl.so.2 (0x00007f0392457000)
libc.so.6 => /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6 (0x00007f039226a000)
/nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/ld-linux-x86-64.so.2 => /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib64/ld-linux-x86-64.so.2 (0x00007f039245e000)
```

```
nm -gD /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6 | grep __tunable_is_initialized
                 U __tunable_is_initialized@GLIBC_PRIVATE
```

On the other hand, in my local system:

```

command -v bash
/usr/bin/bash

/usr/bin/bash --version | grep "GNU b"
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

```
ldd /usr/bin/bash
linux-vdso.so.1 (0x00007ffc30dfb000)
libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fbb32155000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbb31f2c000)
/lib64/ld-linux-x86-64.so.2 (0x00007fbb322f3000)
```
```
nm -gD /lib/x86_64-linux-gnu/libc.so.6 | grep __tunable_is_initialized
# show nothing
```

So maybe it's failing because the devenv bash is used by the vscode integrated terminal, but it doesn't correctly link to the right libc.so.6. 

Has anyone seen this before? And what do you think the best way is to fix? Thanks in advance!

**Comment by domenkozar** [comment]
Try `languages.python.manylinux.enable = false;`

**Comment by orbuluh** [comment]
Thank you so much—the problem is resolved! I've been trying to fix this for days without any clues. Did you identify the issue simply because you saw the 7v7c61ikm7cbd3kbimk9qr8h7pdmyccn-manylinux2014 in the hash? I'm curious why this issue only occurred in the VSCode integrated terminal, while everything works fine in other emulators. I must have overlooked this option when I was reviewing them earlier.
