### ISSUE TITLE
Empty `RUSTFLAGS` are still set

### ISSUE THREAD

**Issue by delehef** [cachix/devenv#1496]
**Describe the bug**

Even if the computed value is empty, the `RUSTFLAGS` env. var. [is still set](https://github.com/cachix/devenv/blob/main/src/modules/languages/rust.nix#L139) when activating rust with `languages.rust.enable = true;`.

However, an empty `RUSTFLAGS` env. var. [inhibits any rust flags](https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags) that may have been set in `.cargo/config.toml`.

**To reproduce**
Set some rust flags in the `[build]` section of `.cargo/config.toml`, do not alter `languages.rust.rustflags`, and enable the rust environment with `languages.rust.enable = true;`.

**Version**
 
`devenv 1.1.0`

**Comment by domenkozar** [comment]
Could you test https://github.com/cachix/devenv/pull/1498

**Comment by clotodex** [comment]
could this be related in any way? #1419 
I am thinking if this is afffecting more than just rustflags or if there are any cross-effects?

**Comment by domenkozar** [comment]
@delehef we can't dynamically filter `env` because that creates recursion errors.

I've pushed a fix that sets it to `null`, which should make sure it's not set. Can you try again?

**Comment by domenkozar** [comment]
Alright merged, thanks!
