### ISSUE TITLE
error: attribute 'unix-socket' missing

### ISSUE THREAD

**Issue by brianmay** [cachix/devenv#1497]
**Describe the bug**
After updating flake to latest devenv main, we get this error:

```
# devenv up
warning: Git tree '/home/brian/tree/3rdparty/teslamate' is dirty
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'devenv-up'
         whose name attribute is located at /nix/store/6dxvxz52z172kxdi97bw4grpkhzx4dx7-source/pkgs/stdenv/generic/make-derivation.nix:333:7

       … while evaluating attribute 'text' of derivation 'devenv-up'

         at /nix/store/6dxvxz52z172kxdi97bw4grpkhzx4dx7-source/pkgs/build-support/trivial-builders/default.nix:103:16:

          102|       ({
          103|         inherit text executable checkPhase allowSubstitutes preferLocalBuild;
             |                ^
          104|         passAsFile = [ "text" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'unix-socket' missing

       at /nix/store/i64dnpssfd0xfcvl11ld4brs3l393nz9-source/src/modules/process-managers/process-compose.nix:42:54:

           41|       ${cfg.package}/bin/process-compose --config ${cfg.configFile} \
           42|         --unix-socket ''${PC_SOCKET_PATH:-${toString config.process.process-compose.unix-socket}} \
             |                                                      ^
           43|         --tui=''${PC_TUI_ENABLED:-${lib.boolToString config.process.process-compose.tui}} \
```

**To reproduce**

1. git clone https://github.com/teslamate-org/teslamate.git
2. cd teslamate
3. git checkout dc64687ba8f150b9da664cc411c4f7111f231418
4. nix flake update
5. devenv up

**Version**

Latest main version. `github:cachix/devenv/4549e9ea6b9fe90ee5ea6705f7f82f301f464d6b`

**Comment by brianmay** [comment]
git bisect shows this is the first bad commit eab7aa8d11cf36a8de13c6597aacfa006c4d62af

**Comment by domenkozar** [comment]
@brianmay what version of process-compose do you have?

**Comment by brianmay** [comment]
I had similar issues with nixos-24.05 (1.6.1) and nixos-unstable (1.27.0).

But the issue looks like it is with `config.process.process-compose.unix-socket` missing to me. i.e. it happens before we even try to run `process-compose`.

**Comment by sandydoo** [comment]
Should be fixed by #1161. 

The `process.process-compose` option was not configured to merge its contents, so [your changes here](https://github.com/teslamate-org/teslamate/blob/ad341310893fdb14ebd3cb72e1cc23e467c3e6a2/flake.nix#L151-L154) would override the defaults, including the `unix-socket`.

**Comment by JakobLichterfeld** [comment]
> Should be fixed by #1161.

Thanks.  The reported error regarding unix-socket is solved.

We now get:

```bash
error:
       … while evaluating the attribute 'optionalValue.value'

         at /nix/store/sdzpqjwx7pdx6lsq6llyfqqf7hspp83c-source/lib/modules.nix:863:5:

          862|
          863|     optionalValue =
             |     ^
          864|       if isDefined then { value = mergedValue; }

       … while evaluating a branch condition

         at /nix/store/sdzpqjwx7pdx6lsq6llyfqqf7hspp83c-source/lib/modules.nix:864:7:

          863|     optionalValue =
          864|       if isDefined then { value = mergedValue; }
             |       ^
          865|       else {};

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `process.process-compose.port' does not exist. Definition values:
       - In `<unknown-file>': 7002
```

Should we use `process-managers.process-compose.port` for this?

**Comment by sandydoo** [comment]
> Adapting to new namings, it runs fine.

🎉 

Did `process.process-compose.port` do anything previously? I don't see any mention of it anywhere, which is why I didn't write a migration for it.

**Comment by JakobLichterfeld** [comment]
> Did `process.process-compose.port` do anything previously? I don't see any mention of it anywhere, which is why I didn't write a migration for it.

@brianmay Can you elaborate on this?

**Comment by sandydoo** [comment]
Ah, it was unceremoniously removed in https://github.com/cachix/devenv/pull/1147. Unfortunate. I'll add a migration for it.
