### ISSUE TITLE
python.uv.sync.enable and python.venv.enable have conflicting PATH exports

### ISSUE THREAD

**Issue by mauricege** [cachix/devenv#1502]
**Describe the bug**
In order to have a python venv that is managed through uv, one has to set both `languages.python.uv.sync.enable` and `languages.python.venv.enable` to true. Since the tasks update, both define PATH as exports - however, the initUvScript does not activate the virtual environment and therefore its path does not include the venv at the front. This randomly leads to a `.devenv/load-exports` file in which PATH from "devenv:python:virtualenv" gets overwritten by the value from "devenv:python:uv" and therefore not correctly activating the venv.

I tried to fix it by setting:
```nix
{
   tasks."devenv:python:uv".before = ["devenv:python:virtualenv"];
}
```
But the order of the tasks does not seem to reflect the order of variable exports in `.devenv/load-exports`.

Removing "PATH" from the task exports of "devenv:python:uv" seems to work and I have not noticed any problems:
```nix
{
   tasks."devenv:python:uv".exports = lib.mkForce ["VIRTUAL_ENV"];
}
```

**To reproduce**
Minimal devenv.nix to reproduce:
```nix
{
  languages.python = {
    enable = true;
    venv.enable = true;
    uv.enable = true;
    uv.sync.enable = true;
  };
}
```

**Version**
 devenv 1.3.0 (x86_64-linux)

**Comment by domenkozar** [comment]
@mauricege could you try https://github.com/cachix/devenv/pull/1504

**Comment by mauricege** [comment]
> @mauricege could you try #1504

With these fixes I was unable to reproduce the error - at least after direnv reloading ~20 times.

However, I do not get how the order of devenv:python:virtualenv and devenv:python:uv is enforced? Is it alphabetical sorting?

**Comment by domenkozar** [comment]
The fixes makes sure that outputs order is respected, so we should tell uv to depend on virtualenv

**Comment by JonathanTroyer** [comment]
This issue isn't fully resolved. The nondeterministic ordering fix in #1504 helped, but the fundamental problem remains: when `languages.python.uv.sync.enable = true`, the Nix-provided python still shadows the venv python on PATH.

**Root cause:** The `languages.python` module unconditionally adds `cfg.package` to `packages`, which gets included in `mkShell` buildInputs. These end up early on PATH. The `devenv:python:uv` task later runs `uv sync` and sources `activate`, but its PATH export lands *after* the Nix python because packages/buildInputs are resolved before task exports.

```
$ devenv shell -- which -a python | head -3
/nix/store/...-python3-3.12.12-env/bin/python    # Nix wrapper (position 2, no project deps)
/nix/store/...-python3-3.12.12/bin/python         # bare Nix python
/path/to/project/.devenv/state/venv/bin/python    # venv (position 54, has project deps)
```

Bare `python` resolves to the Nix interpreter, which lacks project dependencies:

```
$ devenv shell -- python -c "import torch"
ModuleNotFoundError: No module named 'torch'   # torch is installed in the venv
```

On NixOS this is worse — `uv sync` also installs a PyPI-downloaded `uv` binary into the venv that's dynamically linked and can't execute, so `uv` itself breaks if the venv bin is earlier on PATH.

**Workaround:** Add a task that re-activates the venv after devenv's uv task:

```nix
tasks."devenv:python:venv-activate" = {
  exec = ''source "${config.env.DEVENV_STATE}/venv/bin/activate"'';
  exports = [ "PATH" "VIRTUAL_ENV" ];
  after = [ "devenv:python:uv" ];
  before = [ "devenv:enterShell" ];
};
```

**Suggested fix:** When `uv.sync.enable = true`, don't add `cfg.package` to the `packages` list. The interpreter is still available via `cfg.package.interpreter` for `uv venv -p`:

```nix
packages = lib.optional (!cfg.uv.sync.enable) cfg.package;
```

devenv 2.0.1, uv 0.10.6, NixOS.

**Comment by domenkozar** [comment]
> This issue isn't fully resolved. The nondeterministic ordering fix in [#1504](https://github.com/cachix/devenv/pull/1504) helped, but the fundamental problem remains: when `languages.python.uv.sync.enable = true`, the Nix-provided python still shadows the venv python on PATH.
> 
> **Root cause:** The `languages.python` module unconditionally adds `cfg.package` to `packages`, which gets included in `mkShell` buildInputs. These end up early on PATH. The `devenv:python:uv` task later runs `uv sync` and sources `activate`, but its PATH export lands _after_ the Nix python because packages/buildInputs are resolved before task exports.
> 
> ```
> $ devenv shell -- which -a python | head -3
> /nix/store/...-python3-3.12.12-env/bin/python    # Nix wrapper (position 2, no project deps)
> /nix/store/...-python3-3.12.12/bin/python         # bare Nix python
> /path/to/project/.devenv/state/venv/bin/python    # venv (position 54, has project deps)
> ```
> 
> Bare `python` resolves to the Nix interpreter, which lacks project dependencies:
> 
> ```
> $ devenv shell -- python -c "import torch"
> ModuleNotFoundError: No module named 'torch'   # torch is installed in the venv
> ```
> 
> On NixOS this is worse — `uv sync` also installs a PyPI-downloaded `uv` binary into the venv that's dynamically linked and can't execute, so `uv` itself breaks if the venv bin is earlier on PATH.
> 
> **Workaround:** Add a task that re-activates the venv after devenv's uv task:
> 
> tasks."devenv:python:venv-activate" = {
>   exec = ''source "${config.env.DEVENV_STATE}/venv/bin/activate"'';
>   exports = [ "PATH" "VIRTUAL_ENV" ];
>   after = [ "devenv:python:uv" ];
>   before = [ "devenv:enterShell" ];
> };
> **Suggested fix:** When `uv.sync.enable = true`, don't add `cfg.package` to the `packages` list. The interpreter is still available via `cfg.package.interpreter` for `uv venv -p`:
> 
> packages = lib.optional (!cfg.uv.sync.enable) cfg.package;
> devenv 2.0.1, uv 0.10.6, NixOS.

Could I ask you to open another issue so we don't lose this?

**Comment by domenkozar** [comment]
> This issue isn't fully resolved. The nondeterministic ordering fix in [#1504](https://github.com/cachix/devenv/pull/1504) helped, but the fundamental problem remains: when `languages.python.uv.sync.enable = true`, the Nix-provided python still shadows the venv python on PATH.
> 
> **Root cause:** The `languages.python` module unconditionally adds `cfg.package` to `packages`, which gets included in `mkShell` buildInputs. These end up early on PATH. The `devenv:python:uv` task later runs `uv sync` and sources `activate`, but its PATH export lands _after_ the Nix python because packages/buildInputs are resolved before task exports.
> 
> ```
> $ devenv shell -- which -a python | head -3
> /nix/store/...-python3-3.12.12-env/bin/python    # Nix wrapper (position 2, no project deps)
> /nix/store/...-python3-3.12.12/bin/python         # bare Nix python
> /path/to/project/.devenv/state/venv/bin/python    # venv (position 54, has project deps)
> ```
> 
> Bare `python` resolves to the Nix interpreter, which lacks project dependencies:
> 
> ```
> $ devenv shell -- python -c "import torch"
> ModuleNotFoundError: No module named 'torch'   # torch is installed in the venv
> ```
> 
> On NixOS this is worse — `uv sync` also installs a PyPI-downloaded `uv` binary into the venv that's dynamically linked and can't execute, so `uv` itself breaks if the venv bin is earlier on PATH.
> 
> **Workaround:** Add a task that re-activates the venv after devenv's uv task:
> 
> tasks."devenv:python:venv-activate" = {
>   exec = ''source "${config.env.DEVENV_STATE}/venv/bin/activate"'';
>   exports = [ "PATH" "VIRTUAL_ENV" ];
>   after = [ "devenv:python:uv" ];
>   before = [ "devenv:enterShell" ];
> };
> **Suggested fix:** When `uv.sync.enable = true`, don't add `cfg.package` to the `packages` list. The interpreter is still available via `cfg.package.interpreter` for `uv venv -p`:
> 
> packages = lib.optional (!cfg.uv.sync.enable) cfg.package;
> devenv 2.0.1, uv 0.10.6, NixOS.

I've pushed a commit an hour ago that might fix your issue, will be part of devenv 2.0.4

**Comment by leiserfg** [comment]
@domenkozar, do you mind releasing that fix, I'm stuck in 1.x because of this.

**Comment by domenkozar** [comment]
We're fixing https://github.com/cachix/devenv/issues/2602 and then 2.0.4 is getting released.
