### ISSUE TITLE
Can't set DYLD_FALLBACK_LIBRARY_PATH env var while other variables can be set correctly

### ISSUE THREAD

**Issue by onsails** [cachix/devenv#1523]
**Describe the bug**
I'm trying to define `DYLD_FALLBACK_LIBRARY_PATH` environment variable but it's not being picked up by a devenv shell.

**To reproduce**

Put into devenv.nix:

```
env.DYLD_FALLBACK_LIBRARY_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
env.DYLD = "${pkgs.llvmPackages.libclang.lib}/lib";
```

in devshell:

```
❯ env | grep DYLD
LD_DYLD_PATH=/usr/lib/dyld
DYLD=/nix/store/4s2s478cgc19jclm1zg2anjd0kh549nb-clang-16.0.6-lib/lib
```

as you can see, `DYLD_FALLBACK_LIBRARY_PATH` is absent

Make sure to include full logs and what you expected to happen.

**Version**
 
Paste the output of `$ devenv version` here or tell us if you're using flakes.

```
❯ devenv version
devenv 1.3.0 (aarch64-darwin)
```

**Comment by sandydoo** [comment]
IIRC there's a SIP restriction that prevents this variable from being passed across `exec` boundaries.

Try exporting it in `enterShell`.

**Comment by onsails** [comment]
thanks, solved with

```
  env.DYLD =  "${pkgs.llvmPackages.libclang.lib}/lib";
  enterShell = ''
    export DYLD_FALLBACK_LIBRARY_PATH=$DYLD
  '';
```
