### ISSUE TITLE
Cachix substituter not being picked up by devenv

### ISSUE THREAD

**Issue by samchouse** [cachix/devenv#1527]
**Describe the bug**
Devenv complains about its cachix instance not being added to trusted substituters even though it is added.

**To reproduce**
Since I've added devenv as a trusted substituter I'd expect cachix to work. https://gist.github.com/samchouse/0cba1c6787af2d26a0c7a93a681cc292

**Version**
devenv 1.3.0 (x86_64-linux) via nixpkgs (home.packages)

**Comment by rvveber** [comment]
Same issue here!
In addition the recommendation on how to add them is incorrect:
```
b) Add binary caches to /etc/nix/nix.conf yourself by editing configuration.nix:
{
    nix.extraOptions = ''
        extra-substituters = https://devenv.cachix.org;
        extra-trusted-public-keys = devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= nixpkgs-python.cachix.org-1:hxjI7pFxTyuTHn2NkvWCrAUcNZLNS3ZAvfYNuYifcEU=;
    '';
}
```

Should be without the `;`'s at the end.

**Comment by sandydoo** [comment]
devenv doesn't check your configured substituters, so the only way to disable this atm is to add the following to your `devenv.nix`:

```nix
cachix.enable = false;
```

I'll try to get this fixed.

The error message should've at least mentioned this, but it somehow got lost over time.

**Comment by samchouse** [comment]
Does this completely disable cachix meaning I have to build everything myself?

**Comment by sandydoo** [comment]
You have both the nixos and devenv caches set up in `/etc/nix/nix.conf`, so you're all set up. This tells devenv not to try to set them up for you.

**Comment by samchouse** [comment]
Is this normal with `cache.enable = false;`?

```
warning: ignoring the client-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
```
