### ISSUE TITLE
Support unfree and overlays

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#154]
Wire up overlays and allowUnfree

https://nixos.wiki/wiki/Flakes

**Comment by kubukoz** [comment]
My team is currently looking at switching to Devenv for a lower entry barrier (compared to raw flakes), overlays seem to be the remaining blocker atm. Do you have an idea on how this could work?

In particular, the overlays I want to add right now come from one of the inputs.

**Comment by domenkozar** [comment]
I'll work on this next then, thanks :)

**Comment by domenkozar** [comment]
@kubukoz @smunix @pikdum @shyim @jochenmanz @arjan-s @mstine See https://github.com/cachix/devenv/pull/383
