### ISSUE TITLE
Configuring tauri v2 for android development

### ISSUE THREAD

**Issue by Grandkahuna43325** [cachix/devenv#1556]
Hello, I'm trying to create devenv.nix for tauri development but I'm stuck on installing android studio. 
I'm trying to follow tauri [tutorial](https://v2.tauri.app/start/prerequisites/#android) and [this?](https://ryantm.github.io/nixpkgs/languages-frameworks/android/#using-predefined-android-package-compositions) but I'm failing miserably. 
This is the current state of the config but it's not even remotely close to what I'm looking for [devenv.nix.txt](https://github.com/user-attachments/files/17530294/devenv.nix.txt) 

The goal is to run `npm run tauri android dev` and compile the project.

**Comment by sandydoo** [comment]
You could try asking around on our [Discord](https://discord.gg/naMgvexb6q), though I'm not sure there are too many people running this type of setup. 

Unless there's a specific devenv issue here, I'm not sure we'll be able to help you out.

**Comment by Grandkahuna43325** [comment]
I'm closing the issue now, i found a solution and it's posted on my github in tauri-mobile-nixos-template
