### ISSUE TITLE
[docs] why the docs dont receive any love here

### ISSUE THREAD

**Issue by Aneeqasif** [cachix/devenv#1592]
Hi there , consider me as a relatively new devenv user, my issue is : why you guys don't show any love to docs ?

I was trying to wrap my workflow around devenv and i am not yet fluent enough to read directly the source so i was reading the docs and following are the issues I encountered and i wanted to let you guys know.

### Missing/empty pages
- https://devenv.sh/roadmap/ -> mentioned on the repo readme
- https://devenv.sh/processes.md -> mentioned [here](https://devenv.sh/tests/)

## very shallow info in docs
I was looking the tasks page on docs website and  wanted to try the `python:hello` example 
and it didn't work , at first I thought there was just an extra quote there by mistake **(which I believe there is)**  but even after removing it, the example still didn't run properly.

### Make it a lil bit beginner oriented

I know this is kind of project that is meant to be used by matured users but guys I did'nt have any clue about the ability to use ` after = [ "devenv:python:virtualenv" ];`  until I stumbled upone [devnv-blog](https://devenv.sh/blog/2024/09/24/devenv-12-tasks-for-convergent-configuration-with-nix/#usage) 
and yes after some digging i found all the good stuff in the reference page but it would be nice if you give a pointer on the tasks page that there are lists of tasks that devenv defined which one cane use in `after` attribute etc.

and there are the things i found a lil off  . I hope i am not seen as yet another annoying issue reporter.

**Comment by domenkozar** [comment]
Hey! Thanks for spotting these errors, I've pushed f59a3aab0c72f7afb9e0cb03cf0e9be9d523023f to fix them.

In general to assure the docs work well we need to implement #50 and #122

**Comment by Aneeqasif** [comment]
thanks i just wanted to report that issue and my concerns.
