### ISSUE TITLE
Set custom TMPDIR as the nix-shell folder is gone

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#1620]
The cached `devenv up` contains a TMPDIR, and at some point that folder is gone and software start failing

![image](https://github.com/user-attachments/assets/6fa9157c-a234-4b37-866a-337e11465ec8)

That TMPDIR should point to a custom one in `.devenv/tmp` or use the regular system tmp (omit that env)

**Comment by sandydoo** [comment]
We've had a few reports of this, but so far little info on how to reproduce this. 

- Is this using the flakes integration?
- Linux or macOS?
- Any specific steps?
