### ISSUE TITLE
Devcontainer not working for devenv development

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#171]
**Describe the bug**
```
@shyim ➜ /workspaces/devenv (main) $ ./result/bin/devenv shell
Building shell ...
warning: Git tree '/workspaces/devenv' is dirty
error: suspicious ownership or permission on '/nix/store/rbi9ibwrwa6mrv8a08q2kjgq7issgwvm-devcontainer.json' for output 'out'; rejecting this build output
error: 1 dependencies of derivation '/nix/store/2d2x8py0nvnq4r2n6dn6x8hanm29bha2-devenv-env.drv' failed to build
```

```
@shyim ➜ /workspaces/devenv (main) $ ls -la /nix/store/rbi9ibwrwa6mrv8a08q2kjgq7issgwvm-devcontainer.json
-rw-r--rw- 1 nixbld1 nixbld 74 Dec  2 11:58 /nix/store/rbi9ibwrwa6mrv8a08q2kjgq7issgwvm-devcontainer.json
```

Deleting that file and opening the shell does not help its broken again

**To Reproduce**
```bash
nix build
./result/bin/devenv shell
```

**Version**
 
main branch (89cd0f7d6122cbe1f351e8f6fccc7fc638690e9f)

**Comment by domenkozar** [comment]
I see the issue, I'll look into it.

**Comment by domenkozar** [comment]
Also need to install https://github.com/direnv/direnv-vscode

**Comment by kkharji** [comment]
Same issue, just `devcontainer.enable = true` then opened it for testing

**Comment by jonasb** [comment]
I get the same issue when using the devcontainer created by `devcontainer.enable = true` in my own repo as well. So it seems to not only be when working on devenv itself.

devenv: 0.4

**Comment by domenkozar** [comment]
I'll fix this one soon, I have an idea how to get it done.

**Comment by domenkozar** [comment]
Need to check what they do in https://github.com/zombiezen/codespaces-nix

**Comment by thedavidmeister** [comment]
deleting `.devcontainer.json` did not work for me, it simply meant that the default codespaces without `devenv` was used so i couldn't enter a devenv shell

**Comment by domenkozar** [comment]
I'll look into this one tomorrow

**Comment by thedavidmeister** [comment]
@domenkozar any luck/progress/workaround for this one?

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/pull/482 should fix it and I pushed the newest image.

Can you try using devcontainer on the repo that didn't work before?

**Comment by thedavidmeister** [comment]
@domenkozar this bug does seem to be fixed, sadly cargo seems to be blowing resource limits on codespaces, even on a machine that would cost me $50-100 a month

any chance we could get it compiling on mac? https://github.com/cachix/devenv/issues/267

**Comment by shyim** [comment]
do you have an example repo? sounds strange

**Comment by thedavidmeister** [comment]
@shyim it's not that strange that rust uses a ton of memory, storage and cpu to compile

this was enough to get a sigkill during compilation (usually means resource usage on CI)

```
cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil chisel --bins --locked
```

**Comment by kolaente** [comment]
It seems like the problem originally reported here is still (again?) a problem with the latest release: https://github.com/cachix/devenv/issues/1896
