### ISSUE TITLE
devenv init: create missing files

### ISSUE THREAD

**Issue by vajo3694** [cachix/devenv#179]
If I have only `devenv.nix` file and run `devenv init` then devenv say that all devenv files exist and no file create for me.

Expectation:
A question from devenv if it can add other files or delete my file and add all files.

**Comment by matu3ba** [comment]
> A question

Please no slow interaction, if not necessary. `devenv init` should fail and tell user to use `-f` to force an overwrite, if strictly necessary.

**Comment by vajo3694** [comment]
I don’t want overwrite my devenv.nix file. I want to create all other files.
