### ISSUE TITLE
postgresql.conf: set timezone

### ISSUE THREAD

**Issue by vajo3694** [cachix/devenv#180]
Why select this for me? I'm from timezone `Europe/Bratislava`. It's not the same country...

`.devenv/state/postgresql/postgresql.conf`

```
log_timezone = 'Europe/Prague'
timezone = 'Europe/Prague'
```

Please allow this to setup in `devenv.nix`.

**Comment by samjwillis97** [comment]
Just had a look at the documentation for the `initdb` command that is run to initialize the postgres db (https://www.postgresql.org/docs/current/app-initdb.html), if you set the environment variable `TZ` you can force it to use the `Europe/Bratislava` timezone by including the following line in the `devenv.nix` file.
```nix
env.TZ = "Europe/Bratislava";
```
