### ISSUE TITLE
yml vs toml

### ISSUE THREAD

**Issue by delta1** [cachix/devenv#20]
Heya! Very excited about this project 👌

What’s the rationale for choosing yml instead of toml or some other format for the config file?

**Comment by domenkozar** [comment]
Thanks :)

While the world desperately needs an alternative to YAML, I don't think TOML cuts it.

If YAML is human readable, TOML is geek readable. It has that ini vibe.

The goal of devenv is to lower the barrier to Nix, so I've used the mostly used format out there.

YAML won't be used in any advanced features, so I think we're fine.

**Comment by delta1** [comment]
Fair enough, although if the target user is a developer then maybe not so much :) but happy to see this and will try help! Very new to Nix
