### ISSUE TITLE
Provide cache for aarch64-darwin

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#205]
**Describe the bug**

Nix compiling takes some time. I did added `devenv` using cachix already but still no cache is used.

Maybe we can use a nix community darwin arm64 machine to generate cachaes?

**Comment by domenkozar** [comment]
Currently the blocker is that we'd need to port https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/continuous-integration/github-runners.nix to nix-darwin so setting up the machine is easy :)

**Comment by shyim** [comment]
Maybe something like https://garnix.io/ can help?

**Comment by domenkozar** [comment]
Will work on this soon, kind of depends on https://github.com/LnL7/nix-darwin/issues/582
