### ISSUE TITLE
Rename `devenv ci` to `devenv check`?

### ISSUE THREAD

**Issue by rehno-lindeque** [cachix/devenv#210]
Kind of a nitpick, but does "ci", meaning "continuous integration", make sense as an action?

I'm inclined to think of CI as an automation thing - git hooks or other triggers that fire automatically.

**Comment by domenkozar** [comment]
It does run the git hooks: https://github.com/cachix/devenv/blob/main/src/modules/pre-commit.nix#L23

That's what I wanted to have with `ci`, to be able run everything that it can (and expose it to any module).

`check` becomes too broad and abstract, although I'm not opposed to having it. The main question is what is the difference then.

**Comment by rehno-lindeque** [comment]
I guess it refers to running / triggering the complete `ci` pipeline, not to the "continuous" aspect of it, so I withdraw my complaint.

I think there's some risk that people might first assume it runs starts some kind of background daemon but without a better idea it's probably ok as far as I'm concerned.

Glancing at buildkite's jargon, I suppose maybe some kind of pattern could emerge:
* `devenv ci-pipeline`
* `devenv deploy-pipeline`
* `devenv staging-pipeline`

but I suppose just `ci` is ok

**Comment by domenkozar** [comment]
I've deprecated `deven ci` in favor of https://devenv.sh/tests
