### ISSUE TITLE
How to install python packages?

### ISSUE THREAD

**Issue by pogopaule** [cachix/devenv#221]
How do I install python packages?

```
{ pkgs, ... }:
{
  packages = [ pkgs.python310Packages.somepythonpackage ];
  languages.python.enable = true;
}
```

This does not work, because python does not know where `somepythonpackage` is located.

**Comment by domenkozar** [comment]
@thenonameguy this probably requires us setting pythonpath?

**Comment by thenonameguy** [comment]
> @thenonameguy this probably requires us setting pythonpath?

Don't know too much about how this works, will check once I have some  free-time.

**Comment by devusb** [comment]
@domenkozar what about Python dependencies as defined in `propagatedBuildInputs`? For example, if I add `pandas` as 
```
 packages = [ pkgs.python310Packages.pandas ];
```
I get missing dependencies unless I explicitly add them all to `packages`, which can get hairy if there are more than 2-3.
```
(devenv) bash-5.1$ python
Python 3.10.9 (main, Dec 12 2022, 22:19:35) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/3hjfcrdb15rznfshc9bhrrwbrf7xbl4v-devenv-profile/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'numpy'
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'
```

**Comment by domenkozar** [comment]
```nix
{ config, ... }:
{
  languages.python.enable = true;

  pacakges = [ config.languages.python.package.withPackages (ps: [ ps.pandas ]) ];
}
```

**Comment by gador** [comment]
@domenkozar where does the `{ config, ... }:` come from?
I have `{ pkgs, ... }:` on top and no `config` parameter

**Comment by domenkozar** [comment]
`...` acts like a catch-all wildcard for arguments, so you need to add `config` like so: `{ pkgs, config, ... }`

**Comment by gador** [comment]
ah, thanks! I got it working :-)
