### ISSUE TITLE
processes.mysql-configure.exec needs gsleep on mac

### ISSUE THREAD

**Issue by jochenmanz** [cachix/devenv#223]
**Describe the bug**
devenv up shuts down immediately when ensureUsers uses sleep instead of gsleep on mac. 

**To Reproduce**
services.mysql.enable = true;
  services.mysql.initialDatabases = [{ name = "test"; }];
  services.mysql.ensureUsers = [
    {
      name = "test";
      password = "test";
      ensurePermissions = { "test.*" = "ALL PRIVILEGES"; };
    }
  ];

**Version**
 devenv version
devenv: 0.4

**Comment by domenkozar** [comment]
cc @shyim

**Comment by shyim** [comment]
I will fix it @domenkozar , you can assign it to me :)
