### ISSUE TITLE
Feature: Define domains for caddy and add them to /etc/hosts

### ISSUE THREAD

**Issue by jochenmanz** [cachix/devenv#227]
**Describe the Feature**
It would be great to be able to use domain names as virtual hosts in caddy. Devenv could handle the /etc/hosts changes (or dnsmasq configuration).

**Comment by blaggacao** [comment]
- https://github.com/numtide/devshell/pull/75
- https://github.com/numtide/devshell/pull/74

**Comment by shyim** [comment]
@blaggacao do you want to make a PR to devenv if you are already familar with that

**Comment by domenkozar** [comment]
We need a solution that works for macOS and linux and ideally is scoped to the environment.

**Comment by domenkozar** [comment]
Yes please: https://guumaster.github.io/hostctl/docs/guides/basic_profiles/

**Comment by blaggacao** [comment]
It has been literally years. And we're not using `devenv` (yet). But considering.

Iirc, during all the time past there where also ideas about a `HOSTFILE` variable to define project hosts files.

It might be at least worth it to do a quick research to see where these ideas are currently at (and if they have sufficiently progressed).

**Comment by shyim** [comment]
I guess this would require some kind of pre- and post-scripts to `devenv up` to be able to execute the hostctl 🤔

**Comment by domenkozar** [comment]
A draft implementation of an opt-in shared HTTP proxy is now available in #3141. It derives `.localhost` URLs from devenv project/process names, so these local virtual hosts do not require `/etc/hosts` changes or dnsmasq. The current scope is HTTP-only and does not provide arbitrary domains or Caddy-managed HTTPS.
