### ISSUE TITLE
Terminal closes on fauly command with devenv and fish

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#23]
When my terminal is in shell and I run a faulty comand the shell closes

![image](https://user-images.githubusercontent.com/6224096/201474903-2c962cbb-1e31-4bc0-9a40-b5ed92560917.png)

**Comment by shyim** [comment]
With direnv hook its much more annoying as I don't see my command anymore

![image](https://user-images.githubusercontent.com/6224096/201474967-0f2c3d9c-dea9-4304-8022-4557835bf1eb.png)
![image](https://user-images.githubusercontent.com/6224096/201474986-bf847e3a-06dc-4aab-87de-397bcd72ac97.png)

**Comment by shyim** [comment]
Bash seems to work fine :) as expected

**Comment by domenkozar** [comment]
Can you try to install devenv from the main branch?

**Comment by shyim** [comment]
While working on an PR for devenv, I still had it 😅

**Comment by domenkozar** [comment]
And you were in devenv environment triggered by ./result/bin/devenv?

**Comment by shyim** [comment]
yes

**Comment by shyim** [comment]
After installing https://github.com/cachix/devenv/pull/28 from master it works for me.
