### ISSUE TITLE
Auto run `direnv allow`

### ISSUE THREAD

**Issue by mpscholten** [cachix/devenv#236]
Just trying out devenv on an existing project.

I ran `devenv init` as documented and then go this output:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/2072185/209313610-3a8cf8bb-03b4-4d6c-a84a-b62972feaea4.png">

First second until I read the error message i thought something was wrong with devenv.

Maybe devenv could automatically run `direnv allow` when it detects that direnv is installed and it just generated the file?

**Comment by domenkozar** [comment]
:+1:
