### ISSUE TITLE
How to get rid of mkNakedShell entirely

### ISSUE THREAD

**Issue by zimbatm** [cachix/devenv#240]
I realised recently that mkNakedShell exists because we assume that `nix develop` should be executed to enter the developer environment. But that is a mistake. `nix develop` is should be renamed `nix debug` because it's designed to enter the build environment of a derivation. This is not the same as creating a developer environment. A developer environment might include the same programs but also include other development-related toolings such as LSP servers, debuggers, ...

Another aspect is that many IDEs depend on getting the file paths to the source code. You want to point the IDE to the $LANG_SRC folder, and sometimes they want a stable location because they don't know how to reload those env vars with direnv.

This leads me to believe that the best is to put everything in a `buildEnv` and have an entry point script that loads the developer environment. `nix build .#devenv --out-link devenv` and then `./devenv/entrypoint`. Or `nix run .#devenv`. No more, do you have to clean environment variables.

Yet another aspect is that you could imagine this entrypoint script introducing proper docker-like sandboxing when it's executed.

**Comment by domenkozar** [comment]
This should also fix #36

**Comment by blaggacao** [comment]
In the discussions to
 https://github.com/NixOS/nixpkgs/pull/206915

... there is context on how `nix develop` may be also a layer violation in that it's implemented in `nixos/nix` and it wouldn't surprise me if we X(find link) would progress.

**Comment by domenkozar** [comment]
We've gotten rid of it by doing what Nix does by default, all other approaches turned out to be too error prone.

If we're going to fix this properly in the future, it should be done in nixpkgs.
