### ISSUE TITLE
Guide for Caching

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#244]
I added for our own repository a GH action to cache the build for Linux and Mac and pushing it to Cachix.

Does it make sense to have an own page for caching in the docs?

**Comment by domenkozar** [comment]
Does this make sense: https://python-rewrite.devenv.pages.dev/binary-caching/

**Comment by shyim** [comment]
Maybe a command to trigger to push

**Comment by domenkozar** [comment]
Originally I was thinking that we'd push if the push cache was defined, but that's too aggressive (most folks won't have the credentials present).

Using a flag like `--push` is explicit, but it wouldn't work when you forgot to use it. Maybe in those cases folks would just rerun the command twice?
