### ISSUE TITLE
Environment variables are not overrideable

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#250]
**Describe the bug**
Seems related to https://github.com/NixOS/nixpkgs/issues/85508

```nix
# devenv.nix

{
env.FOO = "1";
}
```

```nix
# devenv.local.nix

{
env.FOO = "2";
}
```

It always stays at 1

**Comment by shyim** [comment]
I tried to change the type to `types.attrsOf types.str;` it fails then with  "error: infinite recursion encountered"

**Comment by domenkozar** [comment]
Oh, that's really bad. I'll look into it.

**Comment by domenkozar** [comment]
I tried `types.attrsOf types.anything` but it seems like we're doing something with `env` that we shouldn't that causes the inf recursion.
