### ISSUE TITLE
`languages.rust.enable` doesn't work without adding `clang` as a package

### ISSUE THREAD

**Issue by MForster** [cachix/devenv#256]
**Describe the bug**
The Rust language environment doesn't work without manually installing the `clang` package. I think it would be a better user experience if that package was loaded automatically.

**To Reproduce**

```
mkdir devenv-rust
cd devenv-rust
devenv init
```

Use this configuration: `{ languages.rust.enable = true; }` ([as gist](https://gist.github.com/MForster/1596ed81f3da9a257bb53418f65d5ef3)).

```
direnv allow
cargo init
cargo build
```

**Result**

```
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `devenv-rust` due to previous error
```

It is always necessary to manually add `packages = with pkgs; [ clang ];`

**Version**

devenv: 0.5

**Comment by domenkozar** [comment]
What if you also set `languages.c.enable = true;`?

**Comment by MForster** [comment]
That works as an alternative workaround.

But I still consider it a workaround. I'm not using `C` after all..

**Comment by domenkozar** [comment]
This is similar to https://github.com/cachix/devenv/pull/245, which I think the best solution is that Rust and similar tooling wants compiler stuff. Maybe calling it `c` is not the best description?

**Comment by MForster** [comment]
If `cc` was installed automatically it wouldn't matter much how the option is called :-).
