### ISSUE TITLE
Starship integration doesn't work on macOS Monterey

### ISSUE THREAD

**Issue by loket** [cachix/devenv#266]
**Describe the bug**
The Starship integration does not work on macOS (Monterey 12.6.2). Here's the output when trying to run `devenv shell` with `starship.enable = true;`:

```bash
$ devenv shell
Building shell ...
warning: creating lock file '/private/tmp/devenv-starship/devenv.lock'
Entering shell ...

ps: cmd: keyword not found
ps: no valid keywords; valid keywords:
error: Found argument 'jobc' which wasn't expected, or isn't valid in this context

Usage: starship init [OPTIONS] <SHELL>

For more information try '--help'

NOTE:
    passed arguments: ["init", "%cpu", "jobc", "nwchan", "ruid", "user"]
```

This bug seems to be caused by [how the Starship integration identifies which shell is used](https://github.com/cachix/devenv/blob/493738c368612aec1f63ad9f28aa7726e057f411/src/modules/integrations/starship.nix#L38).

Here's an output from the command used, running on macOS 12.6.2:
```bash
$ ps -o cmd= $$ | awk '{print $1}'
ps: cmd: keyword not found
ps: no valid keywords; valid keywords:
%cpu
jobc
nwchan
ruid
user
```

I'm guessing this is because macOS comes with ancient versions of `ps` et al.

Could this maybe be replaced with `echo $0`, as pointed out in [this](https://github.com/cachix/devenv/issues/36#issuecomment-1343373067) comment?

As in, do this instead?
```bash
eval "$(starship init $(echo $0))"
```

**To Reproduce**
[Gist with `devenv.nix`, `devenv.yaml` and `devenv.lock`](https://gist.github.com/loket/bcddb20e3ec035d83582e945531d65b3)

**Version**
 ```bash
$ devenv version
devenv: 0.5
```

**Comment by domenkozar** [comment]
cc @alejandrosame

**Comment by loket** [comment]
Holy smokes, that was fast! Thanks! 🙂
