### ISSUE TITLE
Scripts with conlicting `bin` from packages installed by `languages.*.enable` won't be available

### ISSUE THREAD

**Issue by terlar** [cachix/devenv#272]
**Describe the bug**
If I'm doing something like this:
```nix
{ config, ... }: {
  languages.javascript.enable = true;
  scripts.npm.exec = ''
    echo Do something fancy...
    ${config.languages.javascript.package}/bin/npm "$@"
  '';
}
```

Then the bin from the package will take precedence over the scripts. Feels like the scripts should take precedence.

**To Reproduce**

devenv.nix:
```nix
{ config, ... }: {
  languages.javascript.enable = true;
  scripts.npm.exec = ''
    echo Do something fancy...
    ${config.languages.javascript.package}/bin/npm "$@"
  '';
}
```

```
$ ls -la (which npm)
lrwxrwxrwx 22 root root 66 jan  1  1970 /nix/store/a1irar8rpq08s0xab1764vd40hi8w01g-devenv-profile/bin/npm -> /nix/store/7ppnyqmp1c92gkfrixbz99sw7q6ifkg1-nodejs-18.12.1/bin/npm*
```

**Version**
 
devenv: 0.5

**Comment by shyim** [comment]
We do the same in MySQL config hmmm https://github.com/cachix/devenv/blob/main/src/modules/services/mysql.nix#L206-L216

**Comment by domenkozar** [comment]
Good catch, see https://github.com/cachix/devenv/pull/274

**Comment by terlar** [comment]
Not sure how this could have been working in the MySQL config (or perhaps it was not). Anyways thank you for the fix! I can confirm that this solves the issue.
