### ISSUE TITLE
devenv mysql multiple user bdd

### ISSUE THREAD

**Issue by Paul75** [cachix/devenv#273]
**Describe the bug**
When I want to create more one of user for my mysql or mariadb it only create the first mentioned on this script : 

```
services.mysql.ensureUsers = [
    {
      name = "emailing";
      password = "PASSWORD1";
      ensurePermissions = { "emailing.*" = "ALL PRIVILEGES"; };
    }
    {
      name = "declaration_simplifiee";
      password = "PASSWORD3";
      ensurePermissions = { "declaration_simplifiee.*" = "ALL PRIVILEGES"; };
    }
  ];
```

It only create 'emailing' and not 'declaration_simplifiee'.

**To Reproduce**
devenv up

**Version**
 
devenv: 0.5

**Comment by domenkozar** [comment]
cc @shyim

**Comment by shyim** [comment]
assign it to me :)

**Comment by Paul75** [comment]
Hello,

I miss declare the name in *services.mysql.initialDatabases* .....

Thanks
