### ISSUE TITLE
devenv breaks when using nix-plugins

### ISSUE THREAD

**Issue by ShaddyDC** [cachix/devenv#276]
**Describe the bug**
Devenv commands fail when [nix-plugins](https://github.com/shlevy/nix-plugins) are enabled.

**To Reproduce**

Having these lines in the system config according to the nix-plugins readme:
```nix
nix.extraOptions = ''
  plugin-files = ${pkgs.nix-plugins}/lib/nix/plugins
'';
```

Then, in an empty directory, run the following:

```bash
devenv init
devenv shell
```

The latter will give an error like this:
```
Building shell ...
error:
       error: could not dynamically open plugin file '/nix/store/6i1k0pp605dgwk3zyvf5adjfr8gzs0ri-nix-plugins-10.0.0/lib/nix/plugins/libnix-extra-builtins.so': /nix/store/6i1k0pp605dgwk3zyvf5adjfr8gzs0ri-nix-plugins-10.0.0/lib/nix/plugins/libnix-extra-builtins.so: undefined symbol: _ZN3nix9EvalState8evalFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_5ValueEb
```

Removing the plugins from the config allows entering the shell again. Readding it rebreaks it. Both with a rebuild, of course.

I'm not sure an sscce is helpful, but if it doesn't reproduce, I can provide one and an updated version of my system configuration.

**Version**
 
`devenv: 0.5`

**Comment by domenkozar** [comment]
We use a custom built Nix, is there a way to make those plugins compatible somehow?

I'd love to fix this, but no idea how. Do you expect devenv just to work or for plugins to be available within?

**Comment by ShaddyDC** [comment]
I use the plugins for something unrelated, so I'd be happy if it just works. I'm provisionally working around it by just temporarily building the system without and enabling again afterwards, but it's of course a bit of a hassle.

**Comment by domenkozar** [comment]
❯ nix --option plugin-files "" build 
warning: error: plugin-files set after plugins were loaded, you may need to move the flag before the subcommand

@shlevy any ideas how to disable plugin-files when invoking Nix?

**Comment by domenkozar** [comment]
Same.

**Comment by shlevy** [comment]
Will take a look

**Comment by shlevy** [comment]
@domenkozar This is fixed in https://github.com/NixOS/nix/pull/7736, but note that even prior to the fix this warning, while misleading, does not actually impede anything. In your command, `plugin-files` are disabled on the client side, the warning comes from the daemon (obviously you can't disable plugin-files for it from the client) but the daemon keeps working even after sending this warning.

**Comment by domenkozar** [comment]
Thanks! I guess we need to add the flag and filter out the useless warning.

**Comment by domenkozar** [comment]
This is fixed in Nix, please reopen if not :)
