### ISSUE TITLE
'command not found' in newly setup environment

### ISSUE THREAD

**Issue by tdeckers** [cachix/devenv#290]
**Describe the bug**
I installed nix for the first time, and worked through the [Getting Started](https://devenv.sh/getting-started/#installation).  After creating a new project directory and running `devenv init` all files get created successfully.  However, running `devenv shell` results in an error:
```
$ devenv shell
Building shell ...
warning: Git tree '/home/tdeckers/git/hello-devenv' is dirty
Entering shell ...

bash: hello: command not found
git version 2.38.1
```
The `hello` command is not found.  I believe this is because initially following lines are commented out in `devenv.nix`:
```
# https://devenv.sh/scripts/
# scripts.hello.exec = "echo hello from $GREET";
```
After uncommenting that second line the error goes away. It would be cleaner for new installs (and confuse less new users) if above line is uncommented by default so that the error doesn't show up.

**To Reproduce**
Follow the steps in [Getting Started](https://devenv.sh/getting-started/#installation).  Then run `devenv shell`.

**Version**
 
[Paste here the output of `$ devenv version`.](devenv: 0.5)

**Comment by domenkozar** [comment]
This was fixed in master, but needs a release of devenv.

**Comment by domenkozar** [comment]
Released
