### ISSUE TITLE
devcontainer not working if defined as a flake

### ISSUE THREAD

**Issue by yajo** [cachix/devenv#300]
**Describe the bug**
`nix develop` yields this error: `bash: /.devcontainer.json: Operation not permitted`

**To Reproduce**

1. Download [example.zip](https://github.com/cachix/devenv/files/10425805/example.zip)
2. Unzip.
3. `cd` into it
4. Run `nix develop`

**Version**
 
818abeae2dd2f4911839a079e5c8934fee160a60

**Comment by domenkozar** [comment]
Did you run `nix develop --impure`?

**Comment by yajo** [comment]
oh it works if I pass `--impure`, indeed! Thanks!
