### ISSUE TITLE
(micro)mamba activation support

### ISSUE THREAD

**Issue by kai-tub** [cachix/devenv#321]
Disclaimer: I think it is technically not a _bug_ of _devenv_ but I would like to open up the discussion in general and maybe there is a way how _devenv_ can work around this issue.

**Describe the bug**
I would like to provide a `devshell` that configures a `micromamba` Python environment.
This is especially relevant for any DL/data science development in Python.
The conda/mamba tools are quite popular as they allow one to simply _download_ binaries from pre-defined channels, apply constraint solving, and quickly get everything up and running.
I would like to avoid the discussion about using _nix_ to resolve those dependencies, as this is (at least as of now) unrealistic, as I would argue that the _nix_ Python ecosystem is focused on creating _end-applications_ and not as much as creating constraints to generate many different environments given additional constraints down the line.

I would like to re-create this setup process with `devshell`.
The relevant section is from https://nixos.wiki/wiki/Python#micromamba.
It is _easy_ to create the environment with `devshell` as executing the micromamba commands is independent of the created environment, but if one wants to _enable_ the environment, one has to rely on `FHS` as shown in the wiki.

My idea is to use `buildFHSUserEnv` to generate an environment and then to _activate_ it via a specific shell/script command.
Something, like this:

```nix
{ pkgs, config, ... }:

let
  fhs = pkgs.buildFHSUserEnv {
    name = "fhs-env";
    profile = ''
      set -e
      SHELL=/bin/bash eval "$(micromamba shell hook --shell=bash)"
      set +e
    '';
    targetPkgs = pkgs: [ pkgs.coreutils pkgs.micromamba ];
  };
in
{
  env.MAMBA_ROOT_PREFIX = "${config.env.DEVENV_STATE}/micromamba";
  packages = [ pkgs.git pkgs.micromamba pkgs.file ];

  enterShell = ''
    micromamba --version
  '';

  scripts.env.exec = "exec ${fhs}/bin/fhs-env";
}

I _think_ this might be related to:
- https://github.com/NixOS/nix/issues/6091
- Might already be _fixed_ in master with https://github.com/NixOS/nix/pull/7010

```

**To Reproduce**
https://gist.github.com/kai-tub/920146ed4e990d5493086022427bd836

**Version**
 devenv: 0.5

**Comment by domenkozar** [comment]
The following seems to work:

```nix
{ pkgs, config, ... }:

{
  env.MAMBA_ROOT_PREFIX = "${config.env.DEVENV_STATE}/micromamba";

  packages = [ pkgs.git pkgs.micromamba pkgs.file ];

  enterShell = ''
    micromamba --version
    eval "$(micromamba shell hook --shell=bash)"
  '';
}
```

**Comment by kai-tub** [comment]
Thank you for responding so quickly!

Hm... It doesn't work for me.
I should've better specified how the 'error appears' sorry for that.
When I open the environment, I get the error `./.envrc:250: complete: command not found`
`complete` is called within the `eval` part of the script.
As far as I understand it, this is due to `nix develop` using `bash stdout` mode (?) and not having any interactive features, such as `complete` available.
The shell will still load but it isn't possible to activate an environment with
`micromamba activate`

I get the message:

```bash
'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

    To initialize the current fish shell, run:
        $ eval "$(micromamba shell hook --shell=fish)"
    and then activate or deactivate with:
        $ micromamba activate

To automatically initialize all future (fish) shells, run:
    $ micromamba shell init --shell=fish --prefix=~/micromamba

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.

critical libmamba Shell not initialized
```

Which is the same error if you "forget" to evaluate the hooks.

**Comment by domenkozar** [comment]
With the following devenv.nix I can run `micromamba activate`:

```
{ pkgs, config, ... }:

{
  env.MAMBA_ROOT_PREFIX = "${config.env.DEVENV_STATE}/micromamba";

  packages = [ pkgs.git pkgs.micromamba pkgs.file ];

  enterShell = ''
    micromamba --version
    set -h
    eval "$(micromamba shell hook --shell=bash)"
  '';
}
```

**Comment by kai-tub** [comment]
Ok, when I am starting it via `devenv shell` it works.
I am using `direnv` with a fish shell and that doesn't work as expected...
Do you happen to know how I can debug this issue?

I am still quite new to nix and this project is amazing in allowing me to get started and familiar with nix :)
Thank you for that!

**Comment by kai-tub** [comment]
I see, thanks!
