### ISSUE TITLE
elixir using latin1 locale instead of utf8 even with glibcLocales

### ISSUE THREAD

**Issue by pikdum** [cachix/devenv#353]
**Describe the bug**

In a fresh project with only `pkgs.glibcLocales` and elixir enabled , running `iex` warns about using latin1 instead of utf8:

```console
$ iex --version
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
IEx 1.14.3 (compiled with Erlang/OTP 25)
```

This works in an older project I have though, so I'll attach two gists only differing by the `devenv.lock`.

Guessing something changed between `nixos-22.05` and `nixos-22.11`?
Not sure how to fix on my end other than modifying the `devenv.lock`, though.

**To Reproduce**

Broken:  https://gist.github.com/pikdum/93a1df7ca19392d7c0dc3092064e5883
Working: https://gist.github.com/pikdum/2e1d311de30f8ce5879dc5989dc917c6

**Version**
 
```console
$ devenv version
devenv: 0.5.1
```

**Comment by sandydoo** [comment]
@pikdum, what does `locale` output when you run it in your shell?

**Comment by pikdum** [comment]
```console
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by sandydoo** [comment]
Weird! Your "broken" gist works fine on my machine. And your locales don't look out of the ordinary either.
What does `echo $LOCALE_ARCHIVE` say?

**Comment by pikdum** [comment]
Looks unset.

```shell
$ echo $LOCALE_ARCHIVE                                      
 
```

**Comment by sandydoo** [comment]
Interesting! Last idea: what if you set `LOCALE_ARCHIVE` to the archive provided by `glibcLocales`?

```nix
{ pkgs, ... }:
{
  packages = [ pkgs.glibcLocales ];
  languages.elixir.enable = true;

  env = {
    LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
  };
}
```

**Comment by pikdum** [comment]
Neat, looks like that fixes it:

```console
$ iex --version
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

IEx 1.14.3 (compiled with Erlang/OTP 25)
```

**Comment by sandydoo** [comment]
What distro are you using by the way?

**Comment by pikdum** [comment]
Pop!_OS 22.04

**Comment by sandydoo** [comment]
@domenkozar, should we check `$LOCALE_ARCHIVE` and friends when launching the shell? NixOS sets this by default, but we might see weirdness like this in other distros.

I imagine `glibcLocalesUtf8` is a smaller closure:
```bash
export LOCALE_ARCHIVE="${pkgs.glibcLocalesUtf8}/lib/locale/locale-archive"
```

**Comment by domenkozar** [comment]
3MB, let's just add those by default!

**Comment by sandydoo** [comment]
### glibc and locales
Source: https://nixos.org/manual/nixpkgs/stable/#locales

> To allow simultaneous use of packages linked against different versions of glibc with different locale archive formats, Nixpkgs patches glibc to rely on LOCALE_ARCHIVE environment variable.
>
> On non-NixOS distributions, this variable is obviously not set. This can cause regressions in language support or even crashes in some Nixpkgs-provided programs. The simplest way to mitigate this problem is exporting the LOCALE_ARCHIVE variable pointing to ${glibcLocales}/lib/locale/locale-archive. The drawback (and the reason this is not the default) is the relatively large (a hundred MiB) size of the full set of locales. It is possible to build a custom set of locales by overriding parameters allLocales and locales of the package. 


### Locales on non-NixOS hosts
Source: https://nixos.wiki/wiki/Locales

> You may need to set the environmental variable LOCALE_ARCHIVE to point to your system's locale-achive. The following can be added to your .zshenv (zsh) or .profile (bash) and applies to Debian, Red Hat, and Arch derivatives:
> ```bash
> export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive
> ```
