### ISSUE TITLE
Putting devenv in nixpkgs?

### ISSUE THREAD

**Issue by DamienCassou** [cachix/devenv#362]
According to [install documentation](https://devenv.sh/getting-started/#installation), the "Advanced (declaratively without flakes)" way to install devenv is:

```nix
{
  environment.systemPackages = [ 
    (import (fetchTarball https://github.com/cachix/devenv/archive/v0.5.1.tar.gz)).default
  ];
}
```

I'm wondering why devenv is not in nixpkgs? This would make updates automatic instead of relying on users to regularly change their configuration.

**Comment by domenkozar** [comment]
Putting devenv to nixpkgs is tricky, because we have a lot of Nix code that would have to be copied to nixpkgs.

Since it's in rapid development it wouldn't make sense to maintain it there, so for now this is the best way to handle it.

**Comment by domenkozar** [comment]
I've been thinking about this, most likely we can solve this by implementing #117, so that devenv becomes a very thin wrapper.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/297714 done!
