### ISSUE TITLE
Enabling poetry causes a deprecation traceback

### ISSUE THREAD

**Issue by arjan-s** [cachix/devenv#378]
**Describe the bug**
Enabling `poetry` causes a traceback:
```
direnv: loading /tmp/test/.envrc
Building shell ...
warning: applying 'toString' to path '«github:cachix/devenv/346d49568b72b1889024d5f9569d777d83adb93f»/src/modules/languages/python.nix' and then accessing it is deprecated, at «stdin»:0
... snipped traceback ...
error: poetry was promoted to a top-level attribute, use poetry-core to build Python packages
```

**To Reproduce**
- Download https://github.com/cachix/devenv/tree/main/examples/python-poetry
- `cd python-poetry`
- `devenv shell`

**Version**
 
`devenv: 0.5.1`

**Comment by domenkozar** [comment]
This should be fixed by bumping Nix.

**Comment by arjan-s** [comment]
Sorry, but is that something I should do? I currently have nix 2.13.2 from nixpkgs-unstable. Or is this something that needs to be fixed in devenv?

**Comment by domenkozar** [comment]
That's to be fixed in devenv, hoping to release 0.6 with these fixes soon :)

**Comment by arjan-s** [comment]
Awesome, thanks!

**Comment by domenkozar** [comment]
Fixed in main
