### ISSUE TITLE
Add newline character to auto-generated devenv.yaml last line

### ISSUE THREAD

**Issue by lanquil** [cachix/devenv#384]
I propose to add a newline character at the end of the auto-generated `devenv.yaml` last line, since a widely used editorconfig configuration is `insert_final_newline = true`.

**Comment by domenkozar** [comment]
Happy to accept a PR, it's in examples/simple/devenv.yaml

**Comment by lanquil** [comment]
I'm late! This was already fixed in https://github.com/cachix/devenv/commit/0787033062e5eb4f5cdc572043cd306f6ca95ed8#diff-9fee3e774ab2cd312c4dbdf2ac8df70c19335051ea98e2578675ce42abc0b066 :1st_place_medal:
