### ISSUE TITLE
Interop between devenv and https://github.com/numtide/devshell

### ISSUE THREAD

**Issue by adrian-gierakowski** [cachix/devenv#386]
I see useful things in both projects.

 Devshell is [extensible](https://github.com/numtide/devshell/blob/main/docs/extending.md) and there exist various 3rd party modules (like https://github.com/cruel-intentions/devshell-files). 

Is there a clean way to leverage both projects (and their extensions) together?

**Comment by adrian-gierakowski** [comment]
I just joined the discord and found [this](https://discord.com/channels/1036369714731036712/1036369758024650792/1058867172149039124)

In which case it would be great if there was a guide on how to use devshell modules with devenv (or how to migrate them)

**Comment by hugosenari** [comment]
I wish I could open discord to read that 😉

**Comment by domenkozar** [comment]
See https://github.com/cachix/devenv/pull/142

**Comment by domenkozar** [comment]
For the extending guide see https://github.com/cachix/devenv/issues/340

I've been talking to @zimbatm to decide the fate of devshell, currently leaning towards devenv as the successor.

I'm going to close this as I think it's best to talk about specific problems in respective issues
