### ISSUE TITLE
No documentation for the `.pre-commit-config.yaml` file

### ISSUE THREAD

**Issue by a12l** [cachix/devenv#390]
**Describe the bug**

Can't find any documentation about the `.pre-commit-config.yaml` file that's created .e.g. when using the Rust example.

**To Reproduce**

1. Run `devenv init`
2. Replace the files that have corresponding files in the Rust example, located at https://github.com/cachix/devenv/tree/main/examples/rust
3. Run `devenv shell`
4. See the file `.pre-commit-config.yaml` having been created.
5. Try to find information about that file on devenv.sh.

**Version**
 
```
$ devenv version
devenv: 0.5.1
```

**Comment by shyim** [comment]
Hey,

you can find it here. https://devenv.sh/pre-commit-hooks/ . Setting that configuration auto generates that file

**Comment by a12l** [comment]
> you can find it here. https://devenv.sh/pre-commit-hooks/ . 

I can't find any mention of `.pre-commit-config.yaml`?

> Setting that configuration auto generates that file

I concluded that, but it isn't mentioned in the list of files generated by devenv. Should it be committed as part of the repo?

**Comment by sabitm** [comment]
ps: I'm super newbie in regards of nix and its ecosystem.

Is there any way to change this `.pre-commit-config.yaml` file content? I could see that the hash inside the file is changing whenever I change `devenv.nix` (or creating derivatives). What is the best way to do it? (If anyone could point me to the nix basics of changing the content of file from `/nix/store`, it would be great!)
