### ISSUE TITLE
Add support for OpenSearch (elasticsearch fork)

### ISSUE THREAD

**Issue by fballiano** [cachix/devenv#407]
Since https://github.com/NixOS/nixpkgs/pull/175000 has been merged I think it could be possible to have support for opensearch in devenv.

I've no idea how to develop it and test it but it should be somehow similar to https://github.com/cachix/devenv/blob/main/src/modules/services/elasticsearch.nix

CCing @shyim since he's the author of https://github.com/NixOS/nixpkgs/pull/175000

**Comment by shyim** [comment]
We don't need to do anything. Just throw into `services.elasticsearch.package = pkgs.opensearch` and it works :)

**Comment by shyim** [comment]
see https://github.com/cachix/devenv/blob/main/src/modules/services/elasticsearch.nix#L41-L43 we set both vars

**Comment by fballiano** [comment]
thanks @shyim!

If I add:
```
  services.elasticsearch.enable = true;
  services.elasticsearch.package = pkgs.opensearch;
```

to my `devenv.nix` and then run `devenv up` I get:
```
       error: attribute 'opensearch' missing
```

but it's probably something I'm doing wrong when upgrading nix

**Comment by shyim** [comment]
You have to wait 1-2 days. see https://status.nixos.org/ then `devenv update` and it should work

**Comment by shyim** [comment]
I am thinking about creating a opensearch flake with all versions

**Comment by shyim** [comment]
See example in the readme to use it right now: https://github.com/shyim/opensearch-nix

**Comment by fballiano** [comment]
Thanks @shyim, it works :-)

**Comment by shyim** [comment]
It's now in unstable you don't need the flake anymore :)

**Comment by domenkozar** [comment]
Would be cool to add it to the option docs.

**Comment by shyim** [comment]
Or we create a second module `opensearch` like in nixos itself. 🤔 . We can adopt also that settings stuff all
