### ISSUE TITLE
Enabling Swift breaks C compilation

### ISSUE THREAD

**Issue by hauleth** [cachix/devenv#409]
**Describe the bug**

When `languages.swift.enable = true` is set the `$CC` value is set to the Clang *directory* instead of `cc` *executable*. This causes for example `cargo build` to fail, as it expects the `$CC` to be path to `cc` executable.

**To Reproduce**

https://gist.github.com/hauleth/0a8cf6a41b0fd075fe51bfa8c3538f34

And inside of the `nix develop` run `make`.

It fails, because it cannot execute directory (no surprise) as `cc` compiler.

**Version**
 
I use Flaked version pinned at 584d63e93a841148f75b3b9ec2cfed2ed08c760f

**Comment by domenkozar** [comment]
Does it work if you do add:

```
env.CC = lib.mkForce "${pkgs.clang}/bin/clang";
``

**Comment by hauleth** [comment]
I did it in `.envrc`, but yes, then it works. It works even with just `env.CC = lib.mkForce "cc";` (at least on macOS).
