### ISSUE TITLE
Feature request: git hooks (other than pre-commit)

### ISSUE THREAD

**Issue by terlar** [cachix/devenv#426]
I know devenv already supports pre-commit hooks which is probably the most used hook, but it would be nice to be able to define other git hooks such as `prepare-commit-msg`. Probably something similar to what `devshell` is doing without conflicting with `pre-commit`:
https://numtide.github.io/devshell/modules_schema.html#githooksenable

**Comment by domenkozar** [comment]
Refs https://github.com/cachix/pre-commit-hooks.nix/issues/196#issue-1463353799

**Comment by terlar** [comment]
Okay, after some digging into `pre-commit` it seems it was already possible to do these kind of things, I managed to do it like this:
```
    pre-commit.hooks.prepare-commit-msg-inject-issue-id = {
      enable = true;
      name = "prepare-commit-msg-inject-issue-id";
      entry = "${config.packages.prepare-commit-msg-inject-issue-id}/bin/inject-issue-id";
      stages = ["prepare-commit-msg"];
    };
```
