### ISSUE TITLE
How to uninstall (macOS)

### ISSUE THREAD

**Issue by Vandaahl** [cachix/devenv#433]
As far as I can tell, there is no documentation on how to uninstall devenv. How is this done?

**Comment by domenkozar** [comment]
`nix-env -e devenv` or `nix profile list` and `nix profile remove <number>`.

**Comment by shyim** [comment]
Also deleting `rm -rf $HOME/.devenv` + maybe running a `nix-collect-garbage -d`

**Comment by Vandaahl** [comment]
Thanks guys.
