### ISSUE TITLE
Silent/Quiet option when opening a new terminal

### ISSUE THREAD

**Issue by jgoux** [cachix/devenv#435]
Hello 👋, very excited about this project!

Could we add an ENV variable or an option to suppress the `Building shell ...` and other progress reports when opening a new terminal? Ideally, I'd like to only see errors reported.

The related code seems here: https://github.com/cachix/devenv/blob/1aa3dbbf745f50e77aadc016d124fed3ca2dc9be/src/devenv.nix#L59-L65

**Comment by domenkozar** [comment]
Sounds good! I'd like to refactor the argument parsing by using docopts, so things like this will be possible.

**Comment by alicebob** [comment]
This would also be nice for github actions. Mine get multiple `devenv shell` statements, which don't need the devenv output:
```
    - name: Test formatting
      run: devenv shell test -z '$(go fmt ./...)'
    - name: Run tests
      run: devenv shell make citest
```

(`-quiet` or similar woud work great for my use case)
