### ISSUE TITLE
devenv: 14: function: not found after update to v0.6 with zsh

### ISSUE THREAD

**Issue by tenpaiyomi** [cachix/devenv#449]
**Describe the bug**
After updating to v0.6, I can no longer run any devenv commands due to the following error:

```
➜ devenv version
/home/eric/.nix-profile/bin/devenv: 14: function: not found
➜ bash
$ devenv version
devenv: 0.6
```

**To Reproduce**
Simply upgraded to v0.6 while using zsh

**Version**
 v0.6

**Comment by shyim** [comment]
Can you tag a release the PR is merged :)

**Comment by domenkozar** [comment]
Released!
