### ISSUE TITLE
print-dev-env takes over 20 seconds

### ISSUE THREAD

**Issue by vHanda** [cachix/devenv#476]
After upgrading from devenv 0.5 to 0.6 (and now 0.6.2), `devenv print-dev-env` which is used by direnv takes too long. With version 0.6 it was taking some 20 seconds, but 0.6.2 seems to often take some 50 seconds.

With version 0.5 it was less than a second.

**To Reproduce**
devenv.nix - https://gist.github.com/vHanda/b59f0eaebfee3f0c8b66fb644ce2be02
devenv.yaml - https://gist.github.com/vHanda/1465594bc9ccb442e06b83f7380bdc2f
devenv.lock - https://gist.github.com/vHanda/3ba3ba920ef9468d1ba3f7a38dbfb5a2
**Version**
 
devenv: 0.6.2

I'm running this on macbook air m2.

```
$ time devenv print-dev-env &> /dev/null

________________________________________________________
Executed in   53.11 secs    fish           external
   usr time    1.82 secs   69.00 micros    1.82 secs
   sys time    0.57 secs  963.00 micros    0.57 secs
```

**Comment by domenkozar** [comment]
Is this on a fresh occasion (where it downloads all the tools) or after it has been run for the first time?

**Comment by domenkozar** [comment]
The first invocation took 50s because it downloads 1.9GB of tooling, but the second one is:

```
❯ time devenv print-dev-env &> /dev/null

real	0m1.252s
user	0m0.817s
sys	0m0.203s
```

**Comment by vHanda** [comment]
For me this happens everytime. Any way I can provide additional info?

**Comment by domenkozar** [comment]
`du -sh` in your repo

**Comment by vHanda** [comment]
I had to restart my machine for some updates, and now it's no longer occurring.

Not sure what was going on, but I can no longer reproduce it. Closing this.
