### ISSUE TITLE
Documentation settings list has numbers in it

### ISSUE THREAD

**Issue by M-arcus** [cachix/devenv#477]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25648755/224252265-b65cb4fc-7382-4e4d-ab71-3ff0a39251a7.png)

**To Reproduce**
https://devenv.sh/reference/options/

**Version**
![image](https://user-images.githubusercontent.com/25648755/224252339-c6859600-6fba-4382-9490-52c2904158b7.png)

**Comment by domenkozar** [comment]
cc @sandydoo

**Comment by sandydoo** [comment]
@domenkozar, it looks correct when I run the docs locally. There was a plugin I added to escape those carets correctly. Maybe the docs site needs to be updated manually?

**Comment by sandydoo** [comment]
Deployed to cloudflare to mimic the production setup. LGTM: https://devenv.sandydoo.me/reference/options/index.html

**Comment by montchr** [comment]
Any update on timeline? It's pretty difficult to use the reference documentation in its current state because of this.

**Comment by montchr** [comment]
As a per-session workaround, I can run the following in browser console to make things readable:

```js
document.querySelectorAll('.md-ellipsis').forEach((el) => {
  const text = el.innerHTML
    el.innerHTML = text.replaceAll(/.46./g, '.')
})
```
