### ISSUE TITLE
mysql/mariadb error SQL when in password get '-'

### ISSUE THREAD

**Issue by Paul75** [cachix/devenv#483]
**Describe the bug**

**To Reproduce**

In devenv.sh : 
[code in github gist](https://gist.github.com/Paul75/c4f4ca88e53e1f4a89ad3620b49a442c)

after do devenv up and get error : 

```
13:11:44 mysql-configure.1 | mysqld is alive
13:11:44 mysql-configure.1 | Creating initial database: sl-outil
13:11:44 mysql-configure.1 | Adding user: sl-outil
13:11:44 mysql-configure.1 | ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-outil.* TO 'sl-outil'@'localhost'' at line 1
```

**Version**
 

0.6.2

**Comment by domenkozar** [comment]
cc @shyim

**Comment by shyim** [comment]
assign it to me :)

**Comment by Paul75** [comment]
20:09:55 mysql-configure.1 | mysqld is alive
20:09:55 mysql-configure.1 | Creating initial database: sl-outil
20:09:55 mysql-configure.1 | Adding user: sl-outil
20:09:55 mysql-configure.1 | ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''sl-outil'.* TO 'sl-outil'@'localhost'' at line 1
