### ISSUE TITLE
/home/user/.nix-profile/bin/devenv: line 239: $'\r': command not found

### ISSUE THREAD

**Issue by Juhlinus** [cachix/devenv#488]
A colleague is getting this error on WSL when running `devenv up`. Some issue with line breaks seemingly.

cc: @Mathewlenning

**Comment by adrian-gierakowski** [comment]
Most likely they checked out the code on windows side with git client which is configured to covert line endings from Linux to Windows. See [here](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-line-endings) for a fix. Not really a devenv problem
