### ISSUE TITLE
Emacs unable to find devenv packages

### ISSUE THREAD

**Issue by ankhers** [cachix/devenv#49]
I am really unsure if this is an issues of emacs or how devenv sets up packages. I am filing a ticket here because this is the first time I have actually had issues with it.

Essentially, I am starting a fresh project and using `devenv init` in order to start. I then enable `languages.elixir`, which supports the `elixir_ls` package. When I `direnv allow`, I get sent to a dev shell. I can then see that the `elixir-ls` binary and `elixir` packages are available. However when I use emacs to start editing the project, it cannot find the `elixir-ls` binary, and when I manually execute a shell command for `elixir --version`, I can see I am using my host elixir version instead of the newer version that was supplied by `devenv`. 

I am really unsure of how to debug this kind of thing. But let me know what you need from me and I can do it.

**Comment by domenkozar** [comment]
Are you launching emacs from the developer environment?

**Comment by ankhers** [comment]
https://github.com/ankhers/devenv-emacs

This is literally a brand new project

1. `$ mix new foo`
2. `$ devenv init`
3. enable elixir language

**Comment by domenkozar** [comment]
@ankhers and then you run ``devenv shell`` and inside emacs?

**Comment by ankhers** [comment]
I'm sorry, I forgot to include the `.envrc` file in that git repo. I just pushed it up. Direnv automatically calls `devenv shell` for me when I am in the shell and `cd` into the project. 

Emacs I do not start within the `devenv shell`. I start emacs server globally with a systemd unit. I use the [`envrc`](https://github.com/purcell/envrc) emacs package to get direnv support.

When I open the previously linked project in emacs, I see that it is evaluating the .envrc file but then it fails to find the `elixir-ls` binary in my path.

If I open [this](https://github.com/ankhers/emacs-direnv-working) project in emacs, it is able to find the package.

**Comment by ankhers** [comment]
I just installed devenv 0.4, and this seems to have resolved itself.
