### ISSUE TITLE
Set subset of setup-hook provided env vars automatically, like NIX_CFLAGS_COMPILE

### ISSUE THREAD

**Issue by thenonameguy** [cachix/devenv#497]
**Describe the bug**
Thanks to #191, we are not using the Nix build system's setup-hook mechanism anymore.
This gives us faster devenv evaluation, but comes with the tradeoff that certain compilation-specific implementation details are not carried over.

One of these is the C-compiler flags that are passed down through env vars to the Nix-provided GCC/Clang stdenv compilers, that are non-standard. This leads to issues like #267 and #258.

It seems we need to find a middle-ground between naked shell and the plain `nix-shell` to have a better out-of-the-box experience for compiling things within a `devenv shell`.

See description of how the normal compilation workflow is extended:
https://nixos.wiki/wiki/C

Some research was made here:
- https://github.com/cachix/devenv/issues/267#issuecomment-1473510291
- https://github.com/cachix/devenv/issues/267#issuecomment-1473515745

**Comment by thenonameguy** [comment]
As a middle-ground I'll create an option to switch between using naked shell vs `nix-shell`-like behavior and turn naked shell off  for the language modules that commonly invoke a C compiler (C-like langs, Rust, Ruby). Should fix most of the woes related to the issue.

**Comment by domenkozar** [comment]
Could we just source some of the needed setup-hooks instead all of them?

**Comment by thenonameguy** [comment]
> Could we just source some of the needed setup-hooks instead all of them?

Deciding that would be:
1. pkg setup-hook dependent, usually they contain a single setup hook that does multiple things
2. while also depending on the given nixpkgs commit, as the setup-hooks evolve over time

Therefore deciding to which setup hooks to source is too cumbersome. We could run them regardless and keep a subset of the env vars `NIX_.*`, etc. to be a bit more safe.

**Comment by domenkozar** [comment]
This is fixed in #745

**Comment by thenonameguy** [comment]
Closing as the 1.0 major version fixed this for the most part.
