### ISSUE TITLE
`devenv build-image`

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#5]
Build containers based on `processes` specification and https://github.com/nlewo/nix2container

**Comment by asymmetric** [comment]
@domenkozar why does this rely on nix2container instead of `pkgs.dockerTools`?

**Comment by domenkozar** [comment]
It's a lot faster to compute the image if you can just stream it to docker.

**Comment by asymmetric** [comment]
Got it. I do wonder if it's worth the additional dependency on a third-party repo maintained by just one person though.

Is the speedup/slowdown actually affecting people? For my workflows, generating a container is something I do rarely (before deployment), not part of the dev workflow, so personally not that concerned.
