### ISSUE TITLE
Integrate mkdocs-linkcheck

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#50]
https://pypi.org/project/mkdocs-linkcheck/

**Comment by totoroot** [comment]
@domenkozar I'll created a draft [here](https://github.com/cachix/pre-commit-hooks.nix/pull/326).
If I understand it correctly, there should be no code change necessary in this repo once the PR gets merged into pre-commit-hooks.nix, right?

**Comment by domenkozar** [comment]
We'd want to run the hook in the repo, to validate all the doc links

**Comment by totoroot** [comment]
I'd suggest we use `lychee`, which is more performant and seems to be maintained better.
It was added as a hook with https://github.com/cachix/pre-commit-hooks.nix/pull/351.
If nothing speaks against it, I can open a PR to integrate it into the devenv repo.

**Comment by domenkozar** [comment]
That would be fantastic, please do :)

**Comment by totoroot** [comment]
See relevant work by @roberth in https://github.com/NixOS/nixpkgs/pull/298665.
