### ISSUE TITLE
Can't use devenv on linux with musl

### ISSUE THREAD

**Issue by aaronmondal** [cachix/devenv#515]
**Describe the bug**

The following lines prevent devenv from building with the musl package set:

https://github.com/cachix/devenv/blob/52232ba41b7c531eacec4cf192d87241bef1a0d1/src/modules/top-level.nix#L114-L119

Removing above lines seems to work (https://github.com/aaronmondal/devenv/pull/1) , but that's probably not the right way to fix this 😅

**To Reproduce**

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
    devenv.url = "github:cachix/devenv";
  };

  outputs = { self, nixpkgs, devenv, ... } @ inputs:

  let
    pkgs = (import nixpkgs { system = "x86_64-linux"; }).pkgsMusl;
  in
  {
    devShells.x86_64-linux = {
      default = devenv.lib.mkShell {
        inherit inputs pkgs;

        modules = [];
      };
    };
  };
}
```

```log
error: cannot coerce null to a string

       at /nix/store/warvqnsjc02awzvgyr58q4v08303a6b3-source/src/modules/top-level.nix
:117:33:

          116|         if [ -z "''${LOCALE_ARCHIVE-}" ]; then
          117|           export LOCALE_ARCHIVE=${pkgs.glibcLocalesUtf8}/lib/locale/loc
ale-archive
             |                                 ^
          118|         fi
```

**Version**
 
nix version 2.13.3

**Comment by domenkozar** [comment]
I wonder if there is such thing as the locale on musl?

**Comment by aaronmondal** [comment]
Wow that was fast! Thanks a lot!

I also wondered how locale handling works with Musl. I still don't know, but I'm sure as more users will switch to Musl in the (probably still far) future, these things will become clearer to everyone 😅
