### ISSUE TITLE
Starship not working on mac

### ISSUE THREAD

**Issue by mrfelton** [cachix/devenv#525]
Enabling starship doesn't work. I see the following error on the console when starting devenv (through direnv):
 
> /dev/stdin:69: preexec_functions: unbound variable

**To Reproduce**
Set `starship.enable = true;` in `devenv.nix`

**Version**
devenv: 0.6.2

**Comment by mbrasch** [comment]
It works for me.

devenv 0.6.2
nix 2.13.3 (via alternative installer from Determinate Systems)
macOS 13.3.1 aarch64

If anyone has any ideas how to get to the bottom of this....

**Comment by sandydoo** [comment]
Confirmed working.

- aarch64-darwin
- devenv 0.6.2
- nixpkgs@9f7d9a55cc9960c029b006444e64e8dfa54a578e

@mrfelton, are you using https://github.com/rcaloras/bash-preexec by any chance? The variable `preexec_functions` is related to that project.

**Comment by mrfelton** [comment]
I am using iterm2 which according to the link you sent, implies that I may be using that.

**Comment by domenkozar** [comment]
Reported as it works, please report if anyone else has issues with it.

**Comment by bestlem** [comment]
Not working on macOS

I do have iTerm but failed on Terminal.apop and iTerm.app

aarch64-darwin
devenv 0.6.2
nix 2.18.1 (via alternative installer from Determinate Systems)
