### ISSUE TITLE
docker-in-docker fails to install with error

### ISSUE THREAD

**Issue by dzmitry-lahoda** [cachix/devenv#526]
https://github.com/cachix/devenv/blob/e639583e5974e1d0f58ac110356f7f182d6f6004/devcontainer/Dockerfile#L1

```
  "features": {    
    "ghcr.io/devcontainers/features/docker-in-docker:2": {
      "installDockerBuildx" : false,
      "moby": false,
      "installDockerBuildx" : true
    }
  }
```

imho seems better base image on debian for codespace with which microsoft tests end to end. basically codespace initiative  non composable garbage if you are not going mainstream.

**Comment by edulix** [comment]
@dzmitry-lahoda did you solve this issue? How? I'm trying to use `docker-in-docker` but the feature install fails just like you said, and `docker-outside-of-docker` has this issue https://github.com/devcontainers/features/issues/171 so I'm a bit stuck.

**Comment by dzmitry-lahoda** [comment]
you can check this https://github.com/NixOS/nix/issues/6680 . 

people claimed it is solved - i do not trust them. they added nix with single package but not ecosystem. 

ecosystem when i just shell into  codespace

so i did it 
https://github.com/ComposableFi/composable/blob/main/Dockerfile

https://github.com/ComposableFi/composable/blob/main/.devcontainer.json

idea is to setup home manager in docker

the only issue i did not fixed nicely, at least I think, I had to hardcode some ENV vars into docker, while they must be in home manager. ufortunately home manager has ugly situation reagrding env vars

https://github.com/ComposableFi/composable/blob/d784d7600802f1c523bf55bb4502013ace79585d/Dockerfile#L72

but other than that - it works perfect.

**Comment by dzmitry-lahoda** [comment]
i am not expert and cannot fix it consistently, 

MS does iditiotic things to nix and claims it is right.


devevn is cool, but I am not so cool. 

home manager ENV vars is weird.

so kind of sure, nice solution exsits, but given MS agains it - which is super clear after answers from 3 codespaces devs - i doubt solution would be ever nice until they will be aligend.
