### ISSUE TITLE
rust: allow adding more targets

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#530]
I want to compile from mac a arm64 binary. Therefore we need to add a option to allow more targets. This seems to be possible with fenix and I have no glue how to configure this.

**Comment by zoechi** [comment]
I want to compile `wasm32-unknown-unknown"

**Comment by domenkozar** [comment]
See https://github.com/cachix/devenv/pull/900

**Comment by MForster** [comment]
> I want to compile `wasm32-unknown-unknown`

FWIW, this workaround seems to work for me:

```nix
{ pkgs, fenix, ... }: {
  languages.rust = let ff = fenix.packages.x86_64-linux; in {
    enable = true;
    channel = "nightly";
    toolchain.rustc = ff.combine [
      ff.minimal.rustc
      ff.targets.wasm32-unknown-unknown.latest.rust-std
    ];
  };
  # ...
}

**Comment by domenkozar** [comment]
Example is now on devenv.sh :)
