### ISSUE TITLE
`devenv init` overwrites existing .envrc unconditionally

### ISSUE THREAD

**Issue by mkhl** [cachix/devenv#55]
not sure what to add. i ran `direnv init` in a directory with an existing `.envrc` file, and it overwrote its contents without asking. i had to restore them from backup.

**Comment by domenkozar** [comment]
What kind of behavior would you expect?

**Comment by mkhl** [comment]
any of:
* leaving the file alone and warning me about it
* appending its code to the file
* renaming the existing file before creating its own one
* asking what to do
