### ISSUE TITLE
postgres does not work because /.devenv does not exist

### ISSUE THREAD

**Issue by matthiasbeyer** [cachix/devenv#550]
**Describe the bug**
When I enable postgres via `services.postgresql.enable = true;`, I cannot `pg_start` the database because `/.devenv` does not exist on my system (and I guess it also should not).

**To reproduce**
Use default devenv setup and enable postgres as described above. Don't have `/.devenv` on your system when you do.

**Version**
 
0.6.2

**Comment by domenkozar** [comment]
How did you run devenv?

**Comment by matthiasbeyer** [comment]
IIRC by adding the devenv in my flake as `devShells.default`...

**Comment by domenkozar** [comment]
You need to invoke `nix develop --impure` for devenv to work.
