### ISSUE TITLE
[Feature Request:] Overriding the stdenv not yet possible

### ISSUE THREAD

**Issue by 573** [cachix/devenv#567]
**Describe the bug**
Currently it is not easily possible to override the stdenv, i. e. to compile to certain targets in rust / cargo.

**To reproduce**
See [sscce for this issue](https://gist.github.com/573/94eb6c9cc8b65dc29cc3f5bfe142b787).

**Version**
 
>devenv: 0.6.2

**Comment by domenkozar** [comment]
We're getting closer to fixing this, I'm not sure if overriding makes sense for the whole devenv but rather than parts of it?

**Comment by domenkozar** [comment]
For Rust see #900 

Otherwise I'd suggest we add an option to `devenv.yaml`:

```yaml
stdenv: pkgs.swift.stdenv
```

Would that work for your use case?

**Comment by 573** [comment]
#900 looks like what is missing, the devenv.yaml option could be feasible from flakes as well then further up the road, so yeah, this would be a nice addition.

**Comment by haraldh** [comment]
my use case would be `stdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.clangStdenv;`

**Comment by domenkozar** [comment]
Can you try https://github.com/cachix/devenv/pull/1092 and tell me if that works for you as expected?

**Comment by 573** [comment]
Tried and worked. Thanks all for the work !
