### ISSUE TITLE
Setting cachix substituter in flake

### ISSUE THREAD

**Issue by mausch** [cachix/devenv#575]
Hi and thanks for this project!

I'd like to introduce devenv to my coworkers, but they're non-nix users so I'm trying to lower the barrier to entry. 
Getting them to install Nix was already a big ask. There's no chance they'll also go through https://devenv.sh/getting-started/#installation  installing cachix and then devenv. 
Thanks to Nix being wildly flexible and flakes not being the standard yet they'll start wondering if they need all those "advanced" install alternatives.

So I want to write a flake.nix and a devenv.nix so I can just tell people to run `nix develop` and then they get the environment, plus the ease of use of `devenv` when/if someone wants to use it.

The problem I have is setting up the binary cache for devenv within this flake.nix

Here's my flake.nix:

```
{
  # copied from https://github.com/cachix/devenv/blob/v0.6.2/flake.nix#L4-L7C5
  nixConfig = {
    extra-trusted-substituters = [ "https://devenv.cachix.org" ];
    extra-trusted-public-keys = [ "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=" ];
  };

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    devenv.url = "github:cachix/devenv/v0.6.2";
  };

  outputs = { self, nixpkgs, flake-utils, devenv }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in {
        defaultPackage = pkgs.mkShell {
          buildInputs = [
            devenv.packages.${system}.devenv
          ];
        };
      }
    );  
}
```

When I run `nix develop` it asks me to allow the substituter but then it goes off to compile libzip, the AWS SDK and the rest of the world.

**Comment by domenkozar** [comment]
Try replacing `extra-trusted-substituters` using `extra-substituters`

**Comment by gshpychka** [comment]
@domenkozar it outputs `warning: ignoring untrusted substituter 'https://devenv.cachix.org', you are not a trusted user.`. Do I have to add myself as a trusted user for this to work? I would like to avoid that if possible due to security implications
