### ISSUE TITLE
nginx service issues

### ISSUE THREAD

**Issue by sehqlr** [cachix/devenv#589]
**Describe the bug**
I have an nginx configuration that does not run with `devenv up`.

```
λ devenv up
13:37:52 system     | api.1 started (pid=321025)
13:37:52 system     | nginx.1 started (pid=321028)
13:37:52 system     | postgres.1 started (pid=321030)
13:37:52 system     | ui.1 started (pid=321032)
13:37:52 nginx.1    | 2023/05/12 13:37:52 [notice] 321028#321028: using the "epoll" event method
13:37:52 nginx.1    | 2023/05/12 13:37:52 [notice] 321028#321028: nginx/1.24.0
13:37:52 nginx.1    | 2023/05/12 13:37:52 [notice] 321028#321028: built by gcc 12.2.0 (GCC)
13:37:52 nginx.1    | 2023/05/12 13:37:52 [notice] 321028#321028: OS: Linux 5.15.106
13:37:52 nginx.1    | 2023/05/12 13:37:52 [notice] 321028#321028: getrlimit(RLIMIT_NOFILE): 1024:524288
13:37:52 nginx.1    | 2023/05/12 13:37:52 [emerg] 321028#321028: open() "/home/sehqlr/Projects/example/.devenv/state/nginx/nginx.pid" failed (13: Permission denied)
13:37:52 system     | nginx.1 stopped (rc=1)
13:37:52 system     | sending SIGTERM to api.1 (pid 321025)
13:37:52 system     | sending SIGTERM to postgres.1 (pid 321030)
13:37:52 system     | sending SIGTERM to ui.1 (pid 321032)
13:37:52 system     | api.1 stopped (rc=-15)
13:37:52 system     | postgres.1 stopped (rc=-15)
13:37:52 system     | ui.1 stopped (rc=-15)
```

**To reproduce**
https://gist.github.com/sehqlr/d1c98dbb96a3e6f11a2d600a33d6fbef

**Version**
 devenv: 0.6.2

**Comment by sandydoo** [comment]
@sehqlr, your repro works for me. 

Have you checked whether any of the directories in `/home/sehqlr/Projects/example/.devenv/state/nginx/nginx.pid` are owned by root?

**Comment by sehqlr** [comment]
Hey @sandydoo, I can't get the service to run long enough to check what the ownership of the PID is, but I will say that the `~/Projects/example/.devenv/state/nginx` is owned by `nobody:users`

**Comment by sandydoo** [comment]
@sehqlr, it's owned by `nobody`? As in the reserved user `nobody`?
It sounds like you don't have write permissions in the `.devenv` folder. Are you able to create files with `touch ~/Projects/example/.devenv/state/nginx/test`?

**Comment by sandydoo** [comment]
@sehqlr, you should `chown -R` the `.devenv` folder and make sure that it's owned by the current user. The nginx server should then start as expected.

**Comment by sehqlr** [comment]
That fixed it! Thanks
