### ISSUE TITLE
The `rustfmt`nix package is broken 

### ISSUE THREAD

**Issue by olebedev** [cachix/devenv#594]
The `rustfmt` package that is enabled via 

```nix
{ pkgs, lib, ... }:

{ 
  # ...
  languages.rust.enable = true;
} 
```
doesn't work. 

**To reproduce**

https://gist.github.com/olebedev/d6968b32d7a1378d22586ebc6e466a53#to-reproduce

Please note, a separately installed `rustfmt` works well. I assume this is an issue with https://github.com/nix-community/fenix, but not sure here.

**Version**
 
`devenv: 0.6.2`

**Comment by olebedev** [comment]
I tried to define the rust tool chain manually as a set of packages:
```nix
{ pkgs, lib, ... }:

{
  # https://devenv.sh/basics/
  env.GREET = "devenv";
  env.RUST_SRC_PATH = "${pkgs.rustPlatform.rustLibSrc}";

  # https://devenv.sh/packages/
  packages = with pkgs; [
    git
    glow
    cargo
    clippy
    rustfmt
    rustc
    rust-analyzer
  ]
  ++ lib.optionals pkgs.stdenv.isDarwin (with pkgs.darwin.apple_sdk; [
    frameworks.Security
  ]);

  # https://devenv.sh/scripts/
  scripts.hello.exec = "echo hello from $GREET";

  # https://devenv.sh/languages/
  languages.nix.enable = true;
  # languages.rust.enable = true;

  # https://devenv.sh/pre-commit-hooks/
  pre-commit.hooks = {
    shellcheck.enable = true;
    clippy.enable = true;
    rustfmt.enable = true;
  };

  # See full reference at https://devenv.sh/reference/options/
}
```

and getting the same error as in the repo example above. That makes me think that this is not an issue wuth the `rustfmt` package but rather `rpath` that Nix understand is overridden somehow so it mess things up.

**Comment by vic** [comment]
Related: #590
