### ISSUE TITLE
When using Overmind, PHP-FPM is not stopped when services are stopped

### ISSUE THREAD

**Issue by cumber** [cachix/devenv#595]
**Describe the bug**

When using Caddy & PHP as [shown in the examples](https://github.com/cachix/devenv/tree/main/examples/caddy-php), I've noticed that PHP-FPM is not killed when exiting the `devenv up` process. This *only* happens when using `process.implementation = "overmind"` though, not any of the other process managers.

After pressing Ctrl+C to terminate the processes, the following output is printed:

```
Stopping processes...
caddy      | Interrupting...
phpfpm-web | Interrupting...
caddy      | 2023/05/15 08:14:12.906	INFO	shutting down	{"signal": "SIGINT"}
caddy      | 2023/05/15 08:14:12.906	WARN	exiting; byeee!! 👋	{"signal": "SIGINT"}
caddy      | 2023/05/15 08:14:12.906	INFO	tls.cache.maintenance	stopped background certificate maintenance	{"cache": "0xc0001f76c0"}
caddy      | 2023/05/15 08:14:12.906	INFO	admin	stopped previous server	{"address": "localhost:2019"}
caddy      | 2023/05/15 08:14:12.906	INFO	shutdown complete	{"signal": "SIGINT", "exit_code": 0}
caddy      | Killing...
phpfpm-web | Killing...
caddy      | Exited
phpfpm-web | Exited
Processes stopped.
```

So Overmind claims to have killed the process, but `ps -ef | grep php-fpm` shows it is still running.

This then blocks running `devenv up` again, as PHP-FPM will notice that another instance is already using its socket and die.

**To reproduce**

I've created a [reproduction repo](https://github.com/cumber/devenv-overmind-phpfpm). It's just the Caddy+PHP example with `process.implementation = "overmind"` added.

**Version**
 
devenv: 0.6.2

**Comment by thenonameguy** [comment]
@cumber see this comment and the surrounding thread for reference:
https://github.com/F1bonacc1/process-compose/issues/33#issuecomment-1348159315

It seems you can configure the kill signal to be used:
https://github.com/DarthSim/overmind/blob/7d970570e9208812eaf3782d695bc13700bee48e/start/procfile.go#L19

Not strictly a devenv bug, although the php.nix module could define this kill signal to be used across the different implementations. This configuration does not exist at the moment, only for `process-compose`.

**Comment by cumber** [comment]
@thenonameguy Yes, the issue itself isn't devenv's "fault", but given devenv supports PHP-FPM and Overmind it would be nice if it knew how to configure them to play well together.

Absent that, I couldn't find a way in devenv to add any configuration to the procfile that would change the way Overmind tries to kill PHP-FPM. (It's only possible to add settings for process-compose?)

**Comment by stephank** [comment]
Honcho also has a problem here (on macOS at least). It's trying to kill the shell script, which goes defunct, but the php-fpm processes themselves don't respond. It then goes into a loop forever trying to SIGKILL the shell script.

Seems to work out-of-the-box with process-compose now.

**Comment by stephank** [comment]
I believe https://github.com/cachix/devenv/commit/9691d307f1f4b3827db13692cecaa9598cddf2c5 fixed this. The issue is not present on `main` for me.

**Comment by stephank** [comment]
Scratch that, and sorry for the confusion. This issue is indeed Overmind specific and still present on `main`.
