### ISSUE TITLE
rust: framework wrong set

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#617]
**Describe the bug**
When rust enabled the link to Framework of apple is set wrong

**To reproduce**
Build something with rust

```
  = note: ld: warning: directory not found for option '-F/nix/store/w7l75bv65jhy6yywcj0b2pzzzlldlym1-devenv-profile/Library/Frameworks'
```

**Version**
 
Paste the output of `$ devenv version` here.

**Comment by sandydoo** [comment]
@shyim, could you share a minimal repro? I just built the default `cargo init` project without issues.

**Comment by shyim** [comment]
It's small https://github.com/shopwareLabs/ext-shopware but does not work on mac :). As workaround I used rustup and that did fine

**Comment by sandydoo** [comment]
Ah, I see whats happening! The path to `Library/Frameworks` has been hardcoded in the language integration, but no frameworks are added by default. The basic example works because it manually adds the Security framework.

**Comment by pogopaule** [comment]
Here is another workaround: https://github.com/cachix/devenv/issues/508

**Comment by domenkozar** [comment]
Fixed on master
