### ISSUE TITLE
How to use devenv with editors like VSCode or Rider

### ISSUE THREAD

**Issue by mrfelton** [cachix/devenv#620]
Neither VS Code or Rider seem able to use the versions of software enabled by devenv. For example, a devenv installs Node.js, but VS Code is unaware of this (it's not on the main system path unless you active the devenv).

I gather that using a devcontainer is a way to make devenv compatible with VSCode, but devcontainer support seems to be in a fairly unusable state, at least [on a mac where it seems to be impossible to compile the container](https://github.com/cachix/devenv/issues/430). Is this the recommended/only way to get this working, or is there a way to make tools like VS Code or Rider aware of and compatible with a locally running devenv?

Note - In VSCode Terminal it's possible to instantiate the devenv, but that doesn't make the devenv tooling available to VSCode itself. So any VSCode extensions or native functionality that relies on system tooling being installed (nodejs, dotnet, python etc) does not work.

For Rider, I have been unable to make it use the devenv installed version of dotnet. It's possible to configure Rider with a path to a custom dotnet executable, but with devenv this changes all the time so there is no static path that could be used to configure Rider so that it leverages the tooling from a devenv.

**Comment by thenonameguy** [comment]
Use devenv's direnv integration plus any editor specific direnv plugin.

**Comment by mrfelton** [comment]
I am using both of those. But still VSCode is unaware of the tooling. The direnv support in VSCode ensures that when I open up a terminal the direnv is activated. But it seems to have no effect outside of a terminal session. So you just end up with a bunch of errors like this, for example

<img width="450" alt="image" src="https://github.com/cachix/devenv/assets/200251/57be58c4-00e7-41f2-acc6-43d9132171b3">

**Comment by mrfelton** [comment]
I can set a custom path - but what would I set it to given the path to the node binary changes all the time?

<img width="940" alt="image" src="https://github.com/cachix/devenv/assets/200251/de8a85b7-2e64-434a-83ac-ed7ddff7f8e4">

**Comment by adrian-gierakowski** [comment]
Doesn’t running `code` from terminal after entering devenv shell work? It doesn’t work for me with `subl` (SublimeText)

**Comment by thenonameguy** [comment]
> I can set a custom path - but what would I set it to given the path to the node binary changes all the time?
> 
> 
> 
> <img width="940" alt="image" src="https://github.com/cachix/devenv/assets/200251/de8a85b7-2e64-434a-83ac-ed7ddff7f8e4">
> 
> 

This is why the $DEVENV_PROFILE env var exist, so:

$DEVENV_PROFILE/bin/node 

always points to the current devenv defined node binary.

**Comment by mrfelton** [comment]
Unfortunately that doesn't work. Presumably either VSCode doesn't support environment variable interpolation here or the `$DEVENV_PROFILE` env var is not known to it at the right point in it's lifecycle.

**Comment by adrian-gierakowski** [comment]
> Doesn’t running `code` from terminal after entering devenv shell work? It doesn’t work for me with `subl` (SublimeText)

This doesn’t work? Whatever binaries are on PATH when you start code should be available to the editor.

**Comment by mrfelton** [comment]
> Whatever binaries are on PATH when you start code should be available to the editor.

Ok - so that is the trick. Starting VSCode from the command line using `code .` gets it working. Starting VS Code normally and letting it attempt to load the devenv itself using direnv extension does not.
