### ISSUE TITLE
Race Condition for multiple tools spawned via `direnv exec`

### ISSUE THREAD

**Issue by ryansch** [cachix/devenv#629]
**Describe the bug**
I'm running a lot of automated processes via editor tooling; language servers, linters, etc. I'm seeing a lot of extra errors due to race conditions when trying to set up the devenv environment.

Since a lot of these tools are spawned at the same time, it seems that they race to create the various symlinks required by devenv.

Examples:
- `ln: .devenv/profile: File exists`
- `ln: .devenv/profile/a4jvj862kmjmlgmqc4f17166n3qhp5b6-devenv-profile: Permission denied`

**To reproduce**
I've created an example rails project with a lot of the tooling we use in our real repos:
https://github.com/detaso/rails-tooling

**Version**
devenv: 0.6.2

**Comment by domenkozar** [comment]
This is fixed in #745
