### ISSUE TITLE
Add Temporal process

### ISSUE THREAD

**Issue by sagikazarmark** [cachix/devenv#632]
[Temporal](https://temporal.io/) is a workflow engine that allows executing long-running workflows. Although it has a lot of dependencies normally (database, elasticsearch, etc), it comes with a dev server mode that I believe fits perfectly into devenv as a process.

I'd be happy to open a PR if you think it's a good fit.

**Comment by domenkozar** [comment]
It's a good fit, any service is welcome to be added as long as it has a test (search for a `.test.sh` file in examples folder).

**Comment by sagikazarmark** [comment]
Thanks @domenkozar! PR sent.
