### ISSUE TITLE
Problem when compiling C code

### ISSUE THREAD

**Issue by Nick1296** [cachix/devenv#656]
**Describe the bug**
I have a development environment that is a mix of C and python code.
Whenever I compile code with C functions defined in sched.h some of these are reported as undefined.
If I try to add glibc as a package direnv crashes.

**To reproduce**
[Minimal working example](https://gist.github.com/Nick1296/df5800e7050e0bbb447bb8fd327c0f33)

enable direnv and compile with `gcc -o test test.c -lnuma`.

The expected result would be compilation without errors, however with direnv gcc sees sched_getaffinity, SCHED_FIFO, and all cpu macros to be undefined.

**Version**
 devenv 0.6.2

**Platform**
Arch linux with nix 2.15.0

**Comment by domenkozar** [comment]
If I add `numactl` to packages, your examples works with devenv 1.0.1
