### ISSUE TITLE
Get rid of impure mode

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#658]
https://github.com/NixOS/nix/issues/5663

**Comment by Atry** [comment]
It is possible to set `DEVENV_ROOT` to support pure mode
See #566 and #583

**Comment by Atry** [comment]
Why do we need plain Nix expressions as flake inputs? Why not just generate a flake that contains current environment variables, including `PWD`, then just pass `--override-input` to use the generated flake.

**Comment by domenkozar** [comment]
For devenv we can do that, but not for the flakes integration.

**Comment by Atry** [comment]
How about:
```
nix develop --redirect .#devenv-state ./.devenv/state
```

https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-develop.html

**Comment by Atry** [comment]
I think the current impure `devenv.root` is a dangerous design when packing images via `nix2container`, because the image content could depend on `devenv.root` and reference to non-existing directory at runtime.

**Comment by Atry** [comment]
Ideally, there should be a `perWorkingDirectory` submodule under `devenv`, where we can access `root`. Environment variables that contain abstract paths should be configured under `devent.perWorkingDirectory.env`, instead of `devent.env`

**Comment by domenkozar** [comment]
In #745 we now generate PWD instead of using `--impure` when using `devenv` cli.

**Comment by Atry** [comment]
How about also avoid `--impure` when using flake? See https://github.com/cachix/devenv/pull/745/files#r1285246995

**Comment by khaled** [comment]
Looking forward to the Python rewrite, as `--impure` seems to prevent evaluation caching from occurring.  This makes devenv annoyingly slow when e.g. entering directories with a `use flake --impure` in `.envrc`.

**Comment by khaled** [comment]
> Looking forward to the Python rewrite, as `--impure` seems to prevent evaluation caching from occurring. This makes devenv annoyingly slow when e.g. entering directories with a `use flake --impure` in `.envrc`.

Unless one uses [nix-direnv](https://github.com/nix-community/nix-direnv), which caches the nix shell environment.  The point about evaluation caching stands though.

**Comment by Atry** [comment]
Why is this issue closed? `--impure` is still needed according to https://devenv.sh/guides/using-with-flakes/#getting-started

**Comment by Atry** [comment]
See https://github.com/cachix/devenv/pull/1018

**Comment by domenkozar** [comment]
This issue was about devenv itself, for flakes it needs to be fixed in Nix itself. Let's see if #1018 will work :)
