### ISSUE TITLE
Support creation of initial user in MongoDB

### ISSUE THREAD

**Issue by stig** [cachix/devenv#672]
I'm trying to bring devenv into a codebase that has lots of tests that uses MongoDB with authentication using docker. The official MongoDB docker images allow creation of initial user by setting two [environment variables](https://hub.docker.com/_/mongo/#environment-variables) in your docker compose file.

I can make the tests in my project pass by removing the auth parameters, but this is something I think my team will not have appetite for (and breaks CI,  which runs using Docker). Thus to make tests pass without changing the code I need to be able to add a MongoDB user. It would be nice if there was a very easy way to do that, ideally something like:

```
  services.mongodb = {
    enable = true;
    initdb = {
      root-username = "my-user";
      root-password = "my-password";
      database = "admin";
    };
  };
```

Alternatively something more generic that allowed you to run a script at init-time would be slightly less desirable for my specific use case, but would also work and may be less burden to support in the long run:

```
  services.mongodb = {
    enable = true;
    init-script = ''
      use admin
      db.createUser(
        {
          user: "myUserAdmin",
          pwd: passwordPrompt(), // or cleartext password
          roles: [
            { role: "userAdminAnyDatabase", db: "admin" },
            { role: "readWriteAnyDatabase", db: "admin" }
          ]
        }
      )
   '';
  };
```

**Comment by domenkozar** [comment]
Happy to accept a PR :) cc @samjwillis97

**Comment by stig** [comment]
Maybe next hack week 😄

**Comment by samjwillis97** [comment]
I'll have a look at this, definitely makes sense to support at least what is available in their docker image 😊
