### ISSUE TITLE
Documentation improvement suggestions

### ISSUE THREAD

**Issue by skurfuerst** [cachix/devenv#674]
**Describe the bug**

The docs which existed were totally understandable etc; but I missed the following things:

- an introduction to services in the main menu here next to "languages": https://devenv.sh/languages/
- some a bit more in depth examples on "languages" how you can customize languages
- some more complete examples for full applications.
- Bonus: some example/explanation about extensibility

Generally, I first thought that [devenv.sh](http://devenv.sh/) can maybe do 20% of what it can really do from first skimming the docs; only when I discovered https://devenv.sh/reference/options/, I saw how powerful it really is.

**Comment by MatrixManAtYrService** [comment]
I wonder if there's a way to compile a list of projects using devenv.  Exploring their configurations would be very helpful, and perhaps less work than creating examples.

**Comment by skurfuerst** [comment]
That would be useful :)

**Comment by skurfuerst** [comment]
I know about https://github.com/kellerkinderDE/devenv-shopware and  

https://github.com/sandstorm/devenv-neos (my own).

All the best!

**Comment by domenkozar** [comment]
I've pushed ce36bb6cebedfdfd19e4043836d51bde8b3c1419 that adds services and improve docs on languages.

We still need to write a guide how to customize devenv and provide more examples.

**Comment by domenkozar** [comment]
cc @k3yss: ideally we'd have something like `languages.python.doc` that would describe how the language bits are used and then we'd render that in the manual.

**Comment by domenkozar** [comment]
Finally done! Thank you.
