### ISSUE TITLE
Misleading documentation (feat. not yet released)

### ISSUE THREAD

**Issue by jboyens** [cachix/devenv#675]
**Describe the bug**
Documentation site describes `permittedInsecurePackages` as a valid `devenv.yaml` key.

Presumably the documentation got updated when https://github.com/cachix/devenv/pull/638 got merged, but since there's been no release since the PR was merged, the documentation is misleading.

**Version**
`devenv: 0.6.2`

**Comment by domenkozar** [comment]
Released v0.6.3, thanks!

**Comment by mrfelton** [comment]
> Released v0.6.3, thanks!

I don't see v0.6.3 anywhere
