### ISSUE TITLE
arm64 devcontainer image

### ISSUE THREAD

**Issue by autolisis** [cachix/devenv#680]
Describe the bug
When attempting to run devenv generated devcontainer, it appears that there is no arm64 version of the cachix devenv image available on ghcr.io/cachix/devenv. This is causing a failure in my cluster, which is running on aarch64 machines.

Auto-generated Devcontainer.json
```json
{
  "name": "nix-devcontainer-greenflow",
  "customizations": {
    "vscode": {
      "extensions": [
        "charliermarsh.ruff",
        "kamadorueda.alejandra",
        "mkhl.direnv"
      ]
    }
  },
  "image": "ghcr.io/cachix/devenv:latest",
  "overrideCommand": false,
  "runArgs": [
    "--network=host",
    "--security-opt",
    "label=disable"
  ]
}
```
Attempt to run the devcontainer generated fails on my cluster that contains only aarch64 machines. I believe that looking at the provided Dockerfile, it should be as simple as building and pushing the appropriate image following the normal github actions workflow for multi-platform manifests https://docs.docker.com/build/building/multi-platform/

Version
Paste the output of $ devenv version here.
```
0.6.2
```

Note: This issue seems to be present irrespective of the devenv version being used, as the root cause is the unavailability of the arm64 version of cachix devenv image on GHCR.

**Comment by domenkozar** [comment]
Now that we have arm64 builders, we need to automate pushing the containers via github actions and this should work.

**Comment by ereduled** [comment]
Well, it's definitely merely a nice to have as this isn't blocking anything.

I'm currently continuing to use it by building and pushing the image manually to my own registry and changing the image by using `devcontainer.settings.image`.

PS: On a side-note, looking at the Dockerfile and seeing that https://mcr.microsoft.com/en-us/product/devcontainers/base/about is available for arm64 as well, I believe setting the secrets for the docker hub in and adding a new action with https://docs.docker.com/build/ci/github-actions/multi-platform as a template Should Just Work™ for both platforms.

**Comment by domenkozar** [comment]
Could you try https://github.com/cachix/devenv/pkgs/container/devenv

**Comment by domenkozar** [comment]
I've pushed v0.6.3 that should also work for arm64!
