### ISSUE TITLE
Incorrect clang-wrapper path 

### ISSUE THREAD

**Issue by tebriel** [cachix/devenv#685]
**Describe the bug**

When using `languages.ruby.enable = true;` directive in the `devenv.nix` file on OSX, the LDFLAG for `clang-wrapper` is incorrect, referencing `eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` instead of the actual hash. This prevented me from installing `eventmachine`, verifiable with: `gem install eventmachine` as seen in the gist's `gem_make.out` file.

Actual (note `-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-clang-wrapper-11.1.0/`):
```rb
# irb
irb(main):001:0> require 'rbconfig'
=> false
irb(main):002:0> RbConfig::MAKEFILE_CONFIG["LDFLAGS"]
=> "-L. -fstack-protector-strong -L/nix/store/z1j6g5z5ik4mdynndakrw0p3ix96f37y-libffi-3.4.4-dev/lib -L/nix/store/rig1v2lb4nw5mz3a1sj0wqdsk9khbvwr-ncurses-6.4-dev/lib -L/nix/store/d7nxik0sp2jqka2ib6w5w6m2rclpgw9q-readline-8.2p1-dev/lib -L/nix/store/ilf4p8sb47c2hjmjbbd8bv07vqqs4kfg-zlib-1.2.13-dev/lib -L/nix/store/xjiy7yzvx5vy0c027fbs7vg9lk9n233j-openssl-3.0.9-dev/lib -L/nix/store/qs9nhg3d5s3n2yfwc7zkqvldn0x33xpl-gdbm-1.23/lib -L/nix/store/56z2crpnrwl0wbpj955fzrhhf99f3hqn-libyaml-0.2.5-dev/lib -L/nix/store/fqammp4dxb721d0zzjgaf8spwjrnwgcv-libiconv-50/lib -L/nix/store/dm123lgglzdl7nw4cnl135b4laxwgcs3-libobjc-11.0.0/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-clang-wrapper-11.1.0/resource-root/lib -L/nix/store/s90lrx3nrrsi711pia76c4x5rh3agww7-libSystem-11.0.0/lib"
```

**To reproduce**

https://gist.github.com/tebriel/632c6e6ec7312ddb0d3add404e605755

**Version**
 
devenv: 0.6.2
OSX: 13.4.1
Chip: Apple M1 Max
Nix: nix (Nix) 2.16.1

**Extra Context**

After researching and debugging for a while, it looks like the `LDFLAGS` are pulled from the config that built the ruby installation (see https://docs.ruby-lang.org/en/master/RbConfig.html), so I thought maybe this was an issue with https://github.com/bobvanderlinden/nixpkgs-ruby which I believe devenv uses to install ruby, but `nix flake init --template github:bobvanderlinden/nixpkgs-ruby#3.1.4` doesn't exhibit the same issue, so I decided it was likely within devenv.

**Comment by t56k** [comment]
I'm getting this same issue with a different gem--did you have any luck solving it?

**Comment by tebriel** [comment]
> I'm getting this same issue with a different gem--did you have any luck solving it?

@t56k I don't quite recall, have you tried using a different version of ruby? Mostly I've stopped doing development on OSX+devenv and do it remotely on a nixos box because of problems like this (which is disappointing but I gotta' get work done)!

**Comment by domenkozar** [comment]
This should be fixed, can someone confirm?

**Comment by t56k** [comment]
@domenkozar Happy to give this a test in a few hours, thanks for your work

**Comment by t56k** [comment]
@domenkozar Do you have an example flake where this is working?

**Comment by sandydoo** [comment]
> https://gist.github.com/tebriel/632c6e6ec7312ddb0d3add404e605755

The placeholder clang-wrapper is still there, but `gem install eventmachine` works from inside the shell.

**Comment by sandydoo** [comment]
There's an upstream PR to remove the warning-causing linker flags: https://github.com/NixOS/nixpkgs/pull/213841

The original error was this line: `ld: library not found for -lc++abi`. The warning mentioning the reference-removed clang wrapper was (mostly) benign.
Now that the library is picked up (I imagine via `NIX_LDFLAGS`?), things should build as normal.

I'm going to consider this resolved, but do ping us if anything comes up.
