### ISSUE TITLE
Postgres with Timescaledb: Create Extension TimescaleDB failed

### ISSUE THREAD

**Issue by bangau1** [cachix/devenv#696]
**Describe the bug**
When I setup `timescaledb` extension and initialScript to `create extension timescaledb`, the `devenv up` failed with the postgres error. The log
```
20:07:50 postgres.1 | 2023-07-01 20:07:50.836 WIB [89376] FATAL:  extension "timescaledb" must be preloaded
20:07:50 postgres.1 | 2023-07-01 20:07:50.836 WIB [89376] HINT:  Please preload the timescaledb library via shared_preload_libraries.
20:07:50 postgres.1 |   
20:07:50 postgres.1 |   This can be done by editing the config file at: /Users/agung/Works/hiveos-backend/.devenv/state/postgres/postgresql.conf
20:07:50 postgres.1 |   and adding 'timescaledb' to the list in the shared_preload_libraries config.
20:07:50 postgres.1 |           # Modify postgresql.conf:
20:07:50 postgres.1 |           shared_preload_libraries = 'timescaledb'
20:07:50 postgres.1 |   
20:07:50 postgres.1 |   Another way to do this, if not preloading other libraries, is with the command:
20:07:50 postgres.1 |           echo "shared_preload_libraries = 'timescaledb'" >> /Users/agung/Works/hiveos-backend/.devenv/state/postgres/postgresql.conf 
20:07:50 postgres.1 |   
20:07:50 postgres.1 |   (Will require a database restart.)
20:07:50 postgres.1 |   
20:07:50 postgres.1 |   If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with: 
20:07:50 postgres.1 |           SET timescaledb.allow_install_without_preload = 'on';
20:07:50 postgres.1 | 2023-07-01 20:07:50.836 WIB [89376] STATEMENT:  CREATE EXTENSION IF NOT EXISTS timescaledb;

```

**To reproduce**
My devenv.nix
```
{ pkgs, lib, ... }:

{
  # https://devenv.sh/basics/
  env.GREET = "devenv";

  # https://devenv.sh/packages/
  packages = [
    pkgs.git
    pkgs.go
  ];

  # https://devenv.sh/scripts/
  scripts.hello.exec = "echo hello from $GREET";

  enterShell = ''
    hello
    git --version
  '';

  # https://devenv.sh/languages/
  # languages.nix.enable = true;

  # https://devenv.sh/pre-commit-hooks/
  # pre-commit.hooks.shellcheck.enable = true;

  # https://devenv.sh/processes/
  # processes.ping.exec = "ping example.com";

  # See full reference at https://devenv.sh/reference/options/

  services.postgres = {
    enable = true;
    package = pkgs.postgresql_14;
#    package = pkgs.postgresql_14.withPackages(p: [p.timescaledb p.postgis]);
    extensions = extensions: [
        extensions.postgis
        extensions.timescaledb
    ];
    settings = { shared_preload_libraries = "timescaledb";};
    initialScript = "CREATE EXTENSION timescaledb;";

  };
}

```

- then `devenv up`, but it exits with postgres error above
- I see that the `postgresql.conf` file doesn't reflect with my setting above to include `timescaledb`.
```
$cat .devenv/state/postgres/postgresql*conf | grep shared_preload
#shared_preload_libraries = ''  # (change requires restart)
```
- but then i tried to `devenv up` second time again, it success, eventhough my `initialScript` is not executed (skipped). And to my surprise, the `shared_preload_libraries` now is correct.
```
$ cat .devenv/state/postgres/postgresql*conf | grep shared_preload
shared_preload_libraries = 'timescaledb'
```

In reality, my `initialScript` will be more complex than the example above (and requires to install timescaledb first). So to set `  SET timescaledb.allow_install_without_preload = 'on';` as suggested from error log above doesn't work for me, since my initialScript will make use of some function defined in timescaledb extension.

Also note that I tried experimenting it by replace the initialScript with  `"CREATE EXTENSION postgis;"`, but it running fine, since I believe it doesn't need the shared_preload_libraries to be configured at all.

**Version**
 
`devenv: 0.6.3`

**Comment by domenkozar** [comment]
That's strange, using the following ``devenv.nix``:

```nix
{ pkgs, ... }:

{
  services.postgres = {
    enable = true;
    initialDatabases = [{ name = "mydb"; }];
    extensions = extensions: [
        extensions.postgis
        extensions.timescaledb
    ];
    settings.shared_preload_libraries = "timescaledb";
    initialScript = "CREATE EXTENSION IF NOT EXISTS timescaledb;";
  };
}
```

The first time I run `devenv up` I get the same error, but if I run it again it works.

**Comment by thenonameguy** [comment]
`initialScript` is currently running against `single-user-mode` mode of Postgres, which apparently does not support extension creation:
https://stackoverflow.com/questions/28147177/do-create-extension-work-in-single-user-mode-in-postgres

The [official Postgres Docker image](https://github.com/docker-library/postgres/blob/master/16/alpine3.18/docker-entrypoint.sh#L326C1-L329) has migrated away from it [for the same reasons](https://www.postgresql.org/message-id/29161.1422337002%40sss.pgh.pa.us).
It might be time to do the same in the Devenv Postgres module as well.
