### ISSUE TITLE
devenv up does not work with flake.parts

### ISSUE THREAD

**Issue by NyCodeGHG** [cachix/devenv#711]
**Describe the bug**
The commit ddba5b442488a0036bba88097b9048d83dd0e709 seems to break flake.parts integration.
Running `devenv up` in the dev shell results in the error:
```
error: flake 'path:/redacted' does not provide attribute 'packages.x86_64-linux.devShells.x86_64-linux.default.config.procfileScript', 'legacyPackages.x86_64-linux.devShells.x86_64-linux.default.config.procfileScript' or 'devShells.x86_64-linux.default.config.procfileScript'
```

**To reproduce**
https://gist.github.com/NyCodeGHG/eae923727d56e4e86d8a48376ab53681

**Version**

`devenv: 0.6.3`

**Comment by domenkozar** [comment]
That's pretty bad. I'll look into it.

**Comment by domenkozar** [comment]
We need a test for flake-parts integration so this doesn't happen in the future.
