### ISSUE TITLE
Import devenv from an existing flake.nix

### ISSUE THREAD

**Issue by DavHau** [cachix/devenv#74]
Currently devenv forcefully replaces nix and flakes. For nix native users, or projects that already contain a flake.nix it could be interesting to import devenv as a dependency manually.

I'd like to hear your thoughts about this @domenkozar . Does mixing flake.nix and devenv.nix make sense in general or would it violate devshell in a fundamental way?

**Comment by domenkozar** [comment]
You can already do that, the only limitation (that I plan to fix) is that flake.nix can't be in the current directory.

To define the input: https://github.com/cachix/devenv/blob/main/devenv.yaml#L7
A flake: https://github.com/cachix/devenv/blob/main/src/modules/flake.nix

**Comment by domenkozar** [comment]
@DavHau I'm planning to write a guide for this, does the above answer your question?

**Comment by DavHau** [comment]
Yes, it does. Thank you

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/pull/150
