### ISSUE TITLE
Excluding packages from containers (or dev-only packages?)

### ISSUE THREAD

**Issue by dnikolovv** [cachix/devenv#748]
Following [the tutorial](https://devenv.sh/containers/#running-a-single-process), this is what I ended up with in my `devenv.nix`:

```nix
packages = [
    pkgs.git
    pkgs.haskell-language-server
  ];
...
containers = {
    "prod" = {
      name = "prod";
      copyToRoot = null;
      startupCommand = "";
    };
  };
...
```

When building the container via `devenv container prod --docker-run`, it seems that `pkgs.haskell-language-server` is adding a whopping `6.2GB` to its size for a `6.5GB` total!

However, if we imagine that the container only needs to run an executable that's already been built, we don't really need `haskell-language-server` (or `git` for that matter).

In a real project, it's easy to imagine you'll end up with quite a lot of these dependencies and containers that are possibly tens of gigabytes.

This sounds fairly impractical. Is there a way to include "dev-only" packages? Either that or is there a way to ignore certain packages when building containers?

Update: it seems `git` is a lot bulkier than I anticipated as well, adding close to `300MB`.

Stats so far:

```nix
packages = [];
```

produces a `76.2MB` container

```nix
packages = [
  pkgs.git
];
```

produces a `364.1MB` container

```nix
packages = [
  pkgs.git
  pkgs.haskell-language-server
];
```
produces a `6.5GB` container

**Comment by domenkozar** [comment]
```nix
packages = [
    pkgs.git
  ] ++ lib.optionals config.container.isBuilding [
    pkgs.haskell-language-server
  ];
```

**Comment by dnikolovv** [comment]
@domenkozar thanks for the swift reply!

This doesn't seem to work though.

My complete `devenv.nix`

```nix
{ pkgs, lib, config, ... }:

{
  # https://devenv.sh/basics/
  env.GREET = "devenv";

  # https://devenv.sh/packages/
  packages = [
  ] ++ lib.optionals config.container.isBuilding [
    pkgs.git
    pkgs.haskell-language-server
  ];
  
  containers = {
    "prod" = {
      name = "size";
      copyToRoot = null;
      startupCommand = "";
    };
  };

  # https://devenv.sh/scripts/
  scripts.hello.exec = "echo hello from $GREET";

  enterShell = ''
    hello
    git --version
  '';
}
```

Output of `devenv container prod --docker-run`:

```shell
/nix/store/mhrnyp5w6963kw9wzdblcaa2na192ski-image-size.json

Copying container /nix/store/mhrnyp5w6963kw9wzdblcaa2na192ski-image-size.json to docker-daemon:size:latest

Getting image source signatures
Copying blob 5f3fcd11c76c [>-------------------------------------] 112.2MiB / 6.5GiB
```

**Comment by dnikolovv** [comment]
I've also tested this with the reverse:

```nix
packages = [
    pkgs.git
    pkgs.haskell-language-server
  ] ++ lib.optionals config.container.isBuilding [
  ];
```

**Comment by domenkozar** [comment]
Pardon, it should be:

```
packages = [
    pkgs.git
  ] ++ lib.optionals !config.container.isBuilding [
    pkgs.haskell-language-server
  ];
```

**Comment by domenkozar** [comment]
Added here: https://devenv.sh/common-patterns/#how-to-exclude-packages-from-the-container
