### ISSUE TITLE
Referencing an environment variable with curly brackets

### ISSUE THREAD

**Issue by bjgbeelen** [cachix/devenv#759]
I'm running in the following issue, which is probably more a nix syntax issue than a devenv issue, but still hoping to get a response here, for I am very enthusiastic about devenv!

I'm trying to write a script that expects an input argument and I want to set a default value if it is not set

```
foo.exec = ''
    arg=${1:-default}
    echo $arg
'';
```
this gives the error: `syntax error, unexpected ':', expecting '}'`

That's because nix probably also uses `${}` for its own interpolation.

I can probably create a workaround, but would be nice to know if there is a way to make this work

**Comment by domenkozar** [comment]
To escape `${`. use `''${`

**Comment by bjgbeelen** [comment]
Thanks a lot!

**Comment by domenkozar** [comment]
Thanks, added here:
https://github.com/cachix/devenv/commit/e91205acb792f6a49ea53ab04c04fbc2a85039cd
