### ISSUE TITLE
`pkgs.buildEnv` Use `nixpkgs` instead of `devenv`?

### ISSUE THREAD

**Issue by Skarlett** [cachix/devenv#765]
Hello, I've been using the project very briefly, just over just a few days.  I am using nix flake + flake-parts.

While attempting to build the following derivation:
```nix
perSystem = args@{ config, self', inputs', pkgs, system, ... }: {
  # snip..
  packages.all = pkgs.buildEnv {
    name = "flake packages";
    paths = builtins.attrValues (builtins.removeAttrs config.packages ["all"]);
  };
}
```
I receive the following error.
```
error: To build the container, you need to add the following to your devenv.yaml:

       inputs:
         nix2container:
           url: github:nlewo/nix2container
           inputs:
             nixpkgs:
               follows: nixpkgs
         mk-shell-bin:
           url: github:rrbutani/nix-mk-shell-bin
(use '--show-trace' to show detailed location information)
```

While containers are quite useful, they're not needed in my case. I expected the default behavior of `nixpkgs.buildEnv`, 

- is there any to use `nixpkgs.buildEnv` instead of `devenv.buildEnv` ?

I'm very excited to continue using the project, but unfortunately the only solution I've found currently is to remove devenv from my flake.

**Comment by domenkozar** [comment]
Duplicates #760
