### ISSUE TITLE
Permission denied in `devenv ci`

### ISSUE THREAD

**Issue by bjgbeelen** [cachix/devenv#770]
**Describe the bug**
I've created a custom pre-commit hook that uses poetry:
```
entry = "${pkgs.poetry}/bin/poetry run pytest .";
```

When running `pre-commit run --all-files` this works, but when I try to run `devenv ci` I get the following exception:

```
[Errno 13] Permission denied: '/private/tmp/nix-build-pre-commit-run.drv-0/src/.venv/bin/pytest'
```

**Solution as mentioned on discord**
> oh yeah, we should wire up venv for devenv ci

**Comment by domenkozar** [comment]
The issue here is that we run `devenv ci` in a Nix derivation that doesn't have access to networking.

We'll need to design it differently to work with features like venv and poetry.

**Comment by domenkozar** [comment]
1.0 ships https://devenv.sh/tests/, which goal is exactly to fix this.

`devenv ci` is now deprecated.
