### ISSUE TITLE
Markdown include not rendering on docs website

### ISSUE THREAD

**Issue by AodhanHayter** [cachix/devenv#828]
URL: https://devenv.sh/services/

<img width="1533" alt="Screenshot 2023-09-21 at 1 23 11 PM" src="https://github.com/cachix/devenv/assets/9039761/8127b69a-def6-4194-8ed7-cc8e5b4d8fd9">

https://github.com/cachix/devenv/blob/7128be003e2fc3a9a2e5bcaddc42cf86cf5a6972/docs/services.md?plain=1#L38C1-L38C1

**Comment by bcardiff** [comment]
Also in https://devenv.sh/languages/#supported-languages

<img width="1103" alt="Screen Shot 2023-09-21 at 16 59 59" src="https://github.com/cachix/devenv/assets/459923/3ba4bc79-9f4f-46ba-8bfc-3777700412f7">

**Comment by domenkozar** [comment]
fixed, thanks!
