### ISSUE TITLE
Install devenv via home-manager

### ISSUE THREAD

**Issue by jminh** [cachix/devenv#831]
Can we install devenv via home-manager?

There are severals ways to install devenv as we can see from
https://devenv.sh/getting-started/#3-install-devenv:
1. Newcomers
2. Flake profiles
3. Declaratively using flakes
4. Declaratively without flakes

Note: from https://search.nixos.org/flakes? there is no devenv package.

**Comment by shyim** [comment]
I am right now using devenv with home manager. I added the flake to my flake as an input and referenced the package in the home.packages.

https://github.com/shyim/nixcfg/blob/main/flake.nix#L17

https://github.com/shyim/nixcfg/blob/main/flake.nix#L152

https://github.com/shyim/nixcfg/blob/main/home/packages.nix#L42

**Comment by THOUSAND-SKY** [comment]
I tried the relevant parts of the config from @shyim, but for me it wanted to pull `aws-sdk-cpp` and build it from source. I then tried adding `devenv.cachix.org` to my flake.nix `extra-substituters`, but that did nothing.

```
  # in home-manager `flake.nix`, next to `inputs`
  nixConfig = {
    extra-substituters = [ https://cache.nixos.org https://nix-community.cachix.org https://devenv.cachix.org ];
    extra-trusted-public-keys = [ cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= ];
  };
```

Any good ideas appreciated.

**Comment by domenkozar** [comment]
@THOUSAND-SKY what OS?

**Comment by THOUSAND-SKY** [comment]
I am on ubuntu 20.04 `5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by shyim** [comment]
when you have the exact same remove the inputs follows https://github.com/shyim/nixcfg/blob/main/flake.nix#L23

**Comment by domenkozar** [comment]
devenv is [now in nixpkgs](https://github.com/NixOS/nixpkgs/pull/297714) so you can install it via `pkgs.devenv`
