### ISSUE TITLE
Installation via Nix profiles fails

### ISSUE THREAD

**Issue by rkrzr** [cachix/devenv#84]
**Describe the bug**

I am trying to install both cachix and devenv via the flake profiles route. However `nix profile install nixpkgs#cachix` and `nix profile install github:cachix/devenv/v0.3` commands fail for both cachix and devenv with an error message.

**Steps To Reproduce**

`cachix` installation:

```
❯ nix profile install nixpkgs#cachix                                                                                                                                                           master
warning: path '/nix/store/4qdpbi788qb5h78l2rrcnf2lizb9h275-profile' claims to be content-addressed but isn't
error: cannot add path '/nix/store/4qdpbi788qb5h78l2rrcnf2lizb9h275-profile' because it lacks a valid signature
```

And `devenv`:

```
warning: Using saved setting for 'extra-substituters = https://devenv.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=' from ~/.local/share/nix/trusted-settings.json.
warning: path '/nix/store/qwkzx221cdg591r7rk7xbl9akz6i1cph-profile' claims to be content-addressed but isn't
error: cannot add path '/nix/store/qwkzx221cdg591r7rk7xbl9akz6i1cph-profile' because it lacks a valid signature
```

I tried removing `~/.local/share/nix/trusted-settings.json`, but the problem persists also without the cached settings.

**Expected behavior**

Both `cachix` and `devenv` should be installed.

**Additional context**

`nix (Nix) 2.11.0` on Ubuntu 22.04.

`nix shell github:cachix/devenv/v0.3 ` works without an error.

As a workaround I now installed both `cachix` and `devenv` via the nix-env route, which worked without errors.

**Comment by domenkozar** [comment]
I must admit I'm lost what's going on here, seems like a Nix bug to me.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nix/issues/4425 hints that your nix-daemon version mismatches the client version.

**Comment by rkrzr** [comment]
I tried the command again after restarting `nix-daemon`, but to no avail unfortunately. But it does look more like a Nix bug, so we can also close this issue again.

**Comment by rkrzr** [comment]
I found the problem: I happened to have two different versions of nix installed on this machine. The multi-user installation running `nix-daemon` was old (nix (Nix) 2.3.6) while the nix client in my user session was new (nix (Nix) 2.11.0). So it was the version mismatch problem after all. `nix profile` now works as expected.
