### ISSUE TITLE
Devenv reports out of date when up to date

### ISSUE THREAD

**Issue by jocelynthode** [cachix/devenv#85]
Hi,

After installing devenv (using direnv) whenever I enter my folder I get the following message:
```
Building shell ...
deadnix 0.1.8
cachix 1.0.1
statix 0.5.6
vulnix 1.10.1
✨ devenv is out of date. Please update to 0.3: https://devenv.sh/getting-started/#installation
```

however when running `devenv version` I get `devenv: 0.3`. I'm also using the following input in my `flake.nix`: `devenv.url = "github:cachix/devenv/v0.3";`

Here is my NixOS config is more info is needed: https://github.com/jocelynthode/nixos-config

**Comment by domenkozar** [comment]
Can you try adding the following to your devenv:

``
enterShell = ''
  echo "devenv: $DEVENV_VERSION"
''';
``

**Comment by JanLikar** [comment]
Same issue for me, after adding your snippet it looks like `$DEVENV_VERSION` is not set.

**Comment by jocelynthode** [comment]
Yep I can confirm @JanLikar findings. It's the same on my end.

**Comment by domenkozar** [comment]
Thanks guys, will investigate and make this more robust.
