### ISSUE TITLE
How can I access environment variables in a Flake?

### ISSUE THREAD

**Issue by Nebucatnetzer** [cachix/devenv#851]
I have an Nginx config in which I need to set the web root and the path to the FPM socket.
However Nginx doesn't read environment variables by default so I thought it would be easiest to write the path directly into the config file generated by devenv.
However I'm doing it wrong and it always uses the path from the Nix store.
What would be the correct way to reference e.g. `DEVENV_ROOT` or `DEVENV_STATE` inside the flake.nix?
I image something like `self.env.DEVENV_STATE` but so far I haven't found the correct value.

**Comment by domenkozar** [comment]
config.env.DEVENV_STATE

**Comment by Nebucatnetzer** [comment]
Do I need to add `rec` I can't seem to access `config`.
I followed the guide here: https://devenv.sh/guides/using-with-flakes/#modifying-your-flakenix-file

**Comment by Nebucatnetzer** [comment]
`self.devShells.${system}.default.config.env.DEVENV_ROOT` seems to work but let me know if there is a better way.

**Comment by domenkozar** [comment]
If you change  `({ pkgs, ... }: {` to `({ pkgs, config, ... }: {` you can reference `config` directly.

**Comment by Nebucatnetzer** [comment]
A perfect thank you!
