### ISSUE TITLE
Add support for `pdm`

### ISSUE THREAD

**Issue by totoroot** [cachix/devenv#854]
I would like to have support for `pdm` in devenv, just like there already is for `poetry`.
`pdm` is a modern Python package and dependency manager supporting the latest PEP standards.

More information can be found [here](https://pdm.fming.dev/latest/).

I'm planning on working on this myself.

**Comment by domenkozar** [comment]
Duplicates #703

**Comment by mattthym** [comment]
Whoops, sorry for the noise. I had a typo when I was looking through the issues :sweat_smile:

**Comment by totoroot** [comment]
Whoops, sorry for the noise. I had a typo when I was looking through the issues 😅
