### ISSUE TITLE
Starship is initialized wrong when loaded by direnv in zsh

### ISSUE THREAD

**Issue by hansalves** [cachix/devenv#860]
**Describe the bug**
Starship outputs wrong control characters when initialized from zsh through direnv.

**To reproduce**
This can be reproduced by creating a .envrc (by running devenv init) in the starship example in git from zsh.

![image](https://github.com/cachix/devenv/assets/34193042/44de6298-9891-45f2-afe6-f44293aa2db2)

The integration adds `eval "$(starship init $(echo $0))"` to the enterShell.
 $0 will be the bash that's started by devenv, not the parent shell. This causes starship to output bash control characters instead of zsh ones.

**Version**
 
devenv: 0.6.3

**Comment by hansalves** [comment]
A workaround is to set the STARSHIP_SHELL variable to zsh. However, this will cause starships shell module to display zsh instead of bash.

**Comment by cyberjar09** [comment]
how did youll resolve this? I also have the same problem but the setting of `STARSHIP_SHELL` did not work

```
{ pkgs, lib, config, inputs, ... }:

{
  env.STARSHIP_SHELL = "zsh";

  enterShell = ''
    if [ -d ".venv" ]; then
      source .venv/bin/activate
    else
      uv venv && source .venv/bin/activate
    fi
  '';


  languages = {
    python = {
      enable = true;
      version = "3.11.6";
    };
  };


  dotenv.enable = true;

  starship.enable = true;
}
```

**Comment by hansalves** [comment]
I ended up not using starship from devenv, but initializing it from my .bashrc / .zshrc 
In devenv I now only have
    enterShell = ''
        export STARSHIP_CONFIG=${config.env.DEVENV_ROOT}/starship.toml
    .......
    ''

**Comment by therealpxc** [comment]
This affects me with Fish as well:

<img width="655" alt="image" src="https://github.com/user-attachments/assets/e10de111-e52a-44ef-bc2c-34abc14f4c33">

**Comment by therealpxc** [comment]
I've also noticed that the prompt gets mangled if I just call `bash` in there, but not if I invoke the systemwide bash provided by Nix. I think we've ended up with `pkgs.bash` rather than `pkgs.bashInteractive`. When I add `pkgs.bashInteractive` to my `packages` declaration in `devenv.nix`, my prompt looks fine when I enter a new shell with `bash`.

I think we can maybe fix this if we get mkShell or something similar to use `bashInteractive` instead of plain `bash`. The [WIP](https://github.com/NixOS/nixpkgs/pull/330822) `devShellTools.buildShell` might solve this issue.

**Comment by therealpxc** [comment]
>  When I add pkgs.bashInteractive to my packages declaration in devenv.nix, my prompt looks fine when I enter a new shell with bash.

So this is kinda crazy and heavy-handed, but for me setting:

```
stdenv = pkgs.stdenv.override (old: { shell  = "${pkgs.bashInteractive}"; });
```

fixes this for `flake.nix`-based projects for me with `nix (Nix) 2.23.3`. For `devenv 1.0.8 (aarch64-darwin)`, though, devenv's Nix (forked from 2.21) spits out an error:

```
error:
       error: 'nix develop' only works on derivations that use 'bash' as their builder

✖ Command produced the following output:


Error:   × Command `/nix/store/fqb0biq56868v5hvnp47fb3aabsk6as2-nix-2.21-devenv/bin/nix --show-
  │ trace --extra-experimental-features nix-command --extra-experimental-features
  │ flakes --option warn-dirty false --keep-going --max-jobs 5 --option eval-cache false
  │ print-dev-env --profile /Users/pxc/Documents/Code/Learning/Command-Line Rust/01/
  │ hello/.devenv/gc/shell --option extra-substituters https://devenv.cachix.org --option
  │ extra-trusted-public-keys devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/
  │ Hm9XgU50cw=` failed with with exit code 1

direnv: failed to build the devenv environment. devenv.nix may contain errors. see above.
```
