### ISSUE TITLE
Docker container out of date?

### ISSUE THREAD

**Issue by monotykamary** [cachix/devenv#865]
Apart from a weird bug that I'm facing with devenv in devcontainers, I've noticed that the docker container at `ghcr.io/cachix/devenv` seems to still be version 0.6.2. Will this get updated?

**Comment by domenkozar** [comment]
There's now https://github.com/cachix/devenv/pkgs/container/devenv built from the main branch if you need the latest.

**Comment by domenkozar** [comment]
Pushed v0.6.3!
