### ISSUE TITLE
Use the defaults from NixOS

### ISSUE THREAD

**Issue by Nebucatnetzer** [cachix/devenv#876]
When I tried to server a site with services.nginx I was surprised to discover that the MIME types weren't set.
Wouldn't it make sense to use similar defaults as with NixOS or other distros for the services so that we don't have to rebuild the config from scratch?
For the MIME types this was the required line:

```nix
include ${pkgs.mailcap}/etc/nginx/mime.types;
```

**Comment by domenkozar** [comment]
Yes! Happy to merge a PR.
