### ISSUE TITLE
How to dynamically extend the PHP config?

### ISSUE THREAD

**Issue by Nebucatnetzer** [cachix/devenv#881]
I have the following config in `languages.php.ini`:

```
[browscap]
; http://php.net/browscap
browscap = "${self.devShells.${system}.default.config.env.DEVENV_STATE}/php-fpm/php_browscap.ini"
```

This works currently fine with Nixpkgs 23.05.
Since the next release is close I tested Unstable and got the following error:

```
error: builder for '/nix/store/v281j8lm1wfgjja88m9f6s00bjahzbli-composer-local-repo-plugin-1.0.3.drv' failed with exit code 254;
       last 11 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/l5a037w0nj3iyfm8xhxh48vc6pa4m90l-source
       > source root is source
       > patching sources
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > building
       >
       > Warning: Cannot open "/home/zweili/git_repos/work/erp3000/.devenv/state/php-fpm/php_browscap.ini" for reading in Unknown on line 0
       >
       > Fatal error: Unable to start standard module in Unknown on line 0
```

When I remove the browscap config it works again.
What would be the recommended way to include browscap?
I tried to use `PHP_INI_SCAN_DIR` but that breaks PHP in general because it then only looks in that directory and all the other packages stop working.

`fetchurl` doesn't look like a viable path either because browscap say that they don't provide the old version so that hash could change at any moment.
Building it would probably work but I would prefer it, if I don't have to go down that road.
Especially since it work fine before.

**Comment by shyim** [comment]
I think it's not accessible because of the isolation. You could use `pkgs.writeText` with `builtins.readFile` to have that file in the nix store

**Comment by Nebucatnetzer** [comment]
Thank you in the meantime I found out that we didn’t actually use that file anymore. 
However we have a different project with multiple Nginx sites and I don’t know yet how that likes dynamic files. 
So I might end up using your solution for that.

**Comment by shyim** [comment]
Nginx should work as it does not need that file on build-time :).

**Comment by Nebucatnetzer** [comment]
That is good to know! I will test it soon.
