### ISSUE TITLE
MySQL service does not create `information_schema` database

### ISSUE THREAD

**Issue by eric-hansen** [cachix/devenv#894]
**Describe the bug**
When configuring the MySQL/MariaDB service, no `information_schema` database is created.  This in turn breaks things like Laravel's migration runner:

```
❯ ./artisan migrate

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] No such file or directory (Connection: mysql, SQL: select * from information_schema.tables where table_schema = hbm and table_name = migrations and table_type = 'BASE TABLE')
```

**To reproduce**
https://gist.github.com/eric-hansen/7612edc538450efb576edfedf4f7105f

**Version**
 
❯ devenv version
devenv: 0.6.3

**Comment by shyim** [comment]
Hey,

I think the error has nothing to do with that table. Did you run the artisan command inside the devenv shell aka `devenv shell` or have direnv running?

Also did you started also the services with `devenv up`?

**Comment by eric-hansen** [comment]
> I think the error has nothing to do with that table. 

Curious, what makes you think that the error has nothing to do with the `information_schema.tables`?

> Did you run the artisan command inside the devenv shell aka `devenv shell` or have direct running?

Not 100% sure I understand the difference, but I was in an active devenv shell, and do not have MariaDB/MySQL accessible/set up outside of the devenv shell.  So this is all within it.

> Also did you started also the services with `devenv up`?

Yes, and I tried it again with `devenv up` in one shell and running `./artisan migrate` in another with the same result.

If I instead use something like PlanetScale for my DB service then the same command works.  So it's something specific to devenv and how it configures MariaDB.

**Comment by shyim** [comment]
The error `No such file or directory` comes as it cannot find the mysql socket. This is mostly not available when the mysql server was not started.

Can you try to use maybe as host: 127.0.0.1?

**Comment by eric-hansen** [comment]
> The error `No such file or directory` comes as it cannot find the mysql socket. This is mostly not available when the mysql server was not started.
> 
> Can you try to use maybe as host: 127.0.0.1?

Hm, odd.  I know the server was started, but I tried using the IP instead and it ran the migrations just fine.  So I apologize for the false alarm and appreciate the help!
