### ISSUE TITLE
Error when inside directories with spaces

### ISSUE THREAD

**Issue by andersmmg** [cachix/devenv#90]
If anywhere in the pwd path there is a directory with spaces, I get an ambiguous redirect error for the $DEVENV_DIR variable. Renaming the directory to something without spaces does make it work, though that's not the best solution

```
/home/andersmmg/.nix-profile/bin/devenv: line 25: $DEVENV_DIR/devenv.json: ambiguous redirect
```

**Comment by domenkozar** [comment]
Fixed in `main` branch, thanks for the report!
