### ISSUE TITLE
Custom shell for scripts

### ISSUE THREAD

**Issue by CodeWitchBella** [cachix/devenv#907]
I like writing my scripts in nushell, but there seems to be no way for `scripts` to emit custom shebang.

I mean, I could write my script exec like this: `"${pkgs.nushell}/bin/nu ./scripts/script-name.nu $@";`, but then I can't easily use custom packages without exposing them to the shell as well. It'd be great to be able to set `scripts.*.shell` or similar.

**Comment by domenkozar** [comment]
Happy to accept a PR :)

**Comment by rawkode** [comment]
I've opened PR #1256 to hopefully provide a solution for this. Let me know what you think, @domenkozar @CodeWitchBella 

I wasn't sure how to test this behaviour, but I have added some working examples I've tested locally.
