### ISSUE TITLE
Unlclear how to feed an overlay something that can modiy a Python library

### ISSUE THREAD

**Issue by mcdonc** [cachix/devenv#918]
Often it's necessary to write an overlay that modifies some Python library (let's say, for example, Sphinx, which tends to fail to build for weird test-related reasons).  It's not clear how to do this when you use a Python from nixpkgs-python.

**Comment by domenkozar** [comment]
Duplicates https://github.com/cachix/devenv/issues/792

**Comment by domenkozar** [comment]
#478
