### ISSUE TITLE
nixpkgs-python depends on  domenkozar/nixpkgs/cpython-moduralize rather than a standard nixpkgs

### ISSUE THREAD

**Issue by mcdonc** [cachix/devenv#921]
It  appears that all the changes in ``domenkozar/nixpkgs/cpython-moduralize`` have been merged.  Sorry for putting this here and not in that repo; I'll forget about it otherwise.

**Comment by domenkozar** [comment]
Thanks for a reminder!

**Comment by domenkozar** [comment]
That's fixed now
