### ISSUE TITLE
Run multiple process-compose at the same time

### ISSUE THREAD

**Issue by bigluck** [cachix/devenv#936]
**Describe the bug**
I have multiple devenv projects, all of them come with different requirements and configurations, but all have a thing in common: they use `process-compose` to run on my computer.

How can I run multiple process-compose projects at the same time?

**To reproduce**
The problem is that only one project at a time can run; when I start the second project (in a different folder) using `devenv up`, devenv starts the shell, but then it dies:

Shell 1:
```bash
$ devenv up
Building shell ...
make[1]: Entering directory '/Users/bigluck/my_project_1'

Working on: /Users/bigluck/my_project_1
make[1]: Leaving directory '/Users/bigluck/my_project_1'
[redis	] 33529:C 15 Jan 2024 17:57:48.403 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[redis	] 33529:C 15 Jan 2024 17:57:48.403 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=33529, just started
...
```

Shell 2:

```bash
$ devenv up
Building shell ...
make[1]: Entering directory '/Users/bigluck/my_project_2'

Working on: /Users/bigluck/my_project_2
make[1]: Leaving directory '/Users/bigluck/my_project_2'

$ 
```

But If I kill `my_project_1`, and then type `devent up` on the `my_project_2` folder, it works.

Shell 2:

```bash
$ devenv up
Building shell ...
make[1]: Entering directory '/Users/bigluck/my_project_2'

Working on: /Users/bigluck/my_project_2
make[1]: Leaving directory '/Users/bigluck/my_project_2'
[postgres	]
[postgres	] PostgreSQL database directory appears to contain a database; Skipping initialization
[postgres	]
...
```

**Version**
 
```
devenv: 0.6.3
```

**Comment by mcdonc** [comment]
You might try changing the `process-managers.process-compose.settings.port` setting to different ports on each projects.  The default is 9999.

**Comment by bigluck** [comment]
Oh yess! Awesome (I didn't take it into account).

In my case I'm now setting the port number using:

```bash
  process.process-compose = {
    version = "0.69.0";
    port = 12345;
    tui = "false";
  };
```

Thanks @mcdonc

**Comment by thenonameguy** [comment]
@bigluck you can also something like this:
https://github.com/schemamap/schemamap/commit/c8ed919e140eb55bbf5141e0629195a488b8b0ab#diff-cef540503c67fa4a36d1b9fe95a62f979c4b8b2bc43a6e023e250b7154341afcR97

Then you can just invoke `process-compose` directly (without the extra devenv up evaluation costs!).
With the above you can provide the port explicitly as well, or create a wrapper script (like `ci-test`).
