### ISSUE TITLE
How to use Python Poetry when the files are located in a sub directory?

### ISSUE THREAD

**Issue by Nebucatnetzer** [cachix/devenv#941]
My project setup is like this:

```
.
├── ansible
│   ├── poetry.lock
│   ├── poetry.toml
│   ├── pyproject.toml
│   ├── README.md
│   ├── renovate.json
│   ├── requirements_ansible_galaxy.yml
├── bin
│   └── dev
├── flake.lock
├── flake.nix
├── README.md
```

Currently I'm using direnv to create and setup the poetry venv.
Is there a way to create the venv with devenv when the files aren't located in the root of the project?

**Comment by domenkozar** [comment]
See https://github.com/cachix/devenv/pull/899

**Comment by Nebucatnetzer** [comment]
Perfect, is it ready to test?
Are you looking for feedback?

**Comment by domenkozar** [comment]
Yeah, give it a go and let me know if it works. I haven't tested it yet.

**Comment by totoroot** [comment]
@Nebucatnetzer I've proposed some changes in #993, if you are willing to test them. I'm happy about any feedback.

**Comment by Nebucatnetzer** [comment]
Please excuse, I must have missed your answer. We found another solution in the end and your pull request got merged by now.
