### ISSUE TITLE
Broken Clang on MacOS (nix-darwin)

### ISSUE THREAD

**Issue by alecandido** [cachix/devenv#951]
**Describe the bug**
Trying to compile a simple `hello.cpp` program is failing, because of c++abi not found.

**To reproduce**
I'm actually using a flake
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    systems.url = "github:nix-systems/default";
    devenv.url = "github:cachix/devenv";
  };

  outputs = {
    self,
    nixpkgs,
    devenv,
    systems,
    ...
  } @ inputs: let
    forEachSystem = nixpkgs.lib.genAttrs (import systems);
  in {
    devShells =
      forEachSystem
      (system: let
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        # ----------------------------------------------------
        default = pkgs.mkShell {
          buildInputs = with pkgs; [clang];
        };
        # ----------------------------------------------------
        # default = devenv.lib.mkShell {
        #   inherit inputs pkgs;
        #
        #   modules = [
        #     {
        #       packages = with pkgs; [clang];
        #     }
        #   ];
        # };
        # ----------------------------------------------------
        # default = devenv.lib.mkShell {
        #   inherit inputs pkgs;
        #
        #   modules = [
        #     {
        #       languages.cplusplus.enable = true;
        #     }
        #   ];
        # };
        # ----------------------------------------------------
      });
  };

  nixConfig = {
    extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
    extra-substituters = "https://devenv.cachix.org";
  };
}
```

I defined three shells (uncommenting each one of the subdivided sections), and run
```sh
nix develop --impure
clang++ hello.cpp
```
with the customary `hello.cpp`:
```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

In the first case (no `devenv`) everything works smoothly (even without `--impure`, of course), and running `./a.out` I obtain the usual `Hello, World!` output.
In the other two cases, I'm unable to compile. The result is:
```sh
❯ nix develop --impure
(devenv) bash-5.2$ clang++ hello.cpp
ld: warning: directory not found for option '-L/nix/store/qfdj687ndydj5mfd60y5ip43d1jgqb6j-devenv-profile/lib'
ld: library not found for -lc++abi
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
(the hash may change, I tried with multiple versions of `nixpkgs`, including `nixos-23.11` and `nixpkgs-23.11-darwin, on top of the two options in the flake)

I'm not sure what is actually happening...

**Version**
 
I attach the whole `flake.lock`.

[flake.zip](https://github.com/cachix/devenv/files/14026603/flake.zip)

I'm on MacOS, with ARM architecture (Apple Silicon).
```sh
❯ sw_vers
ProductName:            macOS
ProductVersion:         14.2.1
BuildVersion:           23C71
```

**Comment by domenkozar** [comment]
I think we have a clang option somewhere that you have to enable, but I might be wrong.

**Comment by alecandido** [comment]
The only references to Clang in the [`devenv.nix` docs](https://devenv.sh/reference/options/#pre-commithooks) are:
https://github.com/cachix/devenv/blob/ad0ae333b210e31237e1fc4a7ddab71a01785add/docs/reference/options.md?plain=1#L3844-L3850

**Comment by DaniruKun** [comment]
My workaround was adding `pkgs.libcxxabi`

**Comment by mrfelton** [comment]
I've found that clang breaks in this way if I have multiple languages enabled.

For example if I have the following then I get problems with clang when using golang.

```
languages.ruby.enable = true;
languages.rust.enable = true;
languages.go.enable = true;
```

But with only go enabled as below, it works just fine.

```
languages.go.enable = true;
```

**Comment by hurricanehrndz** [comment]
I can confirm the issue.

**Comment by hurricanehrndz** [comment]
> My workaround was adding `pkgs.libcxxabi`

This didn't work for me

**Comment by domenkozar** [comment]
Does it also happen on #745

**Comment by domenkozar** [comment]
Could someone try with 1.0.1 that was released yesterday?

**Comment by alecandido** [comment]
I am going to test it immediately

**Comment by domenkozar** [comment]
Closing, please reopen if still broken.
