### ISSUE TITLE
Postgres init script fails on MacOS: Unix-domain socket path is too long (maximum 103 bytes)

### ISSUE THREAD

**Issue by bigluck** [cachix/devenv#952]
Hi all, I'm back :)
After the last MacOS Update (14.3) I'm facing again the "Unix-domain socket path is too long" issue on my Mac.

The issue happens here:

https://github.com/cachix/devenv/blob/ad0ae333b210e31237e1fc4a7ddab71a01785add/src/modules/services/postgres.nix#L81-L125

Essentially the postgres service starts the DB (only during the first setup) using a socket server, ignoring all the user's configurations.
Indeed the path is set to:

```bash
PGHOST=$(mktemp -d "$DEVENV_STATE/pg-init-XXXXXX")
```

In my case, it means:

```bash
[postgres	] 2024-01-24 09:59:14.557 GMT [41621] LOG:  Unix-domain socket path "/Users/bigluck/b/<11 chars dir name>/<32 chars dir name>/service/.devenv/state/pg-init-fv97zJ/.s.PGSQL.35431" is too long (maximum 103 bytes)
```

I've already moved the project root into `/Users/bigluck/b/`, but:
- I can not change my username :D
- I can not move the service to a different location

This is the current workaround I have in place:

```nix
{ pkgs, lib, ... }:

# See full reference at https://devenv.sh/reference/options/
{
  dotenv.disableHint = true;

  # https://devenv.sh/reference/options/#entershell
  enterShell = "
    mkdir -p /tmp/my-project-name
  ";

  # https://devenv.sh/packages/
  packages = [ ... ];

  # https://devenv.sh/languages/
  languages.python = { ... };

  # https://devenv.sh/reference/options/#processimplementation
  process.implementation = "process-compose";

  # https://devenv.sh/services/
  services.postgres = {
    enable = true;
    package = pkgs.postgresql_15;
    listen_addresses = "127.0.0.1";
    port = 35431;
    initialDatabases = [{ name = "MY_DB_NAME"; } ];
    initialScript = ''
      CREATE USER MY_DB_USER WITH PASSWORD 'MY_PASSWORD';

      GRANT ALL PRIVILEGES ON DATABASE ${toString bpln_service.db_name} TO postgres;
      ALTER DATABASE MY_DB_NAME OWNER TO MY_DB_USER;
    '';
  };

  # https://devenv.sh/processes/
  processes = {
    postgres = {
      process-compose = {
        environment = [
          "DEVENV_STATE=/tmp/my-project-name"
        ];
      };
    };
  };
}
```

Essentially I'm overwriting the `DEVENV_STATE` ENV only for the postgres service; it works, but it's a workaround.

**Comment by domenkozar** [comment]
Most likely a duplicate of #540

**Comment by shymega** [comment]
Outsider here, but I've come across this issue as well - think for organisation, we should close this issue, and move resolution discussions to #540.

A solution to me is to use the OS-native `tmp` for sockets but keep `PGDATA` in the usual 'state' directory.

(I've tried disabling unix sockets, but it's always forced as enabled)

**Comment by bigluck** [comment]
Following @shymega suggestion, I’m closing this issue in favor of #540
