### ISSUE TITLE
Rename `devenv processes stop` to `devenv processes down`

### ISSUE THREAD

**Issue by tseaver** [cachix/devenv#970]
For clarity / compatibility with simliar usage in `Docker Compose`.

- Leave `devenv processes stop` as an alias.
- Add `devenv down` as an alias (maybe `devenv stop` too?)

**Comment by domenkozar** [comment]
I'm totally down for this.

**Comment by tseaver** [comment]
I'd be happy to help, but for the life of me can't find where the Python CLI bits live in the repo.

**Comment by domenkozar** [comment]
You need the rewrite branch: https://github.com/cachix/devenv/blob/python-rewrite/src/devenv/cli.py

**Comment by domenkozar** [comment]
In 1.0.2

```
❯ devenv processes
Start or stop processes.

Usage: devenv processes <COMMAND>

Commands:
  up    
  down  
  help  Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```
