### ISSUE TITLE
mysql cli probably shouldn't define --defaults-file

### ISSUE THREAD

**Issue by Nebucatnetzer** [cachix/devenv#973]
**Describe the bug**

We try to use drush[1] in a devenv environment.
However we noticed that we couldn't run tasks that try to access the database because we got the following error:
```
Error Output:
  ================

  In SqlCommands.php line 183:

Query failed. Rerun with --debug to see any error message. /nix/store/g9w07skpvyy47a0l6xgyscdlv5dbd6f7-mariadb-server-10.11.6/bin/mysql: unknown variable 'defaults-file=/tmp/drush_Po73Fh'
```
It turned out that it was caused by the `--defaults-file` option on the mysql cli as defined by devenv[2][3].
When we used `--defaults-extra-file` in `devenv` the drush commands were working again because `--defaults-file` had precedence[4]. 

Would it make sense for devenv to use `--defaults-extra-file` instead of the current `--defaults-file`?

For the moment we override the command with the following snippet.
Would there be a better way?

```
scripts.mysql.exec = lib.mkForce ''
    exec ${config.services.mysql.package}/bin/mysql "$@"
'';
```

The other thing we noticed is  that even when we don't provide any options in `settings` it still generates an empty file and passes that with `--defaults-file`. Shouldn't the config file only be added as a parameter if `settings` actually contains any values?
Something like this?

```
if cfg.settings:
  configFile = format.generate "my.cnf" cfg.settings;

mysqlOptions = "";
if configFile:
  mysqlOptions = "--defaults-file=${configFile}";
```

[1]: https://www.drush.org/12.x/
[2]: https://github.com/cachix/devenv/blob/main/src/modules/services/mysql.nix#L11
[3]: https://github.com/cachix/devenv/blob/main/src/modules/services/mysql.nix#L258
[4]: https://dev.mysql.com/doc/refman/8.0/en/option-file-options.html#option_general_defaults-file

**To reproduce**

Will provide if required but I think it's more a thing to discuss as an actual bug.

**Comment by domenkozar** [comment]
cc @shyim

**Comment by shyim** [comment]
Hey,

we did that because some users had `/etc/my.cnf` and so on. and this will win against `--defaults-extra-file`

**Comment by Nebucatnetzer** [comment]
Makes sense, maybe a flag to toggle it off would make sense?
Force overriding feels a bit like a hacky or would recommend to do it this way?

**Comment by shyim** [comment]
I am open to make it configureable 🤔, so it's possible to turn it off

**Comment by Nebucatnetzer** [comment]
I will try to make a merge request. 
However I don’t know if I‘m good enough with Nix to do something like this😅.

**Comment by shyim** [comment]
Let me know if you need any help. We have also a Devenv discord :)
