### ISSUE TITLE
Resolve environment variables in config

### ISSUE THREAD

**Issue by samoht9277** [cachix/devenv#988]
**Describe the bug**
When declaring my `caddy` service, I have a environment variable called `DOMAIN`. When declaring the caddy's config, `devenv` can't resolve the environment variable, and throws an error.

**To reproduce**
- Create a devenv.nix file
- Add a `caddy` service 
- And an environment variable.
- Reference that environment variable inside the caddy config.

https://gist.github.com/samoht9277/1730d2bea504fc264bde5a58fd4bc6d7

> Building shell ...
error: builder for '/nix/store/6izk0lzi3sk1h9ak8drylh12rivn9gmq-caddy-config-adapted.json.drv' failed with exit code 1;
       last 1 log lines:
       > Error: subject does not qualify for certificate: '$domain'
       For full logs, run 'nix log /nix/store/6izk0lzi3sk1h9ak8drylh12rivn9gmq-caddy-config-adapted.json.drv'.
error: 1 dependencies of derivation '/nix/store/33s76wmb9qm4vn54rgh2zai62dgp3khj-caddy-config.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g3zaq0h3rjvyzrw17n2hdzwdy7p90ayq-caddy.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kh5x258b34j3zr0nvnmz537d3x34nmil-procfile.drv' failed to build
error:
       error: 1 dependencies of derivation '/nix/store/00hiz9a05rcf7ppayfismf9a45as9vp1-devenv-up.drv' failed to build

I believe that the environment variables should be resolved at runtime, inside the config declaration.

**Version**
 
devenv: 0.6.3

**Comment by thenonameguy** [comment]
Thanks for the great description.

Let's not call a feature request a bug, as providing environment variables to internal config builds wasn't never meant to be a feature yet.

The relevant code is here: https://github.com/cachix/devenv/blob/main/src/modules/services/caddy.nix#L54-L56

`{ } ` should be replace with the  `config.env`, for a basic implementation.

**Comment by samoht9277** [comment]
This is a must have! I believe this should be implemented in order to avoid rewriting the same string multiple times.

**Comment by domenkozar** [comment]
Any reason not to use `${config.env.domain}`?

**Comment by domenkozar** [comment]
Resolving due to previous comment, let me know if that doesn't work.

**Comment by samoht9277** [comment]
@domenkozar That worked. Replacing `$DOMAIN` with `${config.env.domain}` does in fact replace the variable at runtime. For any future reader, remember to add the `config` import at the top of your code.

```
{ pkgs, lib, config, ... }: {
             ^^^^^
```
